### ISSUE TITLE
Windows下运行出错

### ISSUE THREAD

**Issue by ChanceDoor** [yeszao/dnmp#1]
Starting lnmp_mysql_1

ERROR: for mysql  Cannot start service mysql: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/F/docker/lnmp/conf/mysql/mysql.cnf\\\" to rootfs \\\"/var/lib/docker/overlay2/c7c277a751ceb21a014548e0625fbbbf9f141179ccf4d596bb89b8e6dd08cf9a/merged\\\" at \\\"/var/lib/docker/overlay2/c7c277a751ceb21a014548e0625fbbbf9f141179ccf4d596bb89b8e6dd08cf9a/merged/etc/mysql/conf.d/mysql.cnf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by yeszao** [comment]
已修复，重新克隆一份就可以了 : )
