### ISSUE TITLE
错误： No releases available for package "pecl.php.net/redis"解决

### ISSUE THREAD

**Issue by yeszao** [yeszao/dnmp#10]
pecl -vvv install redis-3.1.4

`Warning: file_exists(): Unable to find the wrapper "channel" - did you forget to enable it when you configured PHP? in PEAR/Downloader/Package.php on line 1511

Warning: is_file(): Unable to find the wrapper "channel" - did you forget to enable it when you configured PHP? in PEAR/Downloader/Package.php on line 1521

Warning: is_file(): Unable to find the wrapper "channel" - did you forget to enable it when you configured PHP? in PEAR/Downloader/Package.php on line 1521

Warning: fsockopen(): Failed to enable crypto in PEAR/Proxy.php on line 179

Warning: fsockopen(): unable to connect to ssl://pecl.php.net:443 (Unknown error) in PEAR/Proxy.php on line 179
No releases available for package "pecl.php.net/redis"
Cannot initialize 'channel://pecl.php.net/redis-3.1.4', invalid or missing package file
Package "channel://pecl.php.net/redis-3.1.4" is not valid
install failed`

**Comment by yeszao** [comment]
这个错误主要是因为国网络访问外网受限所致。
解决的方法是，
在用`pecl install`之前，给pear加上proxy，Dockerfile中：
```
RUN pear config-set http_proxy http://10.0.75.1:1080
```
注意，其中的IP要换成可用的proxy IP。
按说，用`pecl config-set`也可以，不过试了没用成功，用`pear`可以。

**Comment by yeszao** [comment]
如果没有代理的话，可以从[pecl.php.net](http://pecl.php.net/)下载源码包，然后参考`/php/php54/Dockerfile`文件的最后7行，通过源码包方式安装。

**Comment by zhoutengfu** [comment]
我是在自己的mac上安装的，RUN pear config-set http_proxy http://192.168.2.81(主机IP)，mac上是开了代理服务器的，我是哪里配置错了吗

**Comment by yeszao** [comment]
可以ping通主机的IP吗？如果ping不通，用docker虚拟出来的IP，比如示例中的：10.0.75.1

**Comment by FromChinaBoy** [comment]
RUN pear config-set http_proxy http://10.0.75.1:1080  这个在那里的呀，找不到这段，dockerfile没有呀

**Comment by Dshufeng** [comment]
关于有墙的问题.其实更简单的方法是利用好[dockerhub](https://hub.docker.com/)的自动构建功能,相当于做了下中转.

**Comment by liuqingliu** [comment]
老板，您故意的吧。我直接把您这句“RUN pear config-set http_proxy http://10.0.75.1:1080”给删了。就可以了。。。害得我好辛苦。。。

**Comment by cymsummer** [comment]
感谢楼上的评论，拯救了我！

**Comment by larlence100** [comment]
@liuqingliu 我删了 也可以用了

**Comment by chendongdongdd01** [comment]
@larlence100 可以告诉我是在哪个文件里面有这个吗，具体的路径，为啥我都找不到这个

**Comment by chendongdongdd01** [comment]
@liuqingliu 知道了，被博主删除了，再拉一次master分支就行了

**Comment by yeszao** [comment]
@liuqingliu @larlence100 @cymsummer 加了php72后没删掉，抱歉~已经修正

**Comment by liuqingliu** [comment]
@yeszao 谢谢大佬。很厉害！

**Comment by MRchenao** [comment]
楼主的这个安装了好久，跟大家出现一样的错误，但是又很不想使用楼主说的7行代码那么长的源码安装方式。所以改成了如下方式，成功了。记录一下分享给大家。

RUN sudo apt-get install php-dev php-pear autoconf automake libtool  -y

COPY ./redis-3.1.5.tgz /var/www/html/
RUN curl 'http://pecl.php.net/get/xdebug-2.6.0alpha1.tgz' -o /var/www/html/xdebug-2.6.0alpha1.tgz

#RUN cd /tmp/ \
#    && tar -xf redis-3.1.4.tgz \
#    && rm redis-3.1.4.tgz \
#    && (cd redis-3.1.4 && phpize && ./configure && make && make install) \
#    && rm -r redis-3.1.4 \
#    && docker-php-ext-enable redis

RUN pecl install redis-3.1.5.tgz \
    && rm -rf redis-3.1.5.tgz \
    && docker-php-ext-enable redis \
    && :\
    && pecl install xdebug-2.6.0alpha1.tgz \
    && rm -rf xdebug-2.6.0alpha1.tgz \
    && docker-php-ext-enable xdebug \

**Comment by yeszao** [comment]
@MRchenao 👍

**Comment by haydenzhourepo** [comment]
@ADirtyCat  why docker-php-ext-enable not found

**Comment by ADirtyCat** [comment]
> @ADirtyCat why docker-php-ext-enable not found
看你的基础容器是什么 
FROM php:7.1-fpm

**Comment by yeszao** [comment]
@MRchenao @ADirtyCat 总结得很好

唯一担心的就是，我的网络经常 **pecl.php.net** 都得用梯子，无语啊～～我猜不少人也是一样的情况。
所以要分两种情况，网络顺畅的时候，用 curl/wget 
要是网络不好，就用现成的包

**Comment by wonbin2011** [comment]
加上代理好使了，建议楼主以后发dockerfile 尽量把自己的配置信息去掉。没有坑到我 ，我都是用官方的

**Comment by yeszao** [comment]
@wonbin2011 早已经没有咯～
