### ISSUE TITLE
Windows 10 for docker 安装报错

### ISSUE THREAD

**Issue by 188660660** [yeszao/dnmp#102]
![image](https://user-images.githubusercontent.com/20714428/49726419-e581e280-fca8-11e8-8b2d-08849aef4607.png)

博主您好 在执行docker up的时候就提示报错 我安装的是w10的docker，请问如何解决

**Comment by yeszao** [comment]
有可能是网络问题，多试几下

**Comment by skylei** [comment]
@188660660 更换一下mirror 
https://opsx.alibaba.com/mirror
找一下你对应的mirrors

**Comment by 188660660** [comment]
> 有可能是网络问题，多试几下

https://mirrors.ustc.edu.cn/debian/dists/stable/InRelease
作者您好  他报错中有个路径地址 没有反应  
如何更换这个 
https://mirrors.ustc.edu.cn/debian/dists/stable/Release  InRelease少了一个In好像可以正常访问

**Comment by yeszao** [comment]
可以换个源，修改文件：/sources.list

**Comment by skylei** [comment]
@188660660 
找到根目录中的这个文件：./sources.list
以前的注释掉（每一行的前面加#）,之后内容拷贝下面贴入试试：
`deb http://mirrors.163.com/debian/ jessie main
deb http://mirrors.163.com/debian/ jessie-updates main
deb http://mirrors.163.com/debian-security/ jessie/updates main
deb http://mirrors.163.com/debian/ jessie main non-free contrib
deb http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib
deb-src http://mirrors.163.com/debian/ jessie main non-free contrib
deb-src http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib
deb http://mirrors.163.com/debian/  stretch main non-free contrib
deb http://mirrors.163.com/debian/  stretch-updates main non-free contrib
deb http://mirrors.163.com/debian/  stretch-backports main non-free contrib
deb-src http://mirrors.163.com/debian/  stretch main non-free contrib
deb-src http://mirrors.163.com/debian/  stretch-updates main non-free contrib
deb-src http://mirrors.163.com/debian/  stretch-backports main non-free contrib
deb http://mirrors.163.com/debian-security/  stretch/updates main non-free contrib
deb-src http://mirrors.163.com/debian-security/  stretch/updates main non-free contrib`

**Comment by 188660660** [comment]
![image](https://user-images.githubusercontent.com/20714428/50046324-aefafc00-00dc-11e9-8bb7-c19d7056b87a.png)
作者您好 根据提示 修改了list文件 更改了以后compose又开始出问题了 提示yml文件无效 好头疼额 yml文件没有做过更改  其他朋友有遇到过这种情况吗 0 0 我的为啥这么衰啊
![image](https://user-images.githubusercontent.com/20714428/50046475-e9fe2f00-00de-11e9-87b8-825efcca93a9.png)

**Comment by yeszao** [comment]
把env.sample改成.env了吗？
