### ISSUE TITLE
神经病

### ISSUE THREAD

**Issue by wuchuheng** [yeszao/dnmp#104]
本想安安静静找个docker 的web运行环境，都他妈整成什么了，一个好好的开箱就用工具，都他妈，又是构建又地安装又是编译，好几个小时就过去，要是配置低就直接killed掉。都它妈一群瞎折腾白痴。写一个复杂了不起的构建文件了不起啊，不知道，程序最重要的是稳定吗？越复杂的构建文件风越依赖网络下载第3方库在构建时风险越大，天知道第3方依赖什么时候挂了，什么时候迭代了，这都是不稳定的因素，要是哪个依赖不成功下载来，你能确保你的构建的镜像就是稳定的？你能确保你的镜像就不用再测试测试？构建都他妈那长时间还谈什么开箱即用。都他妈一群什么人啊，直接拉好已经建构好的测试好的镜像才是王道，重复造轮子有意思吗？把你构建好的镜像上传到镜像库会死啊。docker为什么那么受人喜爱？是开箱即用啊？

**Comment by yeszao** [comment]
骚年，别怕麻烦
