### ISSUE TITLE
php容器里面跑带有node的命令

### ISSUE THREAD

**Issue by alexxd35** [yeszao/dnmp#108]
用了fastadmin，我在php的容器里面跑一个指令是压缩js css的（php think min -m all -r js），然后他报需要有node环境才可以，请问怎样可以实现呢？只能在php容器里装node吗，还是可以有别的方法？

**Comment by yeszao** [comment]
在容器里面装node，或者加一个node容器，在node容器里面打包

**Comment by alexxd35** [comment]
感觉还是在php容器装node比较简单了，因为他那个命令是php的，在另外的node容器里面估计也跑不了php命令
