### ISSUE TITLE
Mac上真正开发由于IO问题导致服务器太慢了

### ISSUE THREAD

**Issue by saybye720** [yeszao/dnmp#110]
希望作者有时间的话，帮我们把 docker-bg-sync 这个也搞进去吧，谢谢

**Comment by skylei** [comment]
@saybye720 
麻烦提供一下慢的情况描述一下。

**Comment by wangcong099878** [comment]
@skylei 就是裸跑Laravel 5.6也非常慢   在代码从宿主机挂载进去的情况下

**Comment by yeszao** [comment]
@saybye720 可以搞一个然后提交pull request

**Comment by isecret** [comment]
docker-bg-sync 在我本机上有很高的几率不同步，只能每次重新 clean && start，每次要等很久。不知道还有没有更优的方案。

**Comment by isecret** [comment]
修正一下，我是用的 docker-sync。
