### ISSUE TITLE
源好像有问题

### ISSUE THREAD

**Issue by xingyu-Lu** [yeszao/dnmp#113]
E: Unable to locate package libfreetype6-dev
E: Unable to locate package libjpeg62-turbo-dev
E: Unable to locate package libpng-dev

I can't find a way to solve this problem~

**Comment by xingyu-Lu** [comment]
please help

**Comment by xingyu-Lu** [comment]
W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/stable/InRelease  Temporary failure resolving 'mirrors.ustc.edu.cn'
W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/stable-updates/InRelease  Temporary failure resolving 'mirrors.ustc.edu.cn'
W: Failed to fetch http://deb.debian.org/debian/dists/buster/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/buster/updates/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/buster-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by yeszao** [comment]
根目录下有个 source.list，替换里面的源再试

**Comment by skylei** [comment]
@xingyu-Lu @yeszao 

# deb http://mirrors.ustc.edu.cn/debian stable main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable main contrib non-free
# deb http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable-updates main contrib non-free

# deb http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free
# deb-src http://mirrors.ustc.edu.cn/debian stable-proposed-updates main contrib non-free

deb http://mirrors.163.com/debian/ jessie main
deb http://mirrors.163.com/debian/ jessie-updates main
deb http://mirrors.163.com/debian-security/ jessie/updates main
deb-src http://mirrors.163.com/debian/ jessie main non-free contrib
deb-src http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib
deb http://mirrors.163.com/debian/  stretch main non-free contrib
deb http://mirrors.163.com/debian/  stretch-updates main non-free contrib
deb http://mirrors.163.com/debian/  stretch-backports main non-free contrib
deb-src http://mirrors.163.com/debian/  stretch main non-free contrib
deb-src http://mirrors.163.com/debian/  stretch-updates main non-free contrib
deb-src http://mirrors.163.com/debian/  stretch-backports main non-free contrib
deb http://mirrors.163.com/debian-security/  stretch/updates main non-free contrib
deb-src http://mirrors.163.com/debian-security/  stretch/updates main non-free contrib

**Comment by xingyu-Lu** [comment]
> @xingyu-Lu @yeszao
> 
> deb http://mirrors.163.com/debian/ jessie main
> deb http://mirrors.163.com/debian/ jessie-updates main
> deb http://mirrors.163.com/debian-security/ jessie/updates main
> deb-src http://mirrors.163.com/debian/ jessie main non-free contrib
> deb-src http://mirrors.163.com/debian/ jessie-proposed-updates main non-free contrib
> deb http://mirrors.163.com/debian/ stretch main non-free contrib
> deb http://mirrors.163.com/debian/ stretch-updates main non-free contrib
> deb http://mirrors.163.com/debian/ stretch-backports main non-free contrib
> deb-src http://mirrors.163.com/debian/ stretch main non-free contrib
> deb-src http://mirrors.163.com/debian/ stretch-updates main non-free contrib
> deb-src http://mirrors.163.com/debian/ stretch-backports main non-free contrib
> deb http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib
> deb-src http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib

thanks it works~

**Comment by xingyu-Lu** [comment]
> 根目录下有个 source.list，替换里面的源再试

好的

**Comment by xingyu-Lu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        编译过程中有时会报错，这是其中的，不知道会不会有影响呢~，感谢大牛
        
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2273466984
                            
                    
                        
                            
                                    2273466984@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年1月25日 13:45，Gary Meng<notifications@github.com> 写道： 


根目录下有个 source.list，替换里面的源再试



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by skylei** [comment]
@xingyu-Lu 把日志发出来，不要直接邮件回复

![image](https://user-images.githubusercontent.com/1855591/51730788-bcc87780-20b3-11e9-88c7-997459489aa8.png)

**Comment by sincez** [comment]
换了163源，现在报这种错，怎么解决呢
W: The repository 'http://mirrors.163.com/debian jessie-backports Release' does not have a Release file.
E: Failed to fetch http://mirrors.163.com/debian/dists/jessie-backports/contrib/source/Sources  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y libfreetype6 libjpeg62-turbo-dev libpng-dev     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && :    && apt-get install -y libicu-dev     && docker-php-ext-install intl     && :    && apt-get install -y libxml2-dev libxslt-dev     && docker-php-ext-install soap     && docker-php-ext-install xmlrpc     && docker-php-ext-install xsl     && :    && apt-get install -y libpq-dev     && docker-php-ext-install pdo     && docker-php-ext-install pdo_mysql     && docker-php-ext-install mysqli     && docker-php-ext-install pdo_pgsql     && docker-php-ext-install pgsql     && :    && docker-php-ext-install bcmath     && docker-php-ext-install gettext     && docker-php-ext-install opcache     && docker-php-ext-install pcntl     && docker-php-ext-install sockets     && docker-php-ext-install zip     && docker-php-ext-install redis' returned a non-zero code: 100
