### ISSUE TITLE
docker-compose ps出现警告和错误

### ISSUE THREAD

**Issue by xingyu-Lu** [yeszao/dnmp#115]

**Comment by xingyu-Lu** [comment]
WARNING: The PHPMYADMIN_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The PHP56_XDEBUG variable is not set. Defaulting to a blank string.
WARNING: The REPLACE_SOURCE_LIST variable is not set. Defaulting to a blank string.
WARNING: The PHP56_SWOOLE variable is not set. Defaulting to a blank string.
WARNING: The PHP56_REDIS variable is not set. Defaulting to a blank string.
WARNING: The PHP56_VERSION variable is not set. Defaulting to a blank string.
WARNING: The SOURCE_DIR variable is not set. Defaulting to a blank string.
WARNING: The PHP56_PHP_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP56_FPM_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP54_XDEBUG variable is not set. Defaulting to a blank string.
WARNING: The PHP54_SWOOLE variable is not set. Defaulting to a blank string.
WARNING: The PHP54_REDIS variable is not set. Defaulting to a blank string.
WARNING: The PHP54_VERSION variable is not set. Defaulting to a blank string.
WARNING: The PHP54_PHP_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP54_FPM_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP72_XDEBUG variable is not set. Defaulting to a blank string.
WARNING: The PHP72_SWOOLE variable is not set. Defaulting to a blank string.
WARNING: The PHP72_REDIS variable is not set. Defaulting to a blank string.
WARNING: The PHP72_VERSION variable is not set. Defaulting to a blank string.
WARNING: The PHP72_PHP_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The PHP72_FPM_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The REDIS_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The REDIS_VERSION variable is not set. Defaulting to a blank string.
WARNING: The REDIS_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The NGINX_CONFD_DIR variable is not set. Defaulting to a blank string.
WARNING: The NGINX_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The NGINX_LOG_DIR variable is not set. Defaulting to a blank string.
WARNING: The NGINX_VERSION variable is not set. Defaulting to a blank string.
WARNING: The NGINX_HTTP_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The NGINX_HTTPS_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_ROOT_PASSWORD variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_CONF_FILE variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_DATA_DIR variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_VERSION variable is not set. Defaulting to a blank string.
WARNING: The MYSQL_HOST_PORT variable is not set. Defaulting to a blank string.
WARNING: The REDISMYADMIN_HOST_PORT variable is not set. Defaulting to a blank string.
ERROR: The Compose file './../../docker-compose.yml' is invalid because:
services.mysql.ports is invalid: Port ranges don't match in length
services.nginx.ports is invalid: Port ranges don't match in length
services.redis.ports is invalid: Port ranges don't match in length
services.nginx.ports is invalid: Port ranges don't match in length
services.phpmyadmin.ports is invalid: Port ranges don't match in length
services.phpredisadmin.ports is invalid: Port ranges don't match in length

**Comment by zwl2012** [comment]
.env文件丢失吧

**Comment by xingyu-Lu** [comment]
> .env文件丢失吧
我的.env文件在

**Comment by skylei** [comment]
@xingyu-Lu 
查看一下`.env`是否正确

**Comment by xingyu-Lu** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        好的，谢谢啦
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                2273466984
                            
                    
                        
                            
                                    2273466984@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年2月11日 22:17，Raymond<notifications@github.com> 写道： 


@xingyu-Lu

查看一下.env是否正确



—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Ya-hui** [comment]
需要在当前目录 dnmp下 运行 docker-compose 命令
