### ISSUE TITLE
文件挂载不上了

### ISSUE THREAD

**Issue by jiushang1314** [yeszao/dnmp#116]
ERROR: for dnmp_nginx_1  Cannot start service nginx: OCI runtime create failed:  container_linux.go:344: starting container process caused "process_linux.go:424:  container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/e/dnmp/conf/ nginx.conf\\\" to rootfs \\\"/var/lib/docker/overlay2/f24304d6e9ec830e7574bb4fc9 96f3519ce4d48275f80aa42cf02b212a132189/merged\\\" at \\\"/var/lib/docker/overlay 2/f24304d6e9ec830e7574bb4fc996f3519ce4d48275f80aa42cf02b212a132189/merged/etc/ng inx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to  mount a directory onto a file (or vice-versa)? Check if the specified host path  exists and is the expected type                                                                                                                                  ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: contain er_linux.go:344: starting container process caused "process_linux.go:424: contai ner init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/e/dnmp/conf/nginx.c onf\\\" to rootfs \\\"/var/lib/docker/overlay2/f24304d6e9ec830e7574bb4fc996f3519 ce4d48275f80aa42cf02b212a132189/merged\\\" at \\\"/var/lib/docker/overlay2/f2430 4d6e9ec830e7574bb4fc996f3519ce4d48275f80aa42cf02b212a132189/merged/etc/nginx/ngi nx.conf\\\" caused \\\"not a directory\\\"\"": unknown: **Are you trying to mount  a directory onto a file (or vice-versa)?** Check if the specified host path exists  and is the expected type                                                        Encountered errors while bringing up the project.

**Comment by jiushang1314** [comment]
只能挂载目录了

**Comment by skylei** [comment]
请尝试使用最新的Docker Community版本试试

**Comment by yeszao** [comment]
按下面步骤排除问题：
1. 确定文件确实存在
2. 确定文件有相应权限
3. 重启docker
4. 重装 docker
