### ISSUE TITLE
跑Laravel框架非常慢

### ISSUE THREAD

**Issue by wangcong099878** [yeszao/dnmp#119]
恩，非常好用的项目，一键就可以搭建起开发环境，不过跑Laravel空框架都非常慢，在代码从宿主机挂载进去的情况下，用xhprof发现慢在挂载文件上，请问这个有什么解决方案吗

**Comment by yeszao** [comment]
是在Mac上吧？用docker-bg-sync等工具解决吧

**Comment by skylei** [comment]
@wangcong099878 该环境适合适用与开发，生产环境请慎重使用！！，正式环境一般会有专门的环境运行
