### ISSUE TITLE
请问这个 php72是如何映射到对应容器的 ip 的?

### ISSUE THREAD

**Issue by yhq1994** [yeszao/dnmp#120]
您好,看到这段Nginx 配置代吗`   fastcgi_pass   php72:9000;`  ,这个 php72 是在哪里设置的? 之前自己配置的服务器是这样的` 127.0.0.1:9000 `,这个是如何映射到容器的 IP 上呢?  docker 新手,这里不太理解.

**Comment by yeszao** [comment]
通过虚拟网卡，不是设置了一个networks不

**Comment by yhq1994** [comment]
> 通过虚拟网卡，不是设置了一个networks不

谢谢
