### ISSUE TITLE
php对宿主机数据卷目录不可写

### ISSUE THREAD

**Issue by jason0773** [yeszao/dnmp#121]
centos 7下， php对宿主机数据卷目录不可写
  ，不可写的目录更改777 才能写入

**Comment by skylei** [comment]
@jason0773 请给出一些错误信息

**Comment by Totn** [comment]
> @jason0773 请给出一些错误信息

php容器在宿主机mkdir无权限，进入php容器查看www项目目录 ``` ls -l ```
显示用户 1000，组 994

**Comment by yeszao** [comment]
@Totn 如果 www 目录的拥有者在容器中不存在，那么容器的权限就会直接显示其 UID和GID，在Linux中，一般web用户是www-data，可以手动授权给www-data用户
