### ISSUE TITLE
 Connection refused

### ISSUE THREAD

**Issue by 15527854695** [yeszao/dnmp#123]
SQLSTATE[HY000] [2002] Connection refused

好像是不能访问mysql

**Comment by findmark** [comment]
是不是  容器内之间访问，是的话  直接把 host  改成service 名   e.g.   ['host' => 'mysql', 'port' => 3306]，具体看你配置

**Comment by 15527854695** [comment]
谢谢 ,已经成功的跑起来了!

发送自 Windows 10 版邮件应用

发件人: findmark
发送时间: 2019年3月29日 10:53
收件人: yeszao/dnmp
抄送: 15527854695; Author
主题: Re: [yeszao/dnmp] Connection refused (#123)

是不是 容器内之间访问，是的话 直接把 host 改成service 名 e.g. ['host' => 'mysql', 'port' => 3306]，具体看你配置

**Comment by im55cc** [comment]
@15527854695 我测试了一下，确实是可以的，不过我很好奇，这个是在哪里配置的呢？

**Comment by im55cc** [comment]
@findmark 我试了一下，这个确实是可以的，这个是哪里配置的呢，有什么知识点么？

**Comment by yeszao** [comment]
@im55cc docker中在同一个network的容器可以通过名称来相互访问
