### ISSUE TITLE
php.ini的配置

### ISSUE THREAD

**Issue by 601157475** [yeszao/dnmp#124]
修改display_errors = On 是失败的，测试一下其他选项是可以的，代码中加入ini_set("display_errors", "On");也是可行的。

**Comment by findmark** [comment]
> 修改display_errors = On 是失败的，测试一下其他选项是可以的，代码中加入ini_set("display_errors", "On");也是可行的。

看你描述可能不是dnmp的问题，用的是框架还是别的，建议直接写个 php文件 echo phpinfo()看有没有效果吧，没有的话根据文字debug不出来，有的话就检查下你的框架是不是有debug模式开关，dev/pro env 等等，

**Comment by 601157475** [comment]
我自己的低级错误，后面的配置给覆盖了
