### ISSUE TITLE
MySQL 连接错误

### ISSUE THREAD

**Issue by isecret** [yeszao/dnmp#125]
嘿，我遇到了 [#2](https://github.com/yeszao/dnmp/issues/2) 类似的问题，在 phpMyAdmin 中提示：
```php
mysqli_real_connect(): (HY000/1130): Host '172.21.0.8' is not allowed to connect to this MySQL server
```

不过我重新构建（`docker-compose up -d --force-recreate`）后仍然无法连接，我尝试过进入 MySQL 交互使用 `mysql -u root -p` 中键入密码提示：
```bash
ERROR 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)
```
我使用了来自配置文件中的默认配置，MySQL 相关配置未做任何调整。所以现在密码是个啥我也不知道。

我接下来该怎么做？

**Comment by isecret** [comment]
我尝试更换了版本为 `v5.7.25` 问题解决。真是奇怪。

**Comment by M69W** [comment]
可能是数据库 IP 不对，
用Navicat 可以用localhost连接  
但thinkCMF(thinkphp)报错：
SQLSTATE[HY000] [2002] No such file or directory  
或 数据库账号或密码不正确！SQLSTATE[HY000] [2002] Connection refused
在报错的页面下面看到  

SERVER_ADDR | 172.18.0.4  
REMOTE_PORT | 33806  
REMOTE_ADDR | 172.18.0.1  

然后用172.18.0.1作为数据库服务器地址即可，而不是127.0.0.1或localhost

重装过5次才发现这个问题！

**Comment by yeszao** [comment]
PHP代码连接数据库host直接用：mysql 不就可以了？

M69W <notifications@github.com> 于2019年6月2日周日 上午2:15写道：

**Comment by M69W** [comment]
我换IP就可以了，macOS 上部署 dnmp 的

**Comment by yeszao** [comment]
项目有示例代码的：https://github.com/yeszao/dnmp/blob/master/www/localhost/index.php
