### ISSUE TITLE
php的扩展如何关闭

### ISSUE THREAD

**Issue by 601157475** [yeszao/dnmp#126]
开发阶段 不需要使用opcache等扩展,请问如何关闭

**Comment by isecret** [comment]
在 /extensions/install.sh 中注释 opcache 的安装，然后重新构建。

**Comment by 601157475** [comment]
好的谢谢

**Comment by yeszao** [comment]
新版本已经换了一种方式，更加方便了，需要的扩展在 .env 中指定，不需要的扩展不加就可以了。
