### ISSUE TITLE
PHP 内部虚拟域名的访问

### ISSUE THREAD

**Issue by isecret** [yeszao/dnmp#127]
你好，如何实现多个项目之间虚拟域名的访问呢？比如：本地开发环境配置了 `web.com` 和 `app.com` 两个虚拟域名（本地劫持 `web.com` 和 `app.com` 的 hosts 到 `127.0.0.1`），而在程序里 `web.com` 会对 `app.com` 发起请求呢？似乎就找不到 hosts 地址了。我接下来应该做什么？

**Comment by findmark** [comment]
> 你好，如何实现多个项目之间虚拟域名的访问呢？比如：本地开发环境配置了 `web.com` 和 `app.com` 两个虚拟域名（本地劫持 `web.com` 和 `app.com` 的 hosts 到 `127.0.0.1`），而在程序里 `web.com` 会对 `app.com` 发起请求呢？似乎就找不到 hosts 地址了。我接下来应该做什么？

没试过，但是你可以尝试上nginx容器里 改掉hosts看看

**Comment by isecret** [comment]
改 hosts 应该是在 PHP 的容器里边改为 Nginx 的 IP 吧，但是首先得知道 Nginx 的内网 IP。已知 `ifconfig` 不可用，而且担心 Nginx 的 IP 会变化。

**Comment by isecret** [comment]
问题已经解决，在宿主机中 hosts 改为当前内网 IP 重新构建即可，不能使用 `127.0.0.1`。

**Comment by isecret** [comment]
参考 #91
