### ISSUE TITLE
宿主机上如何使用php-cli? 

### ISSUE THREAD

**Issue by sorshion** [yeszao/dnmp#129]

**Comment by daulCN** [comment]
```
docker run -it --rm php:7.2.13-fpm php -a
```
如果有按readme设置alias可以直接
```
dphp72
php -a
```

**Comment by sorshion** [comment]
php () {
    tty=
    tty -s && tty=--tty
    docker run \
        $tty \
        --interactive \
        --rm \
        --volume $PWD:/var/www/html:rw \
        --workdir /var/www/html \
        dnmp_php72 php "$@"
} 
使用了这个，可以在宿主机上使用

**Comment by skylei** [comment]
> ```
> docker run -it --rm php:7.2.13-fpm php -a
> ```
> 
> 如果有按readme设置alias可以直接
> 
> ```
> dphp72
> php -a
> ```

@sorshion 
可以使用别名方式在主机上设置指向的容器的php-cli

**Comment by skylei** [comment]
@sorshion 
[请查看文档](https://github.com/yeszao/dnmp#4%E6%B7%BB%E5%8A%A0%E5%BF%AB%E6%8D%B7%E5%91%BD%E4%BB%A4)

**Comment by xjimmy906** [comment]
使用readme.md中配置alias方式再host中使用php cli ，默认是没有使用主机的php.ini配置文件的，导致在主机中配置的php.ini项在cli模式下不生效；可以修改下alias指定下挂载的cli文件，代码如下：
```
# php7 cli
php () {
    tty=
    tty -s && tty=--tty
    docker run \
        $tty \
        --interactive \
        --rm \
        --volume $PWD:/www:rw \
        --volume ~/dnmp/services/php/php.ini:/usr/local/etc/php/php.ini:ro \
        --workdir /www \
        dnmp_php php "$@"
}
```
