### ISSUE TITLE
进入nginx容器命令错误

### ISSUE THREAD

**Issue by xuanyue0522** [yeszao/dnmp#131]
![image](https://user-images.githubusercontent.com/22877757/55962082-ce78ee80-5ca2-11e9-9ada-f0fbe31c5d05.png)
由于nginx用的是alpine的容器，所以
如要进入alpine容器，命令是（后面的路径不是/bin/bash）：docker exec -it dnmp_nginx_1 /bin/sh

望作者指明一下

**Comment by isecret** [comment]
我一般是这么写的：`docker-compose exec nginx bash`，会自动补全一些信息。PHP 多个版本的话需要指定版本：`docker-compose exec php72 bash`。

**Comment by skylei** [comment]
@xuanyue0522 
docker exec -it dnmp_nginx_1 sh
这个取决于容器中的shell版本，如果/usr/bin/bash不可使用请使用sh
