### ISSUE TITLE
libcurl4-openssl-dev_7.52.1-5+deb9u7_amd64.deb无法找到了,应该怎么解决

### ISSUE THREAD

**Issue by jingmian** [yeszao/dnmp#132]
Need to get 374 kB of archives.
After this operation, 1376 kB of additional disk space will be used.
**Err:1 http://mirrors.aliyun.com/debian-security stretch/updates/main amd64 libcurl4-openssl-dev amd64 7.52.1-5+deb9u7
  404  Not Found [IP: 183.60.159.231 80]**
E: Failed to fetch http://mirrors.aliyun.com/debian-security/pool/updates/main/c/curl/libcurl4-openssl-dev_7.52.1-5+deb9u7_amd64.deb  404  Not Found [IP: 183.60.159.231 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
ERROR: Service 'php72' failed to build: The command '/bin/sh -c apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && :    && apt-get install -y libicu-dev     && docker-php-ext-install intl     && :    && apt-get install -y libxml2-dev     && apt-get install -y libxslt-dev     && docker-php-ext-install soap     && docker-php-ext-install xsl     && docker-php-ext-install xmlrpc     && docker-php-ext-install wddx     && :    && apt-get install -y libbz2-dev     && docker-php-ext-install bz2     && :    && docker-php-ext-install zip     && docker-php-ext-install pcntl     && docker-php-ext-install pdo_mysql     && docker-php-ext-install mysqli     && docker-php-ext-install mbstring     && docker-php-ext-install exif     && docker-php-ext-install bcmath     && docker-php-ext-install calendar     && docker-php-ext-install sockets     && docker-php-ext-install gettext     && docker-php-ext-install shmop     && docker-php-ext-install sysvmsg     && docker-php-ext-install sysvsem     && docker-php-ext-install sysvshm     && docker-php-ext-install opcache      && :    && apt-get install -y curl     && apt-get install -y libcurl3     && apt-get install -y libcurl4-openssl-dev     && docker-php-ext-install curl     && :    && apt-get install -y libmemcached-dev zlib1g-dev     && pecl install memcached-2.2.0     && docker-php-ext-enable memcached' returned a non-zero code: 100

**Comment by isecret** [comment]
可能是源的问题，你尝试把阿里的源切换到中科大的试试，虽然我在中科大这边也没有找到这个包。

**Comment by jingmian** [comment]
我切换了,也没有,它是为什么出现需要deb9u7_amd64这个包的,我看到除了这个版本,其他都有的
