### ISSUE TITLE
Error response from daemon: Container b9820ff9dc45ce4f55294ed9de27c0b8c4997a3173e568bfdd56d6332e06e3b4 is not running

### ISSUE THREAD

**Issue by zhangludi** [yeszao/dnmp#137]
First of all, we have to start the docker container

ankit@ankit-HP-Notebook:~$  sudo docker start 3a19b39ea021

                        3a19b39ea021
After that, check the docker container:

ankit@ankit-HP-Notebook:~$  sudo docker ps -a

 CONTAINER ID        IMAGE                         COMMAND             CREATED             STATUS                   PORTS               NAMES

  3a19b39ea021        coreapps/ubuntu16.04:latest   "bash"              13 hours ago        
  Up 9 seconds                                 ubuntu1

  455b66057060        hello-world                   "/hello"            4 weeks ago         

Exited (0) 4 weeks ago                       vigorous_bardeen
Then execute by using the command below:

ankit@ankit-HP-Notebook:~$  sudo docker exec -it 3a19b39ea021 bash

root@3a19b39ea021:/#

**Comment by skylei** [comment]
@zhangludi 
docker-compose up 启动 -d 后端启动，
我看到ankit@ankit-HP-Notebook:~$ sudo docker start 3a19b39ea021 你启动了一个单独的镜像，请详情看看官方的说明；
