### ISSUE TITLE
ERROR: Service 'php72' failed to build: The command '/bin/sh -c pecl install redis-3.1.4 

### ISSUE THREAD

**Issue by ss7247** [yeszao/dnmp#14]
Notice: Undefined variable: proxy_host in PEAR/Proxy.php on line 163

Notice: Undefined variable: proxy_port in PEAR/Proxy.php on line 163
No releases available for package "pecl.php.net/redis"
install failed
ERROR: Service 'php72' failed to build: The command '/bin/sh -c pecl install redis-3.1.4     && docker-php-ext-enable redis     && :    && pecl install xdebug-2.6.0alpha1     && docker-php-ext-enable xdebug     && :    && apt-get install -y libmagickwand-dev     && pecl install imagick-3.4.3     && docker-php-ext-enable imagick     && :    && apt-get install -y libmemcached-dev zlib1g-dev     && pecl install memcached-3.0.4     && docker-php-ext-enable memcached' returned a non-zero code: 1

版本不对？

**Comment by Dshufeng** [comment]
你的代理不对吧

**Comment by yeszao** [comment]
参考这个：https://github.com/yeszao/dnmp/issues/10
