### ISSUE TITLE
php和nginx每个容器都要保存一份项目吗

### ISSUE THREAD

**Issue by WencoChen** [yeszao/dnmp#141]
如果php和nginx部署在不同主机上呢？但是前后端没完全分离的话项目中有很多需要直接请求的静态文件，有没有比较好的解决方法？

**Comment by WencoChen** [comment]
不考虑磁盘空间占用，就算代码更新加钩子自动更新server代码也不是很得劲啊

**Comment by yeszao** [comment]
那就是代码层的问题了，即使不用docker也存在一样的问题
