### ISSUE TITLE
安装 xhprof 报错

### ISSUE THREAD

**Issue by Felo-Z** [yeszao/dnmp#143]
从[ 官网](https://pecl.php.net/package/xhprof)下载的扩展，并复制到扩展目录，在php72.sh 中添加安装命令，`if [ -z "${EXTENSIONS##*,xhprof,*}" ]; then
    echo "---------- Install xhprof ----------"
    mkdir xhprof \
    && tar -xf xhprof-0.9.4.tgz -C xhprof --strip-components=1 \
    && ( cd xhprof && phpize && ./configure && make ${MC} && make install ) \
    && docker-php-ext-enable xhprof
fi`，执行按照报错，
![x](https://user-images.githubusercontent.com/6071340/58927492-6665f680-8781-11e9-97aa-890409a1c3a4.png)

**Comment by yeszao** [comment]
什么错？

**Comment by Felo-Z** [comment]
> 什么错？

如上面截图
`Cannot find config.m4
Make sure that you run '/usr/local/bn/phpize' in the top level source directory of the module
`，同样方法安装其他的扩展没有出现这个问题

**Comment by yeszao** [comment]
检查一下添加的脚本，或者换用pecl方式安装

**Comment by Felo-Z** [comment]
> 检查一下添加的脚本，或者换用pecl方式安装

好的
