### ISSUE TITLE
php7.0.33编译pgsql组件失败

### ISSUE THREAD

**Issue by lsk8867485** [yeszao/dnmp#144]
php7.0.33编译pgsql组件失败
![image](https://user-images.githubusercontent.com/15027222/59109559-d639d400-896f-11e9-9293-5ae7551b5e10.png)
需要安装postgresql-dev组件才行。

**Comment by lsk8867485** [comment]
`FROM php:fpm-alpine

RUN set -ex \
  && apk --no-cache add \
    postgresql-dev

RUN docker-php-ext-install pdo pdo_pgsql
`

**Comment by lsk8867485** [comment]
修改extensions下的install.sh文件
最后加入`postgresql-dev`即可
```
if [ "${PHP_EXTENSIONS}" != "" ]; then
    echo "---------- Install general dependencies ----------"
    apk add --no-cache autoconf g++ libtool make curl-dev libxml2-dev linux-headers postgresql-dev
fi

```

**Comment by yeszao** [comment]
@lsk8867485 👍，主干已修复
