### ISSUE TITLE
后续是否能增加rabbitmq和elasticsearch

### ISSUE THREAD

**Issue by jingmian** [yeszao/dnmp#149]
你好,请问后续是否能增加rabbitmq和elasticsearch?

**Comment by yeszao** [comment]
嗯，后续看情况吧，其实这些也可以自己加。

**Comment by jingmian** [comment]
因为自已加进去,以后你升级了,我这边又不会怎么搞兼容了,所以还是等楼主了,哈哈

**Comment by yeszao** [comment]
你加吗，然后提个PR，我合并进来不就兼容了，是不，嘿嘿

**Comment by jingmian** [comment]
已添加上,顺便刷个留言版,哈
