### ISSUE TITLE
启动失败

### ISSUE THREAD

**Issue by zhanghaiyang1** [yeszao/dnmp#150]
1，项目特点说支持MacOs，但第三步操作
如果不是root用户，还需将当前用户加入docker用户组：
$ sudo gpasswd -a ${USER} docker，只写了Linux命令，没有说明
2，启动但时候会有这个问题
Pulling redis (redis:5.0.3-alpine)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Comment by yeszao** [comment]
只是网络超时而已，重试
