### ISSUE TITLE
安装了bcmath扩展使用composer提示缺少扩展

### ISSUE THREAD

**Issue by Orocker** [yeszao/dnmp#152]
1:php72环境下面，已经安装了bcmath扩展 （php -m 能看到bcmath）提示缺少bcmath
2:php版本怎么是php7.3.6? 我进入容器 php -v 显示的是7.2.19

**Your requirements could not be resolved to an installable set of packages.**

  Problem 1
    - The requested PHP extension ext-bcmath * is missing from your system. Install or enable PHP's bcmath extension.
  Problem 2
    - friendsofphp/php-cs-fixer v2.2.20 requires php ^5.3.6 || >=7.0 <7.3 -> your PHP version (7.3.6) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.2.20 requires php ^5.3.6 || >=7.0 <7.3 -> your PHP version (7.3.6) does not satisfy that requirement.
    - Installation request for friendsofphp/php-cs-fixer v2.2.20 -> satisfiable by friendsofphp/php-cs-fixer[v2.2.20].

**Comment by yeszao** [comment]
版本要在.env文件中配置，请问你是如何配的？

**Comment by Orocker** [comment]
> 版本要在.env文件中配置，请问你是如何配的？
就是默认的.env文件
```
#################### PHP7.2 ####################
PHP72_VERSION=7.2.19
PHP72_PHP_CONF_FILE=./conf/php.ini
PHP72_FPM_CONF_FILE=./conf/php-fpm.conf
PHP72_LOG_DIR=./log/php
PHP72_EXTENSIONS=pdo_mysql,opcache,redis,bcmath


#################### PHP5.6 ####################
PHP56_VERSION=5.6.40
PHP56_PHP_CONF_FILE=./conf/php.ini
PHP56_FPM_CONF_FILE=./conf/php-fpm.conf
PHP56_LOG_DIR=./log/php
PHP56_EXTENSIONS=opcache,redis


#################### MySQL #####################
MYSQL_VERSION=8.0.13
MYSQL_HOST_PORT=3306
MYSQL_ROOT_PASSWORD=123456
MYSQL_DATA_DIR=./mysql
MYSQL_CONF_FILE=./conf/mysql.cnf


#################### Redis #####################
REDIS_VERSION=5.0.3-alpine
REDIS_HOST_PORT=6379
REDIS_CONF_FILE=./conf/redis.conf


################## phpMyAdmin ##################
PHPMYADMIN_HOST_PORT=8080


################# redisMyAdmin #################
REDISMYADMIN_HOST_PORT=8081
```

**Comment by yeszao** [comment]
你用 composer 装什么？

**Comment by Orocker** [comment]
@yeszao 从上面的报错，是装["friendsofphp/php-cs-fixer": "v2.2.20",](https://packagist.org/packages/friendsofphp/php-cs-fixer) ， 跑的是一个Laravel 5.3的项目

**Comment by Orocker** [comment]
还有关于 Problem 1的问题，我装了php56 ,php72 进入2个容器都能运行 `php -m` 都能看到bcmath，还是会报第一个错误。

**Comment by yeszao** [comment]
好，晚点我试试

**Comment by Orocker** [comment]
@yeszao docker-compose.yml就是最新的

**Comment by yeszao** [comment]
我自己试了下，composer require friendsofphp 没有问题呢？你还改了什么吗？

**Comment by Orocker** [comment]
@yeszao docker运行的容器名改了下
