### ISSUE TITLE
Notice: Undefined variable: proxy_host in PEAR/Proxy.php on line 163

### ISSUE THREAD

**Issue by panw3i** [yeszao/dnmp#16]
Notice: Undefined variable: proxy_port in PEAR/Proxy.php on line 163
No releases available for package "pecl.php.net/redis"
install failed
ERROR: Service 'php72' failed to build: The command '/bin/sh -c pecl install redis-3.1.4     && docker-php-ext-enable redis     && :    && pecl install xdebug-2.6.0alpha1     && docker-php-ext-enable xdebug     && :    && apt-get install -y libmagickwand-dev     && pecl install imagick-3.4.3     && docker-php-ext-enable imagick     && :    && apt-get install -y libmemcached-dev zlib1g-dev     && pecl install memcached-3.0.4     && docker-php-ext-enable memcached' returned a non-zero code: 1

**Comment by yeszao** [comment]
得有可用的代理才行的哦，参考：https://github.com/yeszao/dnmp/issues/10
