### ISSUE TITLE
有没有可靠的源可以用呢，换了163报这种错，还是用不了

### ISSUE THREAD

**Issue by sincez** [yeszao/dnmp#163]
换了163源，现在报这种错，怎么解决呢
W: The repository 'http://mirrors.163.com/debian jessie-backports Release' does not have a Release file.
E: Failed to fetch http://mirrors.163.com/debian/dists/jessie-backports/contrib/source/Sources 404 Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y libfreetype6 libjpeg62-turbo-dev libpng-dev && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && docker-php-ext-install gd && : && apt-get install -y libicu-dev && docker-php-ext-install intl && : && apt-get install -y libxml2-dev libxslt-dev && docker-php-ext-install soap && docker-php-ext-install xmlrpc && docker-php-ext-install xsl && : && apt-get install -y libpq-dev && docker-php-ext-install pdo && docker-php-ext-install pdo_mysql && docker-php-ext-install mysqli && docker-php-ext-install pdo_pgsql && docker-php-ext-install pgsql && : && docker-php-ext-install bcmath && docker-php-ext-install gettext && docker-php-ext-install opcache && docker-php-ext-install pcntl && docker-php-ext-install sockets && docker-php-ext-install zip && docker-php-ext-install redis' returned a non-zero code: 100

**Comment by yeszao** [comment]
那就换阿里云或中科大的把

**Comment by day112** [comment]
使用163 报错：ERROR: Get https://registry-1.docker.io/v2/: net/http: TLS handshake timeout  使用中科大的源 `https://docker.mirrors.ustc.edu.cn`  飞速通过
