### ISSUE TITLE
容器无法连接局域网

### ISSUE THREAD

**Issue by fengyunye** [yeszao/dnmp#164]
在php容器内，我可以Ping通外网，也可以ping通部分局域网，我已设置默认网络为172.20.10.1，宿主机本身ip为172.17.13.27,无法ping通的局域网为172.17.12.47.可以从哪些方面考虑原因呢

**Comment by yeszao** [comment]
是否本身就无法连通？

**Comment by fengyunye** [comment]
> 是否本身就无法连通？
本身可以连通，我之前的笔记本是可以正常使用的，因为性能原因，换了个台式机，然后就不行了。
