### ISSUE TITLE
pdo_odbc扩展无效

### ISSUE THREAD

**Issue by heaven890922** [yeszao/dnmp#166]
![image](https://user-images.githubusercontent.com/16571758/61343940-17cc7180-a882-11e9-890c-5e465e425793.png)
![image](https://user-images.githubusercontent.com/16571758/61343962-274bba80-a882-11e9-9342-2d63edaae01c.png)
![image](https://user-images.githubusercontent.com/16571758/61343975-2f0b5f00-a882-11e9-858f-af91784e32ea.png)
我使用tp5.1，需要链接sqlserver数据库，一直报错

**Comment by yeszao** [comment]
php -m 是否提示已经安装扩展？
