### ISSUE TITLE
mac 下直接安装报错

### ISSUE THREAD

**Issue by oorzc** [yeszao/dnmp#168]
ERROR: for mongodb  Cannot start service mongodb: OCI runtime create failed: container_linux.go:344: starting container process caused "process_linux.go:424: container init caused \"rootfs_linux.go:58: mounting \\\"/Users/apple/www/dnmp/etc/timezone\\\" to rootfs \\\"/var/lib/docker/overlay2/c3a37b8fdebc1a3bb10f2f3212ad3b69274a91747870e5d6cf037496ca889a66/merged\\\" at \\\"/var/lib/docker/overlay2/c3a37b8fdebc1a3bb10f2f3212ad3b69274a91747870e5d6cf037496ca889a66/merged/etc/timezone\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by jingmian** [comment]
拉取最新版,使用最新的env文件,看看还有问题没

**Comment by oorzc** [comment]
> 拉取最新版,使用最新的env文件,看看还有问题没

还是有点问题  已存在这个目录了  你试下呢

ERROR: for mongodb  Cannot start service mongodb: error while creating mount source path '/Users/apple/www/dnmp/conf/localtime': mkdir /Users/apple/www/dnmp/conf/localtime: file exists

**Comment by jingmian** [comment]
你单独把mongodb的容器和镜像都删除,单独启动这个,然后粘贴错误来

**Comment by oorzc** [comment]
> 你单独把mongodb的容器和镜像都删除,单独启动这个,然后粘贴错误来

我完全删除  重新装了   找到原因了   [``](url)

**Comment by jingmian** [comment]
但是在window和linux引用我上传的文件都是可以用的,但不知道为何mac要删除重建才可以
