### ISSUE TITLE
The mcrypt PHP extension is not installed

### ISSUE THREAD

**Issue by zxslboot** [yeszao/dnmp#17]
dockerFile中  已安装mcrypt  为什么phpinfo中没有该扩展

**Comment by yeszao** [comment]
请问php安装的是什么版本呢？
PHP7已经不支持mcrypt咯，建议用openssl_*类方法替代

**Comment by zxslboot** [comment]
谢谢你的回复
php5.6  我用的yii2框架  框架内用了这个  如果实在用不了  我绕开它  或者装低版本
