### ISSUE TITLE
memcached 的问题

### ISSUE THREAD

**Issue by rockts** [yeszao/dnmp#176]
php memcached 安装好了。
但我进容器了
ps aux | grep memcached
没看到运行，我的wp 显示没有正常
怎么可以自动运行呢？

**Comment by jingmian** [comment]
你只是安装客户端扩展,memcached服务器也要安装的,你拉取一个docker pull memcached:apline

**Comment by rockts** [comment]
> 你只是安装客户端扩展,memcached服务器也要安装的,你拉取一个docker pull memcached:apline

怎么连接呢，我的 wp 需要 memcached ,  这个pull  memcached 怎么和 DNMP 联系起来呢？

**Comment by jingmian** [comment]
在docker-compose.yml里面增加以下代码
https://github.com/yeszao/dnmp/blob/master/docker-compose-full.yml#L104-L111

代码里面需要用memcached连接的127.0.0.1改为"memcached"即可

**Comment by rockts** [comment]
> 在docker-compose.yml里面增加以下代码
> https://github.com/yeszao/dnmp/blob/master/docker-compose-full.yml#L104-L111
> 
> 并拉取最新env配置文件
> 代码里面需要用memcached连接的127.0.0.1改为"memcached"即可

${MEMCACHED_HOST_PORT} 和 ${MEMCACHED_VERSION} 都需要在.env 里配置吧？

**Comment by jingmian** [comment]
是的

**Comment by rockts** [comment]
> 是的

我试试太感谢您了
