### ISSUE TITLE
zip扩展安装失败，提示没有zlib

### ISSUE THREAD

**Issue by wanwenjie** [yeszao/dnmp#177]
问题已解决，https://github.com/docker-library/php/issues/797，建议在install.sh中增加
`apk  add --no-cache libzip-dev && docker-php-ext-configure zip --with-libzip=/usr/include && docker-php-ext-install zip`

**Comment by jingmian** [comment]
你是不是使用php7.3的版本

**Comment by wanwenjie** [comment]
> 你是不是使用php7.3的版本

5.6

**Comment by jingmian** [comment]
我测试了下,直接在env添加zip就可以安装了哦,install.sh里面已经包含zip扩展的

**Comment by niezuxue** [comment]
php 7.4加了zip也是没安装

**Comment by niezuxue** [comment]
> php 7.4加了zip也是没安装

我是第一次启动所有容器时，env中没有加zip扩展，后面不管是执行 docker-composer build php 还是 docker-composer build --no-cache php 都没效果。 
**最后我是删了php.  docker-composer rm php之后再重新build就可以了**
