### ISSUE TITLE
vagrant 启动虚拟机 在/vagrant 目录做映射 MongoDB 文件被占用

### ISSUE THREAD

**Issue by samnew** [yeszao/dnmp#193]
![QQ截图20191009112438](https://user-images.githubusercontent.com/242279/66449516-f2699100-ea87-11e9-96db-1958f1b29ccc.png)

**Comment by yeszao** [comment]
虚拟机目录的共享目录做映射，是会有问题的。

**Comment by samnew** [comment]
> 虚拟机目录的共享目录做映射，是会有问题的。

嗯是的 我现在把 MongoDB 独立出来映射了其他的如Redis MySQL 没问题
