### ISSUE TITLE
2.x版本mysql5.x连接报错SQLSTATE[HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by mufengorg** [yeszao/dnmp#198]
php连接mysql报错：`SQLSTATE[HY000] [2002] Connection refused`，mysql8.x没有问题
连接信息如下：
```
DB_CONNECTION=mysql
DB_HOST=mysql5
DB_PORT=3305
DB_DATABASE=test
DB_USERNAME=root
DB_PASSWORD=123456
```

**Comment by yeszao** [comment]
是否已解决？

**Comment by davidvivi** [comment]
我也是这个错误，请问怎么解决
<?php
return array(

//*************************************数据库设置*************************************
    'DB_TYPE'               =>  'mysql',                 // 数据库类型
    'DB_HOST'               =>  '127.0.0.1',     // 服务器地址
    'DB_NAME'               =>  'ww',     // 数据库名
    'DB_USER'               =>  'root',     // 用户名
    'DB_PWD'                =>  '123456',      // 密码
    'DB_PORT'               =>  '3306',     // 端口
    'DB_PREFIX'             =>  'ww_',   // 数据库表前缀
);

**Comment by mufengorg** [comment]
问题依然存在

**Comment by jingmian** [comment]
@davidvivi 不能填写`127.0.0.1`,填`mysql`

**Comment by mufengorg** [comment]
怎么关闭issue了？如果已经解决，请提示一下
