### ISSUE TITLE
mysql连接失败

### ISSUE THREAD

**Issue by z32556601** [yeszao/dnmp#2]
mysql -h 127.0.0.1 -u root -p
照你的教程，mysql连接不上。
ERROR 1130 (HY000): Host '192.168.0.1' is not allowed to connect to this MySQL server
报这个错

**Comment by yeszao** [comment]
有几点需要注意一下：
1）如果原本docker-compose.yml里面指定了：
`MYSQL_ROOT_PASSWORD: "123456"`
然后又修改了这个值，那么再次`docker-compose up`，容器里面的MySQL密码是不会改变，还是`123456`，除非重新build MySQL容器。
2）如果不是上面的问题，那可以进入容器：
`docker exec -it dlnmp_mysql_1 /bin/bash`
在容器里面用这个命令是否可以登陆MySQL：
`mysql -u root -p`
如果容器里面可以，其他容器不可以，再授权外部访问：
`GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123456' WITH GRANT OPTION;`
一般来说，这样就能排除问题了。

**Comment by M69W** [comment]
可能是数据库 IP 不对，
用Navicat 可以用localhost连接  
但thinkCMF(thinkphp)报错：
SQLSTATE[HY000] [2002] No such file or directory  
或 数据库账号或密码不正确！SQLSTATE[HY000] [2002] Connection refused
在报错的页面下面看到  

SERVER_ADDR | 172.18.0.4  
REMOTE_PORT | 33806  
REMOTE_ADDR | 172.18.0.1  

然后用172.18.0.1作为数据库服务器地址即可，而不是127.0.0.1或localhost

装过5次才发现这个问题！

**Comment by yangjingchuang** [comment]
> 有几点需要注意一下：
> 1）如果原本docker-compose.yml里面指定了：
> `MYSQL_ROOT_PASSWORD: "123456"`
> 然后又修改了这个值，那么再次`docker-compose up`，容器里面的MySQL密码是不会改变，还是`123456`，除非重新build MySQL容器。
> 2）如果不是上面的问题，那可以进入容器：
> `docker exec -it dlnmp_mysql_1 /bin/bash`
> 在容器里面用这个命令是否可以登陆MySQL：
> `mysql -u root -p`
> 如果容器里面可以，其他容器不可以，再授权外部访问：
> `GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '123456' WITH GRANT OPTION;`
> 一般来说，这样就能排除问题了。

大佬，这个是啥问题？？
![image](https://user-images.githubusercontent.com/29910922/109409420-83b70b80-79cd-11eb-8d99-0ae35b5de164.png)
