### ISSUE TITLE
换了好几种源还是不行

### ISSUE THREAD

**Issue by zhqpower** [yeszao/dnmp#20]
Running in f805390bdfd2
Get:1 http://mirrors.ustc.edu.cn/raspbian/raspbian stretch InRelease [2165 B]
Err:1 http://mirrors.ustc.edu.cn/raspbian/raspbian stretch InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Fetched 2165 B in 0s (43.0 kB/s)
Reading package lists...
E: Failed to fetch http://mirrors.ustc.edu.cn/raspbian/raspbian/dists/stretch/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: Some index files failed to download. They have been ignored, or old ones used instead.
ERROR: Service 'php72' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && :    && apt-get install -y libicu-dev     && docker-php-ext-install intl     && :    && apt-get install -y libxml2-dev     && apt-get install -y libxslt-dev     && docker-php-ext-install soap     && docker-php-ext-install xsl     && docker-php-ext-install xmlrpc     && docker-php-ext-install wddx     && :    && apt-get install -y libbz2-dev     && docker-php-ext-install bz2     && :    && docker-php-ext-install zip     && docker-php-ext-install pcntl     && docker-php-ext-install pdo_mysql     && docker-php-ext-install mysqli     && docker-php-ext-install mbstring     && docker-php-ext-install exif     && docker-php-ext-install bcmath     && docker-php-ext-install calendar     && docker-php-ext-install sockets     && docker-php-ext-install gettext     && docker-php-ext-install shmop     && docker-php-ext-install sysvmsg     && docker-php-ext-install sysvsem     && docker-php-ext-install sysvshm     && docker-php-ext-install opcache' returned a non-zero code: 100

**Comment by yeszao** [comment]
有啥提示？
