### ISSUE TITLE
Class 'ZipArchive' not found

### ISSUE THREAD

**Issue by xuanyue0522** [yeszao/dnmp#204]
请问大佬如何安装zip扩展啊？.env文件中已经把zip加到扩展那了，但是不起作用  php5.6版本，报Class 'ZipArchive' not found

**Comment by yeszao** [comment]
从新pull再试试看。

**Comment by xuanyue0522** [comment]
删了容器和镜像重新构建的还是不行，最后还是执行的
`apk add --no-cache libzip-dev && docker-php-ext-configure zip --with-libzip=/usr/include && docker-php-ext-install zip`解决的
