### ISSUE TITLE
Unable to create or open slowlog(/var/log/php/fpm.slow.log): Permission denied (13)

### ISSUE THREAD

**Issue by CDcoding2333** [yeszao/dnmp#206]
php      | [03-Nov-2019 10:36:03] ERROR: Unable to create or open slowlog(/var/log/php/fpm.slow.log): Permission denied (13)
php      | [03-Nov-2019 10:36:03] ERROR: Unable to create or open slowlog(/var/log/php/fpm.slow.log): Permission denied (13)
php      | [03-Nov-2019 10:36:03] ERROR: failed to post process the configuration
php      | [03-Nov-2019 10:36:03] ERROR: failed to post process the configuration
php      | [03-Nov-2019 10:36:03] ERROR: FPM initialization failed
php      | [03-Nov-2019 10:36:03] ERROR: FPM initialization failed

**Comment by jingmian** [comment]
请问是什么系统,执行了什么命令

**Comment by CDcoding2333** [comment]
linux 系统 拉去代码后直接docker-compose up 直接在目录下新建文件 问题可以解决

**Comment by jingmian** [comment]
测试了下,因为你pull后,原来的本地logs文件没有删除,所以提示了权限不足,以后尽量删除logs文件后,再跑一下
