### ISSUE TITLE
在容器中如何切换到root用户？

### ISSUE THREAD

**Issue by daulCN** [yeszao/dnmp#210]
Dockerfile最后一步切换到别的用户了，但是我想在容器中修改一些内容（即使重启就会失效），需要root权限，那么应该如何切换到root用户呢？

**Comment by jingmian** [comment]
默认就是root用户了

**Comment by daulCN** [comment]
> 默认就是root用户了

最新版默认已经改成www-data了

**Comment by jingmian** [comment]
已经移除了,请检查

**Comment by daulCN** [comment]
> 已经移除了,请检查

ok,我更新一下
