### ISSUE TITLE
使用支付宝sdk iconv()报错

### ISSUE THREAD

**Issue by mkm0094** [yeszao/dnmp#211]
支付宝官方sdk
调用接口：分账关系查询 AlipayTradeRoyaltyRelationBatchqueryRequest
错误：iconv(): Wrong charset, conversion from `UTF-8' to `UTF-8//IGNORE' is not allowed

**Comment by jingmian** [comment]
mbstring和xml,查看是否安装这两个扩展

**Comment by yeszao** [comment]
那个php版本？

**Comment by mkm0094** [comment]
> 那个php版本？

php版本 : PHP 7.2.13
phpinfo : './configure' '--build=x86_64-linux-musl' '--with-config-file-path=/usr/local/etc/php' '--with-config-file-scan-dir=/usr/local/etc/php/conf.d' '--enable-option-checking=fatal' '--with-mhash' '--enable-ftp' '--enable-mbstring' '--enable-mysqlnd' '--with-password-argon2' '--with-sodium=shared' '--with-curl' '--with-libedit' '--with-openssl' '--with-zlib' '--enable-fpm' '--with-fpm-user=www-data' '--with-fpm-group=www-data' '--disable-cgi' 'build_alias=x86_64-linux-musl'

docker .env:  PHP72_EXTENSIONS=pdo_mysql,opcache,redis,gd,zip
