### ISSUE TITLE
怎么在php.ini 关闭swoole.use_shortname

### ISSUE THREAD

**Issue by Orocker** [yeszao/dnmp#213]
在安装目录的conf/php.ini 加入了 swoole.use_shortname=off ,重启php72容器
php --ri swoole:
在宿主机：

![host](https://user-images.githubusercontent.com/16423397/69620173-dfcb0b80-1077-11ea-87c4-ff235557da1b.png)
在容器：
![container](https://user-images.githubusercontent.com/16423397/69620564-7e576c80-1078-11ea-8903-e644b7acbebf.png)
为什么看到的结果是不一样的呢？host的php命令在按照文档在~/.bashrc 加的快捷键命令

**Comment by jingmian** [comment]
可修改 `php.ini` 设置` swoole.use_shortname=On/Off `来开启 / 关闭短名，默认为开启。
https://wiki.swoole.com/#/other/alias?id=%E5%8D%8F%E7%A8%8B%E7%9F%AD%E5%90%8D%E7%A7%B0

**Comment by Orocker** [comment]
@jingmian 我的意思是在容器内看到的结果和在host上面看到的结果不一样

**Comment by jingmian** [comment]
你宿主机上应该是装了一个php版本吧,你`which php`看看它指向哪里.而且我在新购买的云主机上测试了一下,没有这个问题呢

**Comment by Orocker** [comment]
@jingmian host上面没有安装php
`
which php
/usr/bin/which: no php in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)

`

**Comment by jingmian** [comment]
一般都是按照容器内为准的,如果没有影响正常使用,可以不用理它.我也暂时无法找出答案

**Comment by Orocker** [comment]
好的，谢谢
