### ISSUE TITLE
docker-compose up 时报错ERROR: unsatisfiable constraints:   shadow (missing)

### ISSUE THREAD

**Issue by humour-picasso** [yeszao/dnmp#217]
Step 15/16 : RUN apk --no-cache add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data
 ---> Running in 042061ff6b9f
fetch http://mirrors.aliyun.com/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  shadow (missing):
    required by: world[shadow]
ERROR: Service 'php' failed to build: The command '/bin/sh -c apk --no-cache add shadow && usermod -u 1000 www-data && groupmod -g 1000 www-data' returned a non-zero code: 1

请问我怎样才能解决这个问题

**Comment by jingmian** [comment]
删除后,拉取最新版试试
