### ISSUE TITLE
可以添加自扩展的shell文件引入吗？

### ISSUE THREAD

**Issue by popdaul** [yeszao/dnmp#218]
我所在的公司用了几个比较冷门的PHP扩展，我是自己在本地添加到此项目里了，但是每次源项目更新后我都要我都要重拉并解决冲突，很不方便。
所以可以在 
`services/php/extensions/install.sh` 
`services/php54/extensions/install.sh`
文件中添加一个引入指定文件夹文件并执行的命令吗？然后在.gitignore里忽略这个用户自定义文件。
这样方便自己扩展，也可以一直保持最新的项目。
望答复🙏🙏🙏

**Comment by daulCN** [comment]
我可以自己加然后pr吗？ @yeszao

**Comment by yeszao** [comment]
@daulCN 欢迎提交pr
