### ISSUE TITLE
php mkdir(): Permission denied

### ISSUE THREAD

**Issue by deepsea-tyy** [yeszao/dnmp#219]
代码部署dnmp后，后台上传文件一直这个问题无法解决，相应文件目录已改为777

**Comment by jingmian** [comment]
粘贴错误代码,出现mkdir,要么你把www目录都设置777

**Comment by deepsea-tyy** [comment]
![image](https://user-images.githubusercontent.com/16817929/70840056-dbaa3680-1e4a-11ea-9efc-76ebcf3bfe97.png)

@jingmian 
```
$dir = '/var/dnmp/www/localhost/file'
var_dump(is_dir($dir)); //返回false  这个是我上传文件的根目录
```

**Comment by jingmian** [comment]
是否有设置 777 -R
