### ISSUE TITLE
请问新建虚拟主机怎么操作？提示Access Denied.

### ISSUE THREAD

**Issue by yhf7952** [yeszao/dnmp#220]
刚接触docker，代码运行成功，默认网站访问正常。
在/www下添加新网站目录，并复制nginx/conf.d/localhost.conf，修改网站路径为新目录，运行PHP文件提示Access Denied. 
各种大佬看看是还有哪需要设置？

**Comment by jingmian** [comment]
访问默认的index.php可以不

**Comment by yhf7952** [comment]
> 访问默认的index.php可以不

默认的可以，自己新建的虚拟主机不行

**Comment by jingmian** [comment]
应该是你nginx配置文件问题,检查下

**Comment by yhf7952** [comment]
> 应该是你nginx配置文件问题,检查下

复制的示例配置文件，只改了路径，域名这些

**Comment by jingmian** [comment]
估计你文件夹或者文件权限不足,再排查
