### ISSUE TITLE
如何将代码和数据挂载在外面

### ISSUE THREAD

**Issue by taobali32** [yeszao/dnmp#222]
现在代码挂载在 /www目录的，  -v试过了挂载不出来， 还有数据库也需要挂载在外面，

如果可以最好像lardocker那样， 我只需要  ../wwwroot 即可 挂载在外面物理主机了

**Comment by jingmian** [comment]
粘贴你运行的命令

**Comment by taobali32** [comment]
> 粘贴你运行的命令

sorry..   我需要在试试，因为我的docker使用水平太烂提问了不该问的问题
