### ISSUE TITLE
如何配置新站点啊

### ISSUE THREAD

**Issue by vincent66666** [yeszao/dnmp#225]
如何配置新站点啊

**Comment by jingmian** [comment]
跟你配置nginx新站点一样配置的,复制多一个.conf文件

**Comment by vincent66666** [comment]
我复制出来一个conf配置好重启nginx，Mac本地没有访问到，Mac本地需要配置什么吗？

**Comment by vincent66666** [comment]
> 跟你配置nginx新站点一样配置的，复制多一个.conf文件

我复制出来一个conf配置好重启nginx，Mac本地没有访问到，是Mac本地还需要配置什么吗？

**Comment by jingmian** [comment]
粘贴自已conf配置看看

**Comment by vincent66666** [comment]
server {
    listen       80  ;
    server_name  dnmp.site1.com;
    root   /www/localhost;
    index  index.php index.html index.htm;
    #charset koi8-r;

    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.localhost.access.log  main;
    error_log  /var/log/nginx/nginx.localhost.error.log  warn;

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
        fastcgi_pass   php:9000;
        include        fastcgi-php.conf;
        include        fastcgi_params;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

**Comment by vincent66666** [comment]
> 粘贴自已conf配置看看

server {
    listen       80  ;
    server_name  dnmp.site1.com;
    root   /www/localhost;
    index  index.php index.html index.htm;
    #charset koi8-r;
    access_log /dev/null;
    #access_log  /var/log/nginx/nginx.localhost.access.log  main;
    error_log  /var/log/nginx/nginx.localhost.error.log  warn;

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    location ~ \.php$ {
        fastcgi_pass   php:9000;
        include        fastcgi-php.conf;
        include        fastcgi_params;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}

**Comment by jingmian** [comment]
很明显`root /www/localhost;`你都没有改过来

**Comment by vincent66666** [comment]
> 很明显`root /www/localhost;`你都没有改过来

刚开始不是这个路径的但是一直请求不到，我想着访问下默认的 /www/localhost/index.php  结果也访问不到。。。
![image](https://user-images.githubusercontent.com/26354633/71405210-b948c200-266f-11ea-870a-aa4e32f7f318.png)
但是默认的拉高nginx配置缺能访问到

**Comment by jingmian** [comment]
你hosts文件修改没

**Comment by vincent66666** [comment]
> 你hosts文件修改没
修改了
127.0.0.1 dnmp.site1.com
![image](https://user-images.githubusercontent.com/26354633/71405651-0aa58100-2671-11ea-988e-75fbd94c7fc5.png)

**Comment by jingmian** [comment]
那你访问浏览器域名,提示什么

**Comment by vincent66666** [comment]
> 那你访问浏览器域名,提示什么

没有得到提示
![image](https://user-images.githubusercontent.com/26354633/71406373-ef3b7580-2672-11ea-8681-8b2217bbc867.png)

![image](https://user-images.githubusercontent.com/26354633/71406347-d9c64b80-2672-11ea-9fb6-b35f93884410.png)
![image](https://user-images.githubusercontent.com/26354633/71406359-e34fb380-2672-11ea-8a43-d379bfaf21ea.png)

**Comment by jingmian** [comment]
1.查看你的index.php或者index.html是否存在内容
2.查看你的nginx配置conf中,root是否指定相应的目录

**Comment by vincent66666** [comment]
> 1.查看你的index.php或者index.html是否存在内容
> 2.查看你的nginx配置conf中,root是否指定相应的目录

目前就是默认的拿 localhost.conf 过来改了下server_name 删除掉了https的哪个server， http://localhost/能访问到
![image](https://user-images.githubusercontent.com/26354633/71406802-2eb69180-2674-11ea-8e2b-5e61f60674a7.png)

**Comment by jingmian** [comment]
那就在localhost文件夹里面添加一个test.html,里面随便点内容,
然后访问dnmp.site1.com/test.html,看下

**Comment by vincent66666** [comment]
> 那就在localhost文件夹里面添加一个test.html,里面随便点内容,
> 然后访问dnmp.site1.com/test.html,看下
好像是Mac本地的nginx 返回的错误，我是得做下配置吗？
![image](https://user-images.githubusercontent.com/26354633/71407144-332f7a00-2675-11ea-93ef-84fe397f7b67.png)

**Comment by jingmian** [comment]
文件夹设置权限对没,
你把目录里面都截图下

**Comment by vincent66666** [comment]
> 文件夹设置权限对没,
> 你把目录里面都截图下

![image](https://user-images.githubusercontent.com/26354633/71407607-7807e080-2676-11ea-9fe1-27253addb1c1.png)

**Comment by jingmian** [comment]
启动docker时,尽量不要直接用root用户操作.
你现在把www目录都设置 777 -R  看下

**Comment by vincent66666** [comment]
> 777 -R
改成777了，没效果，哪个默认的站点就可以访问，新开的站点直接就404了nginx的版本还行我Mac本地的版本
![image](https://user-images.githubusercontent.com/26354633/71429638-9b786d00-2702-11ea-8a07-89438589e554.png)

**Comment by jingmian** [comment]
conf文件夹下面,你有多少个conf文件,里面的权限又是什么

**Comment by vincent66666** [comment]
> conf文件夹下面,你有多少个conf文件,里面的权限又是什么
就两个conf
![image](https://user-images.githubusercontent.com/26354633/71429929-0f674500-2704-11ea-8e76-3edf5f5a536a.png)

**Comment by jingmian** [comment]
这里的权限不对,都设置777,要是还是无反应,就整个dnmp目录设置777看下

**Comment by vincent66666** [comment]
> 这里的权限不对,都设置777,要是还是无反应,就整个dnmp目录设置777看下

还是没什么用，会不会是Mac系统本身的问题啊，我试了laradock也是这个样子

**Comment by jingmian** [comment]
你ping下自已搭建的域名,是否指向127.0.0.1

**Comment by vincent66666** [comment]
> 你ping下自已搭建的域名,是否指向127.0.0.1

指向的是127.0.0.1

**Comment by jingmian** [comment]
你把con.f里面的日志都开启,然后查看下日志,提示什么
`
access_log /var/log/nginx/nginx.dnmp.access.log main;
error_log /var/log/nginx/nginx.dnmp.error.log warn;
`
