### ISSUE TITLE
如何同时运行多个PHP版本（7.X、5.6、5.4）

### ISSUE THREAD

**Issue by huangyanrui** [yeszao/dnmp#228]
初学者提问，在Mac上  怎么同时运行多个PHP版本（7.X、5.6、5.4）

**Comment by huangyanrui** [comment]
7aa5f5982148        dnmp_php56           "docker-php-entrypoi…"   47 minutes ago      Up 13 minutes       9000/tcp, 9502/tcp                         php56
6ea9ec3911aa        dnmp_php             "docker-php-entrypoi…"   3 days ago          Up 13 minutes       9000/tcp, 9501/tcp                         php

两个版本的容器都已经运行了
dnmp/services/nginx/conf.d  下新建了两个conf 
-rw-r--r--  1 huangyr  staff  2256 12 31 11:47 56.default.conf
-rw-r--r--  1 huangyr  staff  2254 12 27 23:39 localhost.conf

 fastcgi_pass   改配置也做了相应修改

报错信息如下：
nginx        | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/localhost.conf:2
nginx exited with code 1
nginx        | nginx: [emerg] a duplicate default server for 0.0.0.0:80 in /etc/nginx/conf.d/localhost.conf:2

**Comment by jingmian** [comment]
已经提示了,在第二行编写错误,
`
etc/nginx/conf.d/localhost.conf:2
`

**Comment by huangyanrui** [comment]
我这可以跑起来了，删了  56.default.conf 文件中 443 端口的配置就可以了，还不知道根本原因是什么。。。

**Comment by huangyanrui** [comment]
> 已经提示了,在第二行编写错误,
> `etc/nginx/conf.d/localhost.conf:2`

我这可以跑起来了，删了 56.default.conf 文件中 443 端口的配置就可以了，还不知道根本原因是什么。。。

**Comment by yeszao** [comment]
nginx 用哪个版本就写哪个service名称，比如：
```nginx
php:9000        # 或者
php56:9000   # 或者
php54:9000 
```
端口都用9000。
