### ISSUE TITLE
SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by taobali32** [yeszao/dnmp#229]
环境： 
mac + 最新docker默认文件安装

操作：
默认mysql8.0变动为5.7 ok
nginx添加测试域名  ok

下载php框架  项目跑起来  ok
composer laravel 

mysql出错
更改配置文件
`DB_CONNECTION=mysql
DB_HOST=localhost  ##试过127.0.0.1
DB_PORT=3305
DB_DATABASE=tests
DB_USERNAME=root
DB_PASSWORD=123456`

权限都 777 -R过

始终报错：
Illuminate \ Database \ QueryException (2002)
SQLSTATE[HY000] [2002] No such file or directory (SQL: insert into `tests` (`nickname`, `updated_at`, `created_at`) values (1, 2020-01-02 09:22:14, 2020-01-02 09:22:14))

[网上还可以的答案链接](https://segmentfault.com/q/1010000007356940/a-1020000007367966)

以上答案试过， 个人docker太菜。解决不了，，，期待大佬帮忙。

**Comment by u5de6** [comment]
这个问题有其他好的解决办法吗

**Comment by u5de6** [comment]
> 这个问题有其他好的解决办法吗

大概知道是啥问题了  貌似是因为docker容器的网段造成的   docker-compose启动运行时会有一个默认的网段  docker运行时默认也有一个  两个不在同一网段

`docker network ls`

设置下docker-compose的network就行（自己了解下比较好，我就不贴具体操作了）
实在不行就进容器操作吧（PS：我是因为要操作migrate）
