### ISSUE TITLE
如何安装 .env里面注释里没有的PHP扩展？

### ISSUE THREAD

**Issue by crazyYG** [yeszao/dnmp#235]
如何安装 .env里面注释里没有的PHP扩展？比如安装swoole_loader

**Comment by yeszao** [comment]
在install.sh里面加吧，加了之后再提交个pr，这样其他人也可以用了。

**Comment by crazyYG** [comment]
> 在install.sh里面加吧，加了之后再提交个pr，这样其他人也可以用了。

我的这个扩展  是只有编译后的.so文件    我看到install.sh里面的都是先编译完 然后产生的.so文件  只有.so文件的这种怎么办？

**Comment by bossikill** [comment]
照着install.sh里面抄就行了..
改一下.env 
然后重新build一下
php -m看一下就有了

**Comment by bossikill** [comment]
举个栗子
比如我要安装PHP的rdkafka扩展
先修改.enu,在PHP_EXTENSIONS后加上rdkafka
然后修改install.sh,加上下面的代码,用来安装librdkafka-dev依赖和rdkafka扩展
`if [[ -z "${EXTENSIONS##*,rdkafka,*}" ]]; then
    echo "---------- Install rdkafka ----------"
	apk add --no-cache librdkafka-dev
    printf "\n" | pecl install rdkafka
    docker-php-ext-enable rdkafka
fi`
运行docker-compose build php
重启docker
php -m 看一下就有了

**Comment by crazyYG** [comment]
首先十分感谢您的回复。
看了您的举例，这个过程我明白。
我要安装的是一个PHP代码加密的扩展  您可以帮看下这个是Swoole Loader扩展安装的介绍与以往的扩展不太一样https://qq52o.me/2540.html   这里面介绍的这个过程怎么在docker里实现呢？
十分感谢！

**Comment by crazyYG** [comment]
> d
首先十分感谢您的回复。看了您的模仿
，这个过程我明白。
我要安装的是一个PHP代码加密的扩展您可以帮看下这个是Swoole Loader扩展安装的介绍与以前的扩展不太一样https ：//qq52o.me/2540.html 这里面介绍的这个过程怎么在docker里实现呢？非常
感谢！

**Comment by crazyYG** [comment]
> 举个栗子
> 比如我要安装PHP的rdkafka扩展
> 先修改.enu,在PHP_EXTENSIONS后加上rdkafka
> 然后修改install.sh,加上下面的代码,用来安装librdkafka-dev依赖和rdkafka扩展
> if [[ -z "${EXTENSIONS##_,rdkafka,_}" ]]; then
> echo "---------- Install rdkafka ----------"
> apk add --no-cache librdkafka-dev
> printf "\n" | pecl install rdkafka
> docker-php-ext-enable rdkafka
> fi
> 运行docker-compose build php
> 重启docker
> php -m 看一下就有了

首先十分感谢您的回复。看了您的模仿
，这个过程我明白。
我要安装的是一个PHP代码加密的扩展您可以帮看下这个是Swoole Loader扩展安装的介绍与以前的扩展不太一样https ：//qq52o.me/2540.html 这里面介绍的这个过程怎么在docker里实现呢？非常
感谢！

**Comment by bossikill** [comment]
> > 举个栗子
> > 比如我要安装PHP的rdkafka扩展
> > 先修改.enu,在PHP_EXTENSIONS后加上rdkafka
> > 然后修改install.sh,加上下面的代码,用来安装librdkafka-dev依赖和rdkafka扩展
> > if [[ -z "${EXTENSIONS##_,rdkafka,_}" ]]; then
> > echo "---------- Install rdkafka ----------"
> > apk add --no-cache librdkafka-dev
> > printf "\n" | pecl install rdkafka
> > docker-php-ext-enable rdkafka
> > fi
> > 运行docker-compose build php
> > 重启docker
> > php -m 看一下就有了
> 
> 首先十分感谢您的回复。看了您的模仿
> ，这个过程我明白。
> 我要安装的是一个PHP代码加密的扩展您可以帮看下这个是Swoole Loader扩展安装的介绍与以前的扩展不太一样https://qq52o.me/2540.html 这里面介绍的这个过程怎么在docker里实现呢？非常
> 感谢！

我也不会呀多试试
