### ISSUE TITLE
docker-compose up 出错he command '/bin/sh -c chmod +x install.sh     && sh install.sh     && rm -rf /tmp/extensions'

### ISSUE THREAD

**Issue by Ystars** [yeszao/dnmp#237]
![image](https://user-images.githubusercontent.com/4011903/72677234-287dce80-3ad5-11ea-929c-4f54e21754c5.png)

**Comment by yeszao** [comment]
这是PHP7.4之后参数改变引起的，以修复，参考：https://github.com/yeszao/dnmp/commit/4daa530c79d9d472e805bc1362b4f1853360ad94
