### ISSUE TITLE
安装后PHP xdebug扩展没有安装

### ISSUE THREAD

**Issue by jayeley** [yeszao/dnmp#238]
今天刚装了一个在本机，dphp进去看了一下php版本是7.4.1，php.ini 里面有xdebug的配置，但是phpinfo 显示xdebug 并没有安装。这个是因为PHP版本的原因吗？

**Comment by genwocaigudian** [comment]
相同问题, 我php7.3版本, 从pecl上升级了下xdebug版本, 就可以了.

**Comment by yeszao** [comment]
因为xdebug版本和PHP版本不匹配，会出现下面错误，所以安装不成功：
```bash
configure: error: not supported. Need a PHP version >= 7.0.0 and < 7.3.0 (found 7.4.1)
```
已经新加了最新版本的xdebug，重新pull然后重新构建就能用了。

**Comment by Tyraan** [comment]
同样的问题 php7.3.9
