### ISSUE TITLE
php7.4里gd配置错误

### ISSUE THREAD

**Issue by whsyourdaddy** [yeszao/dnmp#239]
dnmp/services/php/extensions/install.sh里210行下面：
        --with-gd \\
        --with-freetype-dir=/usr/include/ \\
        --with-png-dir=/usr/include/ \\
        --with-jpeg-dir=/usr/include/ \\
应该改成这样吧：
        --with-jpeg=/usr/include/ \\
        --with-freetype=/usr/include/ \\
否则的话会报gd配置错误：
![image](https://user-images.githubusercontent.com/44776259/73567528-7e714f80-44a1-11ea-881d-5f9b80b7b983.png)

**Comment by whsyourdaddy** [comment]
如果PHP版本是7.4，那么install.sh里的549行：
docker-php-ext-configure zip --with-libzip=/usr/include
要去掉。否则安装zip扩展时会报错：
![image](https://user-images.githubusercontent.com/44776259/73629585-9a861400-468e-11ea-9962-dad1c9ee1ed1.png)

参见https://github.com/laradock/laradock/issues/2421

**Comment by yeszao** [comment]
已修复
