### ISSUE TITLE
建议添加  pure-ftpd

### ISSUE THREAD

**Issue by ming200825** [yeszao/dnmp#240]
参考:  https://hub.docker.com/r/stilliard/pure-ftpd  

ftp:
    container_name: ftp
    image: stilliard/pure-ftpd
    volumes:
        - "${SOURCE_DIR}:/home/ftpusers/www"
        - "./pure-ftpd:/etc/pure-ftpd"
    restart: always
    ports:
        - "21:21"
    environment:
        PUBLICHOST: localhost
    networks:
      - default

**Comment by yeszao** [comment]
目前暂无这个计划，或者可以提交个pr，我看好不好合进去。
