### ISSUE TITLE
找不到redis和mongodb扩展

### ISSUE THREAD

**Issue by 422835426** [yeszao/dnmp#241]
.env文件中添加了mongodb,redis
PHP_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache,mongodb,redis

curl http://localhost
Redis服务器版本：Redis 扩展未安装
MongoDB服务器版本：MongoDB 扩展未安装

请问是哪里的问题？

**Comment by yeszao** [comment]
用的是哪个PHP版本？5.4吗？

**Comment by AuroraLZDF** [comment]
> 用的是哪个PHP版本？5.4吗？

php7.2.19
遇到同样的问题

**Comment by xingyu-Lu** [comment]
> 用的是哪个PHP版本？5.4吗？



> 用的是哪个PHP版本？5.4吗？

php 7.4.1也是这样

**Comment by xingyu-Lu** [comment]
> 用的是哪个PHP版本？5.4吗？

看了下扩展是安装上了只是连接redis失败了
![image](https://user-images.githubusercontent.com/24647719/74910349-46509300-53f5-11ea-95ce-641e90466c51.png)

**Comment by xingyu-Lu** [comment]
> > 用的是哪个PHP版本？5.4吗？
> 
> 看了下扩展是安装上了只是连接redis失败了
> ![image](https://user-images.githubusercontent.com/24647719/74910349-46509300-53f5-11ea-95ce-641e90466c51.png)
Warning: Redis::connect(): php_network_getaddresses: getaddrinfo failed: Name does not resolve in /www/test.php on line 3

Fatal error: Uncaught RedisException: php_network_getaddresses: getaddrinfo failed: Name does not resolve in /www/test.php:3
Stack trace:
#0 /www/test.php(3): Redis->connect('redis', 6379)

**Comment by xingyu-Lu** [comment]
> 用的是哪个PHP版本？5.4吗？

![image](https://user-images.githubusercontent.com/24647719/74913334-608d6f80-53fb-11ea-9daa-41dc7e46fb10.png)

redis.ini配置文件没有加载进去

**Comment by yeszao** [comment]
那就是没安装上，单独装一遍，看有没有提示错误
