### ISSUE TITLE
安装时报APKINDEX.811644a4.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by xingyu-Lu** [yeszao/dnmp#242]
WARNING: Ignoring APKINDEX.811644a4.tar.gz: No such file or directory

**Comment by m23100** [comment]
安装时报错

WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.11/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://mirrors.aliyun.com/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.11/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
WARNING: Ignoring APKINDEX.811644a4.tar.gz: No such file or directory

**Comment by yeszao** [comment]
warning不用管，error要看到error内容才行。
