### ISSUE TITLE
最好能添加supervisor扩展

### ISSUE THREAD

**Issue by renzhifan** [yeszao/dnmp#243]
最好能添加supervisor扩展 这个在平常项目中使用还是很多的

**Comment by yymmhh** [comment]
有考虑吗

**Comment by yymmhh** [comment]
@yeszao 能否提交supervisor扩展 的PR

**Comment by jingmian** [comment]
其实每个服务设置`restart: always`运行就可以守护进程执行了,要是进程挂了,它不断尝试重启.
如果添加`supervisor`扩展,等于基本要在每个容器内都安装`apk add supervisor`,然后配置.后续维护也繁琐吧
