### ISSUE TITLE
使用dump后mysql总会自动Restarting 

### ISSUE THREAD

**Issue by isjyi** [yeszao/dnmp#252]
![1584108539(1)](https://user-images.githubusercontent.com/16569948/76628193-52082300-6577-11ea-962e-71123fc1e690.png)

**Comment by jingmian** [comment]
```
  docker logs mysql5
```
查看错误日志

**Comment by whsyourdaddy** [comment]
可能是服务器负载过高了吧，我是用的mysql8也出现了一直重启导致web页面显示不出的问题，在关掉另一个可能给机器带来较高负载的容器后，数据库恢复正常了。
