### ISSUE TITLE
phpmyadmin 打不开

### ISSUE THREAD

**Issue by call4242564** [yeszao/dnmp#257]
![截图](https://user-images.githubusercontent.com/10222029/78753005-b320ec00-79a7-11ea-8188-1dcdd89ba9c2.png)

检查后发现 php-phpmyadmin.ini 文件中配置的 session.save_path = "/sessions" php7容器中好像没有这个目录  修改为/tmp后可以成功打开

**Comment by jingmian** [comment]
我在linux测试无这个问题呢,你是在什么系统下操作

**Comment by fendouai** [comment]
> 我在linux测试无这个问题呢,你是在什么系统下操作

mac 有同样的问题

**Comment by diegomagikal** [comment]
Same here with Ubuntu 20.04 LTS.. Solved with `/tmp`. Thanks.

**Comment by jingmian** [comment]
谢谢反馈,已修改

**Comment by jingmian** [comment]
谢谢反馈,已修改
