### ISSUE TITLE
wordpress安装自定义主题时提示：

### ISSUE THREAD

**Issue by GitMsw** [yeszao/dnmp#261]
**wordpress安装自定义主题时提示：**

连接信息
要执行请求的操作，WordPress需要访问您网页服务器的权限。 请输入您的FTP登录凭据以继续。 如果您忘记了您的登录凭据（如用户名、密码），请联系您的网站托管商。

怎么解决？？？

**Comment by jingmian** [comment]
这个不是docker讨论范围,需要自行排除问题

**Comment by GitMsw** [comment]
谢谢楼主，已经解决了，是我看错了。。。
