### ISSUE TITLE
容器内为啥使用curl的时候报错  curl: (7) Failed to connect to 在外面访问正常

### ISSUE THREAD

**Issue by mr-chen-king** [yeszao/dnmp#262]
如题

**Comment by mr-chen-king** [comment]
问题补充 443端口，如果是用http访问的话进行代理转发，反而可以，就是直接curl https不行

**Comment by mr-chen-king** [comment]
再补充一点 curl 外部服务器的https 地址可以成功，但是curl本服务器部署的docker中的https 服务地址则不行

**Comment by mr-chen-king** [comment]
难道是域名解析有问题吗

**Comment by mr-chen-king** [comment]
curl -L  访问http 跟踪重定向的时候也是报错
 Failed to connect to ******* port 443: Host is unreachable

## 难道是端口问题？

**Comment by jingmian** [comment]
![选区_742](https://user-images.githubusercontent.com/20872873/79432199-150fd000-7ffe-11ea-8b92-b147f221d3d6.png)
我这里显示正常呢

**Comment by mr-chen-king** [comment]
你这个是外部的连接，我的意思是连接自己服务器中nginx https服务同一个network网关的，不过问题我解决了，要在php 的容器中 的hosts 中进行一个域名映射 例如 172.25.0.5   hostname，其中172.25.0.5是nginx docker在网关中的ip，不过还是谢谢

**Comment by mr-chen-king** [comment]
不知道是啥问题 curl http的时候没问题，就是 https 转443端口才会出这问题，这样解决了也不知道啥原因，难道是443端口会验证防火墙问题，为80端口不需要 =-=

**Comment by mr-chen-king** [comment]
这样改容器中相关配置文件的方式不太好，如果容器的ip变了还得重新配，希望有个更好的办法

**Comment by Madoka-Kaname** [comment]
127.0.0.1加nginx监听的服务端口号不就好了 你用容器ip干嘛 那是随机分配的

**Comment by yeszao** [comment]
如 @Madoka-Kaname 所说，直接用容器名称，而不是IP地址，例如：
```shell
curl http://nginx:443
```
