### ISSUE TITLE
创建php容器的时候会报错

### ISSUE THREAD

**Issue by Ynwasususama** [yeszao/dnmp#264]
好像是网络连接问题  搜了下 https://www.ioiox.com/archives/62.html 可以看这个链接修改hosts解决，之前是没有的  今天装的时候遇到了

**Comment by jingmian** [comment]
这是网络导致,中国电信线路比较本地,可以访问github,其他就一般般

**Comment by xingyu-Lu** [comment]
> 好像是网络连接问题 搜了下 https://www.ioiox.com/archives/62.html 可以看这个链接修改hosts解决，之前是没有的 今天装的时候遇到了

fetch http://mirrors.aliyun.com/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.11/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
fetch http://mirrors.aliyun.com/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.11/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
老铁，你的也是报这个吗

**Comment by Ynwasususama** [comment]
@xingyu-Lu 不是  我是raw.github那个可能连接不对 按链接中修改host可以了  你的这个试下群主说的先点链接下载下来 然后放到项目了看看 具体放哪我不太清楚

**Comment by batouy** [comment]
经尝试，此方法可以行通：

1. 翻墙，通过https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions这个地址，直接将该脚本下载到本地；

2. 下载下来以后，默认文件后缀名是.txt，通过copy命令去掉后缀，放在./services/php目录下；

3. 修改./services/php目录下的Dockerfile文件， 注释18行的“ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/”，添加一行："ADD ./install-php-extensions /usr/local/bin/"；

4.  重新执行“docker-compose up”即可；

**Comment by jingmian** [comment]
谢谢,已将此方法更新到最新版
