### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by xingyu-Lu** [yeszao/dnmp#266]
docker版本：Docker version 19.03.8, build afacb8b
docker-compose版本：docker-compose version 1.25.5, build 8a1c60f6
确实要报错，大佬有时间就看看吧，我没辙了
![image](https://user-images.githubusercontent.com/24647719/80489429-6458e780-8992-11ea-9fe5-973cd2c069c6.png)

**Comment by xingyu-Lu** [comment]
估计是在虚拟机里有问题

**Comment by haohaisheng** [comment]
不是虚拟机的问题，正常的centos也有这个问题

**Comment by xingyu-Lu** [comment]
我找到的问题是容器不能联网，桥接方式，但正常来说应该能连才对，不知道是我在虚拟机里装的docker的原因还是其他，有老铁说正常的centos也有这个问题，就更迷惑了

**Comment by xingyu-Lu** [comment]
意外的惊喜，今天去弄又好了。
