### ISSUE TITLE
安装报错 ERROR: Service 'php' failed to build: The command '/bin/sh -c chmod +x install.sh     && sh install.sh     && rm -rf /tmp/extensions' returned a non-zero code: 1

### ISSUE THREAD

**Issue by haohaisheng** [yeszao/dnmp#267]
![Uploading image.png…]()

安装时报错：

`---------- Install opcache ----------
fetch http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  autoconf (missing):
    required by: .phpize-deps-0[autoconf]
  dpkg-dev (missing):
    required by: .phpize-deps-0[dpkg-dev]
  dpkg (missing):
    required by: .phpize-deps-0[dpkg]
  file (missing):
    required by: .phpize-deps-0[file]
  g++ (missing):
    required by: .phpize-deps-0[g++]
  gcc (missing):
    required by: .phpize-deps-0[gcc]
  libc-dev (missing):
    required by: .phpize-deps-0[libc-dev]
  make (missing):
    required by: .phpize-deps-0[make]
  pkgconf (missing):
    required by: .phpize-deps-0[pkgconf]
  re2c (missing):
    required by: .phpize-deps-0[re2c]

---------- Install gd ----------
fetch http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:
  freetype (missing):
    required by: world[freetype]
  freetype-dev (missing):
    required by: world[freetype-dev]
  libjpeg-turbo (missing):
    required by: world[libjpeg-turbo]
  libjpeg-turbo-dev (missing):
    required by: world[libjpeg-turbo-dev]
  libpng (missing):
    required by: world[libpng]
  libpng-dev (missing):
    required by: world[libpng-dev]

---------- curl is installed ----------
**WARNING: Ignoring APKINDEX.2ac53f5f.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.96fa836e.tar.gz: No such file or directory**

**ERROR: Service 'php' failed to build: The command '/bin/sh -c chmod +x install.sh     && sh install.sh     && rm -rf /tmp/extensions' returned a non-zero code: 1**
`

**Comment by jingmian** [comment]
提示`ERROR: unsatisfiable constraints:`,估计你容器网络无法连接

**Comment by xingyu-Lu** [comment]
> 安装时报错：
> 
> `---------- Install opcache ----------
> fetch http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
> fetch http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
> WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> ERROR: unsatisfiable constraints:
> autoconf (missing):
> required by: .phpize-deps-0[autoconf]
> dpkg-dev (missing):
> required by: .phpize-deps-0[dpkg-dev]
> dpkg (missing):
> required by: .phpize-deps-0[dpkg]
> file (missing):
> required by: .phpize-deps-0[file]
> g++ (missing):
> required by: .phpize-deps-0[g++]
> gcc (missing):
> required by: .phpize-deps-0[gcc]
> libc-dev (missing):
> required by: .phpize-deps-0[libc-dev]
> make (missing):
> required by: .phpize-deps-0[make]
> pkgconf (missing):
> required by: .phpize-deps-0[pkgconf]
> re2c (missing):
> required by: .phpize-deps-0[re2c]
> 
> ---------- Install gd ----------
> fetch http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
> fetch http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
> WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> ERROR: unsatisfiable constraints:
> freetype (missing):
> required by: world[freetype]
> freetype-dev (missing):
> required by: world[freetype-dev]
> libjpeg-turbo (missing):
> required by: world[libjpeg-turbo]
> libjpeg-turbo-dev (missing):
> required by: world[libjpeg-turbo-dev]
> libpng (missing):
> required by: world[libpng]
> libpng-dev (missing):
> required by: world[libpng-dev]
> 
> ---------- curl is installed ----------
> WARNING: Ignoring APKINDEX.2ac53f5f.tar.gz: No such file or directory
> WARNING: Ignoring APKINDEX.96fa836e.tar.gz: No such file or directory
> 
> ERROR: Service 'php' failed to build: The command '/bin/sh -c chmod +x install.sh && sh install.sh && rm -rf /tmp/extensions' returned a non-zero code: 1
> `

@haohaisheng 老哥你这个问题解决了吗

**Comment by haohaisheng** [comment]
没有解决呀，不是这个问题就是那问题，自己搞不定了呀。

**Comment by Ystars** [comment]
> > 安装时报错：
> > `---------- Install opcache ----------
> > fetch http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
> > fetch http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
> > WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> > WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> > ERROR: unsatisfiable constraints:
> > autoconf (missing):
> > required by: .phpize-deps-0[autoconf]
> > dpkg-dev (missing):
> > required by: .phpize-deps-0[dpkg-dev]
> > dpkg (missing):
> > required by: .phpize-deps-0[dpkg]
> > file (missing):
> > required by: .phpize-deps-0[file]
> > g++ (missing):
> > required by: .phpize-deps-0[g++]
> > gcc (missing):
> > required by: .phpize-deps-0[gcc]
> > libc-dev (missing):
> > required by: .phpize-deps-0[libc-dev]
> > make (missing):
> > required by: .phpize-deps-0[make]
> > pkgconf (missing):
> > required by: .phpize-deps-0[pkgconf]
> > re2c (missing):
> > required by: .phpize-deps-0[re2c]
> > ---------- Install gd ----------
> > fetch http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz
> > fetch http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz
> > WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> > WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.9/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
> > ERROR: unsatisfiable constraints:
> > freetype (missing):
> > required by: world[freetype]
> > freetype-dev (missing):
> > required by: world[freetype-dev]
> > libjpeg-turbo (missing):
> > required by: world[libjpeg-turbo]
> > libjpeg-turbo-dev (missing):
> > required by: world[libjpeg-turbo-dev]
> > libpng (missing):
> > required by: world[libpng]
> > libpng-dev (missing):
> > required by: world[libpng-dev]
> > ---------- curl is installed ----------
> > WARNING: Ignoring APKINDEX.2ac53f5f.tar.gz: No such file or directory
> > WARNING: Ignoring APKINDEX.96fa836e.tar.gz: No such file or directory
> > ERROR: Service 'php' failed to build: The command '/bin/sh -c chmod +x install.sh && sh install.sh && rm -rf /tmp/extensions' returned a non-zero code: 1
> > `
> 
> @haohaisheng 老哥你这个问题解决了吗

请问你解决了吗？

**Comment by fslyfeng** [comment]
同样问，求解

**Comment by jingmian** [comment]
切换阿里云源试试,
提示`unsatisfiable constraints:`,网络不可达,

**Comment by fslyfeng** [comment]
> 切换阿里云源试试,
> 提示`unsatisfiable constraints:`,网络不可达,

是的，用外网vps正常，但内网的nas上的vps就出这个.换了几个不同源，重启了也一样。
应是内网的dns 等网络问题，就是不知为何，因为安装docker等软件正常，你这个的php7.1到php7.4也正常。就是只有php5.6不行，就奇怪了。

**Comment by jingmian** [comment]
php5.6,你选择安装的扩展有哪些,你粘贴来,我测试安装下

**Comment by fslyfeng** [comment]
> php5.6,你选择安装的扩展有哪些,你粘贴来,我测试安装下

可以了，重装了Debian10,开启科学上网。装上docker-compose后，不用改源
第一次不成功 ，之后改了你提到的 nginx 配置 php56 就成功运行了。

编译中只有以下少量错误，其它正常。 正在装网站，试试


Installing shared extensions:     /usr/local/lib/php/extensions/no-debug-non-zts-20131226/
find . -name \*.gcno -o -name \*.gcda | xargs rm -f
find . -name \*.lo -o -name \*.o | xargs rm -f
find . -name \*.la -o -name \*.a | xargs rm -f
find . -name \*.so | xargs rm -f
find . -name .libs -a -type d|xargs rm -rf
rm -f libphp.la       modules/* libs/*
WARNING: Ignoring APKINDEX.e3d33561.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.39d9158a.tar.gz: No such file or directory
