### ISSUE TITLE
mongodb每次启动 总是失败

### ISSUE THREAD

**Issue by moon-zhangyue** [yeszao/dnmp#268]
`mongodb    | 2020-05-06T11:11:11.286+0800 I  CONTROL  [main] Automatically disabling TLS 1.0, to force-enable TLS 1.0 specify --sslDisabledProtocols 'none'
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=940cb84a9a5b
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] db version v4.1.13
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] git version: 441714bc4c70699950f3ac51a5cac41dcd413eaa
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] allocator: tcmalloc
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] modules: none
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] build environment:
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten]     distmod: ubuntu1804
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten]     distarch: x86_64
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten]     target_arch: x86_64
mongodb    | 2020-05-06T11:11:11.290+0800 I  CONTROL  [initandlisten] options: { net: { bindIp: "*" }, security: { authorization: "enabled" } }
mongodb    | 2020-05-06T11:11:11.297+0800 I  STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=1445M,session_max=33000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),verbose=(checkpoint_progress),
mongodb    | 2020-05-06T11:11:11.815+0800 E  STORAGE  [initandlisten] WiredTiger error (17) [1588734671:815007][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1588734671:815007][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: File exists
mongodb    | 2020-05-06T11:11:11.832+0800 I  STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.48
mongodb    | 2020-05-06T11:11:11.836+0800 E  STORAGE  [initandlisten] WiredTiger error (1) [1588734671:836121][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1588734671:836121][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
mongodb    | 2020-05-06T11:11:11.860+0800 E  STORAGE  [initandlisten] WiredTiger error (17) [1588734671:859961][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1588734671:859961][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: File exists
mongodb    | 2020-05-06T11:11:11.868+0800 I  STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.49
mongodb    | 2020-05-06T11:11:11.901+0800 E  STORAGE  [initandlisten] WiredTiger error (1) [1588734671:901550][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1588734671:901550][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
mongodb    | 2020-05-06T11:11:11.918+0800 E  STORAGE  [initandlisten] WiredTiger error (17) [1588734671:918955][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: File exists Raw: [1588734671:918955][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: File exists
mongodb    | 2020-05-06T11:11:11.923+0800 I  STORAGE  [initandlisten] WiredTiger message unexpected file WiredTiger.wt found, renamed to WiredTiger.wt.50
mongodb    | 2020-05-06T11:11:11.928+0800 E  STORAGE  [initandlisten] WiredTiger error (1) [1588734671:928205][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted Raw: [1588734671:928205][1:0x7fe22c5c0ac0], connection: __posix_open_file, 712: /data/db/WiredTiger.wt: handle-open: open: Operation not permitted
mongodb    | 2020-05-06T11:11:11.931+0800 W  STORAGE  [initandlisten] Failed to start up WiredTiger under any compatibility version.
mongodb    | 2020-05-06T11:11:11.932+0800 F  STORAGE  [initandlisten] Reason: 1: Operation not permitted
mongodb    | 2020-05-06T11:11:11.932+0800 F  -        [initandlisten] Fatal Assertion 28595 at src/mongo/db/storage/wiredtiger/wiredtiger_kv_engine.cpp 766
mongodb    | 2020-05-06T11:11:11.932+0800 F  -        [initandlisten]
mongodb    |
mongodb    | ***aborting after fassert() failure`

这是为什么呢？这是mongo的配置 没做更改
`  mongodb:
    image: mongo:${MONGODB_VERSION}
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
      TZ: "$TZ"
    volumes:
      - ${DATA_DIR}/mongo:/data/db:rw
      # - ${DATA_DIR}/mongodata:/data/db:rw
      # - ${DATA_DIR}/mongo_key:/mongodata:rw
      - ${DATA_DIR}/mongo_key:/mongo:rw
    ports:
      - "${MONGODB_HOST_PORT}:27017"
    networks:
      - default
    command:
      --auth`

是权限问题吗？win10系统  docker desktop

**Comment by wang577901673** [comment]
win10的文件系统问题导致的， 需要创建一个数据卷

**Comment by wang577901673** [comment]
数据本地化是不行

**Comment by moon-zhangyue** [comment]
> win10的文件系统问题导致的， 需要创建一个数据卷

好的 谢谢, 已经解决了

**Comment by mfei58** [comment]
你好，遇到同样的问题，请教一下怎么解决的~

**Comment by moon-zhangyue** [comment]
> 你好，遇到同样的问题，请教一下怎么解决的~

解决了吗 不好意思 才看到。 弄的比较久远了 要是还没解决 我再瞅瞅  我用的win 感觉在win上 毛病多多

**Comment by lancemach** [comment]
windows 10  Docker Desktop 环境下，接口响应5-10s多，网上说是DNS问题，电脑和软件都设置了DNS还是没有解决，但是在云主机中部署了好几台项目，暂还没有出现这种问题
