### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by shishaoqi** [yeszao/dnmp#269]
Step 10/18 : ADD https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions /usr/local/bin/
ERROR: Service 'php74' failed to build: ADD failed: Get https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions: Service Unavailable

**Comment by shishaoqi** [comment]
新增install-php-extensions，测试量不够？

**Comment by jingmian** [comment]
是网络不行,一般用电信网络才可以访问raw.githubusercontent.com网站.这个代码可以删除的,你构建完后,进去容器,在手动执行这个命令
