### ISSUE TITLE
Service 'php' failed to build

### ISSUE THREAD

**Issue by ainyko** [yeszao/dnmp#270]
ERROR: Service 'php' failed to build: ADD failed: Get https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions: dial tcp 0.0.0.0:443: connect: connection refused

**Comment by ainyko** [comment]
翻墙，通过https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions这个地址，直接将该脚本下载到本地,已经翻墙了还是下载不了，博主能否下载到本地中？

**Comment by ainyko** [comment]
> ERROR: Service 'php' failed to build: ADD failed: Get https://raw.githubusercontent.com/mlocati/docker-php-extension-installer/master/install-php-extensions: dial tcp 0.0.0.0:443: connect: connection refused

解决方案：
https://github.com/mlocati/docker-php-extension-installer

**Comment by jingmian** [comment]
谢谢建议,已更新到本地
