### ISSUE TITLE
php使用 7.4.1-fpm 使用 -alpine 后缀的镜像存在数据库读取精度会有问题

### ISSUE THREAD

**Issue by zxzgit** [yeszao/dnmp#272]
发现 php使用 7.4.1-fpm-alpine、7.3.1-fpm-alpine 后缀的镜像存在数据库读取数据精度会有问题，如果直接使用 7.4.1-fpm 则不会有这个数据库读取数据错误的问题，估计 alpine 的镜像的可能都会有这个问题。数据库中某个float字段 比如为 0.93 ，读取后会为 0.94，  0.99读取后会为1。希望您有时间可以注意下，避免使用者不必要的损失和困难

**Comment by jingmian** [comment]
一般计算金额或者需要准确数据,可以选择用`decimal`的,如果你一定要设置float字段,长度请设置为`21,4`
而且我测试了一下,长度设置`21,4`和`21,2`也没有出现0.93读取会得到0.94.请自行新建创建test文件测试
![选区_750](https://user-images.githubusercontent.com/20872873/82855741-b44dae80-9f3e-11ea-813d-687fbf2f059e.png)
![选区_751](https://user-images.githubusercontent.com/20872873/82855744-b6177200-9f3e-11ea-8618-6a8cabf1508a.png)
![选区_752](https://user-images.githubusercontent.com/20872873/82855746-b7e13580-9f3e-11ea-98b9-a5dc4f68ba51.png)

**Comment by zxzgit** [comment]
> 一般计算金额或者需要准确数据,可以选择用`decimal`的,如果你一定要设置float字段,长度请设置为`21,4`
> 而且我测试了一下,长度设置`21,4`和`21,2`也没有出现0.93读取会得到0.94.请自行新建创建test文件测试
> ![选区_750](https://user-images.githubusercontent.com/20872873/82855741-b44dae80-9f3e-11ea-813d-687fbf2f059e.png)
> ![选区_751](https://user-images.githubusercontent.com/20872873/82855744-b6177200-9f3e-11ea-8618-6a8cabf1508a.png)
> ![选区_752](https://user-images.githubusercontent.com/20872873/82855746-b7e13580-9f3e-11ea-98b9-a5dc4f68ba51.png)

首先谢谢你的回复，你用的是mysqli查询的吗？我原本发现float读取错误的是pdo查询，今天我了试了下mysqli查询，读取float值是正确的，pdo的读取float字段还是有问题。

**Comment by zxzgit** [comment]
> 一般计算金额或者需要准确数据,可以选择用`decimal`的,如果你一定要设置float字段,长度请设置为`21,4`
> 而且我测试了一下,长度设置`21,4`和`21,2`也没有出现0.93读取会得到0.94.请自行新建创建test文件测试
> ![选区_750](https://user-images.githubusercontent.com/20872873/82855741-b44dae80-9f3e-11ea-813d-687fbf2f059e.png)
> ![选区_751](https://user-images.githubusercontent.com/20872873/82855744-b6177200-9f3e-11ea-8618-6a8cabf1508a.png)
> ![选区_752](https://user-images.githubusercontent.com/20872873/82855746-b7e13580-9f3e-11ea-98b9-a5dc4f68ba51.png)

首先谢谢您的回复，你用的是mysqli查询的吗？我原本发现float读取错误的是pdo查询，今天我了试了下mysqli查询，读取float值是正确的，pdo的读取float字段还是有问题。

比如
float(10,2), 0.93 会被读取为0.94
float(21,4), 0.9393 会被读取为0.9394

**Comment by zxzgit** [comment]
> 一般计算金额或者需要准确数据,可以选择用`decimal`的,如果你一定要设置float字段,长度请设置为`21,4`
> 而且我测试了一下,长度设置`21,4`和`21,2`也没有出现0.93读取会得到0.94.请自行新建创建test文件测试
> ![选区_750](https://user-images.githubusercontent.com/20872873/82855741-b44dae80-9f3e-11ea-813d-687fbf2f059e.png)
> ![选区_751](https://user-images.githubusercontent.com/20872873/82855744-b6177200-9f3e-11ea-8618-6a8cabf1508a.png)
> ![选区_752](https://user-images.githubusercontent.com/20872873/82855746-b7e13580-9f3e-11ea-98b9-a5dc4f68ba51.png)

首先谢谢您的回复，您用的是mysqli查询的吗？我原本发现float读取错误的是pdo查询，今天我了试了下mysqli查询，读取float值是正确的，pdo的读取float字段还是有问题。

比如
float(10,2), 0.93 会被读取为0.94
float(21,4), 0.9393 会被读取为0.9394

**Comment by jingmian** [comment]
我是用PDO的,确实没有出现这个0.93会变0.94的情况出现
```php
/**
 * 获取MySQL版本
 */
function getMysqlVersion()
{
    if (extension_loaded('PDO_MYSQL')) {
        try {
            $dbh = new PDO('mysql:host=mysql;dbname=test', 'root', '123456');
            $sth = $dbh->query('SELECT VERSION() as version');
            foreach ($dbh->query('SELECT * from hello') as $row) {
                print_r($row);
            }
          //  $info = $sth->fetch();
        } catch (PDOException $e) {
            return $e->getMessage();
        }
       // return $info['version'];
    } else {
        return 'PDO_MYSQL 扩展未安装 ×';
    }

}
```
![选区_753](https://user-images.githubusercontent.com/20872873/82887847-28a64300-9f7b-11ea-8f29-fe5b51fba909.png)

**Comment by zxzgit** [comment]
> ```
> foreach ($dbh->query('SELECT * from hello') as $row) {
>                 print_r($row);
>             }
> ```

我又试了下，我发现跟 $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES, false); ，由于我这里使用laravel 5.7.21,我刚才查找laravel代码关于查询的配置，发现它的查询配置中该值也为false，所以可能导致了之前读取错误，而我使用非 alpine 的 7.4.1-fpm则没有该问题

你可以使用如下，看是否有此问题
/**
 * 获取MySQL版本
 */
function getMysqlVersion()
{
    if (extension_loaded('PDO_MYSQL')) {
        try {
            $dbh = new PDO('mysql:host=192.168.56.10;dbname=11daijia_backend_2020-5-22', 'root', 'MyNewPass4!');
            $sth = $dbh->query('SELECT VERSION() as version');
            
           
            $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
            $dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $stmt = $dbh->prepare('SELECT * FROM zxz_test_float_read order by id desc limit 1');
            $stmt->execute();
            
            foreach ($stmt as $row) {
                print_r($row);
            }

            
            $info = $sth->fetch();
        } catch (PDOException $e) {
            return $e->getMessage();
        }
        return $info['version'];
    } else {
        return 'PDO_MYSQL 扩展未安装 ×';
    }

}

**Comment by zxzgit** [comment]
> 我是用PDO的,确实没有出现这个0.93会变0.94的情况出现
> 
> ```
> /**
>  * 获取MySQL版本
>  */
> function getMysqlVersion()
> {
>     if (extension_loaded('PDO_MYSQL')) {
>         try {
>             $dbh = new PDO('mysql:host=mysql;dbname=test', 'root', '123456');
>             $sth = $dbh->query('SELECT VERSION() as version');
>             foreach ($dbh->query('SELECT * from hello') as $row) {
>                 print_r($row);
>             }
>           //  $info = $sth->fetch();
>         } catch (PDOException $e) {
>             return $e->getMessage();
>         }
>        // return $info['version'];
>     } else {
>         return 'PDO_MYSQL 扩展未安装 ×';
>     }
> 
> }
> ```
> 
> ![选区_753](https://user-images.githubusercontent.com/20872873/82887847-28a64300-9f7b-11ea-8f29-fe5b51fba909.png)

我又试了下，我发现跟 $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES, false); ，由于我这里使用laravel 5.7.21,我刚才查找laravel代码关于查询的配置，发现它的查询配置中该值也为false，所以可能导致了之前读取错误，而我使用非 alpine 的 7.4.1-fpm则没有该问题

你可以使用如下，看是否有此问题

````
/**
 * 获取MySQL版本
 */
function getMysqlVersion()
{
    if (extension_loaded('PDO_MYSQL')) {
        try {
            $dbh = new PDO('mysql:host=192.168.56.10;dbname=11daijia_backend_2020-5-22', 'root', 'MyNewPass4!');
            $sth = $dbh->query('SELECT VERSION() as version');
            
            $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
            $dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $stmt = $dbh->prepare('SELECT * FROM zxz_test_float_read order by id desc limit 1');
            $stmt->execute();
            
            foreach ($stmt as $row) {
                print_r($row);
            }
            
            $info = $sth->fetch();
        } catch (PDOException $e) {
            return $e->getMessage();
        }
        return $info['version'];
    } else {
        return 'PDO_MYSQL 扩展未安装 ×';
    }

}
````

**Comment by zxzgit** [comment]
> 我是用PDO的,确实没有出现这个0.93会变0.94的情况出现
> 
> ```
> /**
>  * 获取MySQL版本
>  */
> function getMysqlVersion()
> {
>     if (extension_loaded('PDO_MYSQL')) {
>         try {
>             $dbh = new PDO('mysql:host=mysql;dbname=test', 'root', '123456');
>             $sth = $dbh->query('SELECT VERSION() as version');
>             foreach ($dbh->query('SELECT * from hello') as $row) {
>                 print_r($row);
>             }
>           //  $info = $sth->fetch();
>         } catch (PDOException $e) {
>             return $e->getMessage();
>         }
>        // return $info['version'];
>     } else {
>         return 'PDO_MYSQL 扩展未安装 ×';
>     }
> 
> }
> ```
> 
> ![选区_753](https://user-images.githubusercontent.com/20872873/82887847-28a64300-9f7b-11ea-8f29-fe5b51fba909.png)

我又试了下，我发现跟 $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES, false); 有关，之前我这里使用laravel 5.7.21,我刚才查找laravel代码关于查询的配置，发现它的查询配置中该值也为false，所以可能导致了之前读取错误，而我使用非 alpine 的 7.4.1-fpm则没有该问题

```
/**
 * 获取MySQL版本
 */
function getMysqlVersion()
{
    if (extension_loaded('PDO_MYSQL')) {
        try {
            $dbh = new PDO('mysql:host=192.168.56.10;dbname=test', 'root', '123456');
            $sth = $dbh->query('SELECT VERSION() as version');
            
            $dbh->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
            $dbh->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            $stmt = $dbh->prepare('SELECT * FROM hello order by id desc limit 1');
            $stmt->execute();
            
            foreach ($stmt as $row) {
                print_r($row);
            }
            
            $info = $sth->fetch();
        } catch (PDOException $e) {
            return $e->getMessage();
        }
        return $info['version'];
    } else {
        return 'PDO_MYSQL 扩展未安装 ×';
    }
    
}
```

**Comment by jingmian** [comment]
这个问题在apline 官网有解决方案,就是重构建php本身镜像,可以参考以下链接
[PHP with PDO cannot return the correct native value from the database](https://gitlab.alpinelinux.org/alpine/aports/issues/11072#login-pane)

第二种方法,在你的`laravel`框架中的` config/databases.php`添加以下配置
```php
            'options'  => [
                PDO::ATTR_EMULATE_PREPARES => true,// 模拟预处理语句
            ]
```

**Comment by zxzgit** [comment]
> 这个问题在apline 官网有解决方案,就是重构建php本身镜像,可以参考以下链接
> [PHP with PDO cannot return the correct native value from the database](https://gitlab.alpinelinux.org/alpine/aports/issues/11072#login-pane)
> 
> 第二种方法,在你的`laravel`框架中的` config/databases.php`添加以下配置
> 
> ```
>             'options'  => [
>                 PDO::ATTR_EMULATE_PREPARES => true,// 模拟预处理语句
>             ]
> ```

嗯，非常谢谢，我在自己使用时已经改写php的Dockerfile 该用7.4.1-fpm 镜像。建议是不是要在仓库中修复下这个问题，以免其他人使用过程中碰到同样的问题造成的困恼。

**Comment by jingmian** [comment]
我找到有更好的解决方法时,会修复这个问题

**Comment by lazzzy18** [comment]
@jingmian  您好，我测试了一下，7.4.7版本目前已经没有出现这种情况了，您可以测试一下。
