### ISSUE TITLE
关于配置文件.env的问题

### ISSUE THREAD

**Issue by yanghuanfirst** [yeszao/dnmp#276]
我看到.evn里，php7.4和php5.6的配置文件都是一个？都是services/php/php.ini?

请问一下：我安装多个版本的PHP，比如我安装PHP7.4和PHP5.6，配置文件都是一样吗？不能自动生成php.ini和php-fpm？

**Comment by jingmian** [comment]
已经通过`volumes`根据不同版本映射到不同的`php.ini`和`php-fpm`了

**Comment by yanghuanfirst** [comment]
> 已经通过`volumes`根据不同版本映射到不同的`php.ini`和`php-fpm`了
volumes配置的是php7.4和php5.6指定的php.ini和php-fpm都是一个路径啊，就是services/php/php.ini和services/php/php-fpm，而且如果我同时开启php7.4和php5.6两个版本的容器，配置文件目录services也只有PHP一个配置文件目录，不会有PHP5.6的配置文件。

**Comment by jingmian** [comment]
谢谢你反馈,已更新好

**Comment by yanghuanfirst** [comment]
> 谢谢你反馈,已更新好

3Q
