### ISSUE TITLE
请问MAC上加载速度特别慢怎么办？

### ISSUE THREAD

**Issue by xuanyue0522** [yeszao/dnmp#277]
因为I/O的问题，mac上加载速度特别慢，查了很多资料没查到解决方案，各位大佬请问怎么办啊，同样项目同样环境配置，不用docker 加载1s，使用docker 6s多，崩溃了

**Comment by nowindexman** [comment]
文件系统的问题暂时无解，暂时可用docker的cached来解决。
在docker-compose.yml文件中目录映射中配置。
如： ${SOURCE_DIR}:/www/:cached

**Comment by rkxs** [comment]
vagrant+docker 可以解决。也就是linux虚拟机里面装docker
