### ISSUE TITLE
刚刚发现PHP56里面没有dockerfile和扩展包？是共用php里的dockerfile吗？

### ISSUE THREAD

**Issue by yanghuanfirst** [yeszao/dnmp#278]
刚刚发现PHP56目录下没有dockerfile和扩展包？是共用php目录下的dockerfile吗？

**Comment by jingmian** [comment]
是的,在`install.sh`已经有判断好`php7`和`php56`扩展

**Comment by yanghuanfirst** [comment]
> 是的,在`install.sh`已经有判断好`php7`和`php56`扩展

哦哦，那意思就是说，如果我现在要装个PHP7.0的版本，，我只需要把services/php目录复制一份改名为php70,然后改改.env和docker-compose.yml都指定php70相应的配置就行了，是吧？

**Comment by jingmian** [comment]
是的

**Comment by yanghuanfirst** [comment]
> 是的

好的，3Q
