### ISSUE TITLE
建议增加php cli下php.ini等配置文件

### ISSUE THREAD

**Issue by taobali32** [yeszao/dnmp#291]
### 问题: 安装composer包时会出现一下错误
```shell
Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 4096 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/RuleWatchGraph.php on line 52

Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of/你的目录
```

### 查看配置项
```shell
➜  7.2 php -r "echo ini_get('memory_limit');"
128M  
```

### 问题整体(php 容器内)
```shell
/www # php -r "echo ini_get('memory_limit');"
128M/www # 
/www # php -r "ini_set('memory_limit','2048MB');"
/www # 
/www # php -r "echo ini_get('memory_limit');"
128M/www # 
/www # 


```

**Comment by taobali32** [comment]
### 不是最优的解决办法
```shell
find / -name compoer // 找到你的composer安装路径，我的 /usr/bin/composer

//	运行你的东西
php -d memory_limit=-1 /usr/bin/composer require barryvdh/laravel-debugbar --dev
```

**Comment by jingmian** [comment]
增加cli配置,后期可能单独增加一个cli的容器实现
当你执行` php -r "ini_set('memory_limit','2048MB');"`只是动态改变了内存,
当php进程退出了,下次再次` php -r "echo ini_get('memory_limit');"`,依然只是`128M`,不会改变的.
其实你可以手动复制一个php.ini文件,改名`custom.ini`,使用`-c`方式指定一个ini配置文件运行就可以了
`php -c /usr/local/etc/php/custom.ini my_script.php`

**Comment by taobali32** [comment]
> 增加cli配置，后期可能单独增加一个cli的容器实现
> 当你执行` php -r "ini_set('memory_limit','2048MB');"`只是动态改变了内存，
> 当php进程退出了，再次再次` php -r "echo ini_get('memory_limit');"`，依然只是`128M`，不会改变的。
> 实际上你可以手动复制一个php.ini文件，改名`custom.ini`，使用`-c`方式指定一个ini配置文件运行就可以了
> `php -c /usr/local/etc/php/custom.ini my_script.php`

非常感觉帮助我，问题已解决
