### ISSUE TITLE
无法安装redis swoole扩展

### ISSUE THREAD

**Issue by casshong** [yeszao/dnmp#293]
已经在.env文件中添加以下参数

PHP_VERSION=7.4.7
PHP_PHP_CONF_FILE=./services/php/php.ini
PHP_FPM_CONF_FILE=./services/php/php-fpm.conf
PHP_LOG_DIR=./logs/php
PHP_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache,redis,swoole

并且重新build，但php -m时仍然未见redis及swoole扩展
在容器中/usr/local/lib/php/extensions/no-debug-non-zts-20190902/文件夹下也未发现相关so文件

**Comment by casshong** [comment]
docker-compose up就好le

**Comment by yangjingchuang** [comment]
> docker-compose up就好le

大佬，我为啥这么做不可以？？
1：docker-compose restart php
2：docker-compose build php
依次操作上面两部，但是最后还是不可以
