### ISSUE TITLE
宿主机连接了vpn，容器内无法访问宿主机的vpn网络

### ISSUE THREAD

**Issue by casshong** [yeszao/dnmp#294]
如题，请问如何解决

**Comment by casshong** [comment]
很奇怪

**Comment by answer666** [comment]
> 加一

我用的是 clash。 设置白名单就行了。 docker 不用设置。

**Comment by sreio** [comment]
https://github.com/yeszao/dnmp/issues/294#issuecomment-2068572351

是的，我这会也正在设置白名单

```
  - DOMAIN-SUFFIX,local,🎯 全球直连,DIRECT
```

**Comment by sreio** [comment]
> [#294 (comment)](https://github.com/yeszao/dnmp/issues/294#issuecomment-2068572351)
> 
> 是的，我这会也正在设置白名单
> 
> ```
>   - DOMAIN-SUFFIX,local,🎯 全球直连,DIRECT
> ```

所有`local`后缀的域名，全部直连
