### ISSUE TITLE
怎能完整的在线上展示呢？

### ISSUE THREAD

**Issue by wotemenige** [yeszao/dnmp#298]
比如：我在线下使用的是 /www/wwwroot/data  然后开发完了；

我上线上去，我怎么把我本地的docker镜像和容器复制到线上呢？

是直接执行 docker-compose up吗？

**Comment by jingmian** [comment]
要么你把镜像上传到自已的托管镜像中心,然后在拉取.要么只能在服务器上运行  `docker-compose build`重新构建的
