### ISSUE TITLE
comppser 报错

### ISSUE THREAD

**Issue by QingjiLiu** [yeszao/dnmp#299]
按照文档，把composer函数加入到了 .zshrc  (新版的是.zshrc);
但是报下面的错误

/usr/local/bin/docker-php-entrypoint: exec: line 9: composer: not found

**Comment by futuremeng** [comment]
需要source .zshrc来让它加载生效

**Comment by SmileAany** [comment]
你可以使用composer创建项目么？
我composer create的时候，一直提示我没有权限
![Uploading image.png…]()

**Comment by futuremeng** [comment]
如何提示找不到git，但显然是存在的，搜索发现可能是权限问题，就给~/dnmp/data/composer（这里面的dnmp具体在什么位置要看你放在什么地方了）加权限，比如777，compser需要把缓存的文件放到这里面去，另外一个需要给权限的是你要创建的项目的那个地址，也要有权限。
