### ISSUE TITLE
Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by babyandy0111** [yeszao/dnmp#30]
Creating dnmp_php72_1 ... error
ERROR: for dnmp_php72_1  Cannot start service php72: b'Cannot link to a non running container: /dnmp_mysql_1 AS /dnmp_php72_1/dnmp_mysql_1'

ERROR: for php72  Cannot start service php72: b'Cannot link to a non running container: /dnmp_mysql_1 AS /dnmp_php72_1/dnmp_mysql_1'
ERROR: Encountered errors while bringing up the project.

what can i do

**Comment by mengxiabing** [comment]
The same mistake

**Comment by yeszao** [comment]
Hi @babyandy0111  @mengxiabing ,
Please config secure_file_priv to empty in my.cnf:
```
secure_file_priv=""
```

**Comment by babyandy0111** [comment]
thanks for your help :)
it's work
