### ISSUE TITLE
能否把certbot也加进去？

### ISSUE THREAD

**Issue by peyoot** [yeszao/dnmp#302]
dockerhub上有一个certbot官方的certbot
如果能整合在一起就好了，我看有个参考https://www.cloudbooklet.com/how-to-install-nginx-and-lets-encrypt-with-docker-ubuntu-20-04/, 不过它是用官方的nginx

Let's Encrypt用的人还是很多，虽然可以手工安装，不过如果能在compose模板里集成，用户就很容易修改成自用的，一个命令实现布署后自动renew，这样就完美了

**Comment by jingmian** [comment]
这个已经有的了,你在`.env`文件中,找到这行
`
# Available apps: certbot
NGINX_INSTALL_APPS=
`
修改`NGINX_INSTALL_APPS=certbot`,然后重新`build`一次就行了

**Comment by peyoot** [comment]
谢谢，但要生成指定域名的证书如何使用? 需要进入容器发命令么？ 生成的证书放哪，是否支持自动renew?

**Comment by peyoot** [comment]
经过测试，需要把.env中的nginx版本改为1.19.1-alpine，然后进入容器就可以申请let's encrypt证书了，默认的nginx等版本还是旧了些，希望早点更新，毕竟很多人会用let's encrypt证书。
