### ISSUE TITLE
elasticsearch默认配置问题

### ISSUE THREAD

**Issue by XIONGchanghu** [yeszao/dnmp#303]
安装拉下的部署代码测试会一直存在elasticsearch.yml不生效的问题
最终发现问题为：
docker-compose.yml配置的映射为：
/usr/share/elasticsearch/elasticsearch.yml
其实应该为：
/usr/share/elasticsearch/config/elasticsearch.yml
希望官方能修复下避免后面的小伙伴半天发现不了问题

**Comment by jingmian** [comment]
谢谢,已修改
