### ISSUE TITLE
关于/www/localhost

### ISSUE THREAD

**Issue by peyoot** [yeszao/dnmp#305]
我一般要host好几个网站，最简单的就是在/www下创建不同的目录，很早以前我用这个dnmp，那时版本非常旧却很顺畅，最近升级了一下最新的，发现在/www下创建不同的目录，比如myweb， 在services/nginx/conf.d/下再用myweb.conf来定义网站。试了一圈，发觉这具dnmp只认/www/localhost，而不认其它目录！

我即使只用localhost.conf，简单地把root指向其它目录，也是不能用的，不知道这该如何解决。

**Comment by peyoot** [comment]
可能是操作失误

**Comment by oneLZH** [comment]
同样有此问题，麻烦问下是怎么解决的啊
