### ISSUE TITLE
不懂就问，进入supervisord 看到/www文件夹没有数据，怎么写配置呢

### ISSUE THREAD

**Issue by xuyudong** [yeszao/dnmp#308]
![微信图片_20200806151628](https://user-images.githubusercontent.com/12404091/89502886-49e7a300-d7f8-11ea-9b87-622d897276b3.png)

**Comment by flyrory** [comment]
参考PHP镜像www目录挂载方式

**Comment by xuyudong** [comment]
@flyrory 谢谢，已解决
