### ISSUE TITLE
怎么切换 php7.0 php7.1 php7.2 php7.3 php7.4

### ISSUE THREAD

**Issue by dzz2013** [yeszao/dnmp#313]
请问下 怎么切换 php7.0 php7.1 php7.2 php7.3 php7.4 或者我需要这些都共存时需要怎么操作？直接修改配置文件php_version?

**Comment by jingmian** [comment]
每个版本是不同的容器,指定使用哪个版本是在nginx配置文件中的` fastcgi_pass   php:9000;`这里修改就行了.`php`对应容器名称

**Comment by dzz2013** [comment]
我看到docker-compose 里面只有三个容器 php54、php56、php，默认安装 php 的为最新版本 7.4  只有一个容器 如果我同时要使用 php7.0与php7.2 只能复制一份代码重新创建容器？让两个 php 并存

**Comment by jingmian** [comment]
复制多一份`php`构建信息,然后修改容器构建容器的名称`php70`,进行`build`的之前,把`env`文件中的`PHP_VERSION`修改对应版本

**Comment by shaoyikai** [comment]
> 复制多一份`php`构建信息,然后修改容器构建容器的名称`php70`,进行`build`的之前,把`env`文件中的`PHP_VERSION`修改对应版本
请问是复制services/php目录里的所有内容为services/php70这样吗？

**Comment by shaoyikai** [comment]
@jingmian 谢谢

**Comment by GHBJayce** [comment]
再以上大佬说的操作之后，请记得删除原先的镜像
docker rmi dnmp_php -f
然后再docker-compose up

**Comment by shaoyikai** [comment]
发现简单设置下env，然后重新build一下php就可以了。env里`PHP_VERSION`和`SUPERVISOR_PHP_VERSION`的值设置一下，然后执行`docker-compose build php`，然后重启dnmp即可。

只是这种方式会共用php目录，下次换版本仍然需要类似操作。

**Comment by pengpn** [comment]
failed to solve with frontend dockerfile.v0: failed to create LLB definition: docker.io/library/php:7.0.0-fpm-alpine: not found


php7.0报这个错，如何解决
