### ISSUE TITLE
docker-composer up报错

### ISSUE THREAD

**Issue by qiao-summer** [yeszao/dnmp#314]
mysql    | Initializing database
mysql    | mysqld: Can't create/write to file '/var/lib/mysql/is_writable' (OS errno 13 - Permission denied)
mysql    | 2020-08-20T04:11:42.252793Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
mysql    | 2020-08-20T04:11:42.252878Z 0 [Warning] [MY-010915] [Server] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
mysql    | 2020-08-20T04:11:42.252931Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.13) initializing of server in progress as process 27
mysql    | 2020-08-20T04:11:42.254896Z 0 [ERROR] [MY-010460] [Server] --initialize specified but the data directory exists and is not writable. Aborting.
mysql    | 2020-08-20T04:11:42.255481Z 0 [ERROR] [MY-010187] [Server] Could not open file '/var/lib/mysql/mysql.error.log' for error logging: Permission denied
mysql    | 2020-08-20T04:11:42.255502Z 0 [ERROR] [MY-013236] [Server] Newly created data directory /var/lib/mysql/ is unusable. You can safely remove it.
mysql    | 2020-08-20T04:11:42.255507Z 0 [ERROR] [MY-010119] [Server] Aborting
mysql    | 2020-08-20T04:11:42.255892Z 0 [System] [MY-010910] [Server] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.13)  MySQL Community Server - GPL.
mysql exited with code 1

**Comment by yeszao** [comment]
Windows 和 Mac OS 系统给目录授予 Docker 访问权限，这在 Docker 界面操作，如果是 Linux 系统，还需要：
```shell
$ sudo gpasswd -a ${USER} docker
```

**Comment by liapples** [comment]
搞了一上午，终于搞好mysql5了，归根结底还是权限问题。
mysql8.0就没有问题，mysql5.7怎么运行，怎么修改都不行。
之前一直在wsl里面的linux执行docker-compose up，死活不行。第一次运行时自动退出，再第二次就提示--initialize specified but the data directory exists and is not writable. Aborting.

解决方法：其实只需要在windows上进入对应目录，运行docker-compose up就可以了
