### ISSUE TITLE
php 7.2.33 mcrypt安装不了

### ISSUE THREAD

**Issue by justmd5** [yeszao/dnmp#317]
PHP_EXTENSIONS 配置没安装
手动进容器也会报错：error: /usr/src/php/ext/mcrypt does not exist

**Comment by jingmian** [comment]
[PHP 7.1.x 中废弃的特性](https://www.php.net/manual/zh/migration71.deprecated.php)
已经通过pecl方式安装

**Comment by justmd5** [comment]
> [PHP 7.1.x 中废弃的特性](https://www.php.net/manual/zh/migration71.deprecated.php)
> 已经通过pecl方式安装

我是在容器里边使用 

```shell
apk add --no-cache libmcrypt-dev
install-php-extensions  mcrypt
```
安装好了
