### ISSUE TITLE
dnmp-nginx exited with code 1

### ISSUE THREAD

**Issue by smartyaunt** [yeszao/dnmp#32]
nmp-nginx | 2018/05/31 03:15:20 [emerg] 1#1: open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dnmp-nginx | nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)
dnmp-nginx exited with code 1，

**Comment by yeszao** [comment]
修改下这个文件的权限
```
 sudo chmod a+r conf/nginx.conf
```
