### ISSUE TITLE
ERROR: unsatisfiable constraints:

### ISSUE THREAD

**Issue by sampsonliu** [yeszao/dnmp#323]
fetch http://mirrors.aliyun.com/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.12/main/x86_64/APKINDEX.tar.gz: operation timed out
WARNING: Ignoring http://mirrors.aliyun.com/alpine/v3.12/community/x86_64/APKINDEX.tar.gz: operation timed out
ERROR: unsatisfiable constraints:
  autoconf (missing):
    required by: .phpize-deps-20201013.151130[autoconf]
  dpkg-dev (missing):
    required by: .phpize-deps-20201013.151130[dpkg-dev]
  dpkg (missing):
    required by: .phpize-deps-20201013.151130[dpkg]
  file (missing):
    required by: .phpize-deps-20201013.151130[file]
  g++ (missing):
    required by: .phpize-deps-20201013.151130[g++]
  gcc (missing):
    required by: .phpize-deps-20201013.151130[gcc]
  libc-dev (missing):
    required by: .phpize-deps-20201013.151130[libc-dev]
  make (missing):
    required by: .phpize-deps-20201013.151130[make]
  pkgconf (missing):
    required by: .phpize-deps-20201013.151130[pkgconf]
  re2c (missing):
    required by: .phpize-deps-20201013.151130[re2c]

**Comment by jingmian** [comment]
` unsatisfiable constraints`提示网络不通,可以更换电信或者移动网络测试下
