### ISSUE TITLE
5.6 提示的问题

### ISSUE THREAD

**Issue by wukchao** [yeszao/dnmp#33]
The following packages have unmet dependencies:
 libfreetype6-dev : Depends: zlib1g-dev but it is not going to be installed or
                             libz-dev
 libpng12-dev : Depends: zlib1g-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'php5.6' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && :    && apt-get install -y libicu-dev     && docker-php-ext-install intl     && :    && apt-get install -y libxml2-dev     && apt-get install -y libxslt-dev     && docker-php-ext-install soap     && docker-php-ext-install xsl     && docker-php-ext-install xmlrpc     && docker-php-ext-install wddx     && :    && apt-get install -y libbz2-dev     && docker-php-ext-install bz2     && :    && docker-php-ext-install zip     && docker-php-ext-install pcntl     && docker-php-ext-install pdo_mysql     && docker-php-ext-install mysqli     && docker-php-ext-install mbstring     && docker-php-ext-install exif     && docker-php-ext-install bcmath     && docker-php-ext-install calendar     && docker-php-ext-install sockets     && docker-php-ext-install gettext     && docker-php-ext-install shmop     && docker-php-ext-install sysvmsg     && docker-php-ext-install sysvsem     && docker-php-ext-install sysvshm     && docker-php-ext-install opcache     && :    && apt-get install -y libmcrypt-dev     && docker-php-ext-install mcrypt     && :    && apt-get install -y curl     && apt-get install -y libcurl3     && apt-get install -y libcurl4-openssl-dev     && docker-php-ext-install curl     && :    && apt-get install -y inetutils-ping     && apt-get install -y net-tools     && :    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer     && :RUN pecl install redis-3.1.4     && docker-php-ext-enable redis     && :    && pecl install xdebug-2.5.5     && docker-php-ext-enable xdebug     && :    && apt-get install -y libmagickwand-dev     && pecl install imagick-3.4.3     && docker-php-ext-enable imagick     && :    && apt-get install -y libmemcached-dev zlib1g-dev     && pecl install memcached-2.2.0     && docker-php-ext-enable memcached' returned a non-zero code: 100

**Comment by yeszao** [comment]
加个：
```
apt-get install -y zlib1g-dev
```
呢

**Comment by wukchao** [comment]
加了，还是提示这个
The following packages have unmet dependencies:
 zlib1g-dev : Depends: zlib1g (= 1:1.2.8.dfsg-2+b1) but 1:1.2.8.dfsg-5 is to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'php5.6' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y zlib1g-dev    && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && :    && apt-get install -y libicu-dev     && docker-php-ext-install intl     && :    && apt-get install -y libxml2-dev     && apt-get install -y libxslt-dev     && docker-php-ext-install soap     && docker-php-ext-install xsl     && docker-php-ext-install xmlrpc     && docker-php-ext-install wddx     && :    && apt-get install -y libbz2-dev     && docker-php-ext-install bz2     && :    && docker-php-ext-install zip     && docker-php-ext-install pcntl     && docker-php-ext-install pdo_mysql     && docker-php-ext-install mysqli     && docker-php-ext-install mbstring     && docker-php-ext-install exif     && docker-php-ext-install bcmath     && docker-php-ext-install calendar     && docker-php-ext-install sockets     && docker-php-ext-install gettext     && docker-php-ext-install shmop     && docker-php-ext-install sysvmsg     && docker-php-ext-install sysvsem     && docker-php-ext-install sysvshm     && docker-php-ext-install opcache     && :    && apt-get install -y libmcrypt-dev     && docker-php-ext-install mcrypt     && :    && apt-get install -y curl     && apt-get install -y libcurl3     && apt-get install -y libcurl4-openssl-dev     && docker-php-ext-install curl     && :    && apt-get install -y inetutils-ping     && apt-get install -y net-tools     && :    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin/ --filename=composer     && :    && pecl install swoole-1.10.3     && docker-php-ext-enable swoole' returned a non-zero code: 100

**Comment by kleveralt** [comment]
去掉COPY ./sources.list.jessie /etc/apt/sources.list
