### ISSUE TITLE
composer [ErrorException]  mkdir(): Permission denied  

### ISSUE THREAD

**Issue by SmileAany** [yeszao/dnmp#331]
我想要在容器外面直接使用composer，然后我将bash.alias.sample 中的composer的复制到 ～/.bashrc 中，在容器外面确实可以使用composer
但是当我创建一个项目的时候，直接提示我没有权限！请问这个问题该如何解决！
![image](https://user-images.githubusercontent.com/47846456/98104373-5354da00-1ed1-11eb-866d-82469d1b51c6.png)
![Uploading image.png…]()

**Comment by SmileAany** [comment]
有大哥指点下么？谢谢了

**Comment by futuremeng** [comment]
在宿主机，就是容器外面，给给~/dnmp/data/composer这个目录加权限，如果你的dnmp放在当前用户根目录下的话。如果不是，修改前面的地址，对应的就是这个https://github.com/yeszao/dnmp/tree/master/data/composer

**Comment by yangjingchuang** [comment]
> 有大哥指点下么？谢谢了

大佬，咋解决的？？？

**Comment by yangjingchuang** [comment]
> 在宿主机，就是容器外面，给给~/dnmp/data/composer这个目录加权限，如果你的dnmp放在当前用户根目录下的话。如果不是，修改前面的地址，对应的就是这个https://github.com/yeszao/dnmp/tree/master/data/composer

还要给   www 目录添加权限吧
