### ISSUE TITLE
mysql exited with code 1

### ISSUE THREAD

**Issue by taoyafan** [yeszao/dnmp#332]
执行 docker-compose up 后
就无限循环报错：
`mysql exited with code 1`
还五颜六色的，贼好看了。

**Comment by taoyafan** [comment]
`
Creating network "dnmp_default" with the default driver
Creating nginx ... done
Creating mysql ... done
Creating php   ... done
Attaching to mysql, nginx, php
nginx    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx    | /docker-entrypoint.sh: Configuration complete; ready for start up
php      | [10-Nov-2020 21:46:12] NOTICE: fpm is running, pid 1
php      | [10-Nov-2020 21:46:12] NOTICE: ready to handle connections
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
`

**Comment by taoyafan** [comment]
``` shell
Creating network "dnmp_default" with the default driver
Creating nginx ... done
Creating mysql ... done
Creating php   ... done
Attaching to mysql, nginx, php
nginx    | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx    | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx    | 10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist
nginx    | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx    | /docker-entrypoint.sh: Configuration complete; ready for start up
php      | [10-Nov-2020 21:46:12] NOTICE: fpm is running, pid 1
php      | [10-Nov-2020 21:46:12] NOTICE: ready to handle connections
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
mysql exited with code 1
```

**Comment by taoyafan** [comment]
Win10

**Comment by jingmian** [comment]
你单独启动mysql 看看有提示什么错误没

**Comment by taoyafan** [comment]
过了一段时间再试的时候自己好了。。
