### ISSUE TITLE
安装zip 扩展失败

### ISSUE THREAD

**Issue by fleaLi** [yeszao/dnmp#333]
install-php-extensions zip
Updating channel "pecl.php.net"
Channel "pecl.php.net" is up to date
fetch http://mirrors.aliyun.com/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
v3.12.1-24-g9d31f224d7 [http://mirrors.aliyun.com/alpine/v3.12/main]
v3.12.1-25-gea4636f2a5 [http://mirrors.aliyun.com/alpine/v3.12/community]
OK: 12754 distinct packages available
FAILED TO LIST THE WHOLE PACKAGE LIST FOR
 libzip

COMMAND OUTPUT:
ERROR: ' libzip' is not a valid world dependency, format is name(@tag)([<>~=]version)

ERROR: apk failed

**Comment by jingmian** [comment]
可以在`env`添加`zip`然后构建，`install-php-extensions `还需要再优化一下
