### ISSUE TITLE
我想请问里面的superviosr如何使用

### ISSUE THREAD

**Issue by SmileAany** [yeszao/dnmp#335]
因为supervisor是单独的创建了一个容器，那么当supervisor如何守护php容器中的php进程？？？？？？请问有根据作者的文档使用supervisor的么？大佬求带啊！！！！
![image](https://user-images.githubusercontent.com/47846456/99814136-88288880-2b83-11eb-8490-02beb39bc393.png)

**Comment by SmileAany** [comment]
请教各位大佬了！

**Comment by yymmhh** [comment]
这个你可以fork之后自己修改一下,也可以直接用我 fork后修改好的
https://github.com/yymmhh/dnmp

**Comment by SmileAany** [comment]
已经处理好了

**Comment by SmileAany** [comment]
> 这个你可以fork之后自己修改一下,也可以直接用我 fork后修改好的
> 
> https://github.com/yymmhh/dnmp


已经处理了 和你一样将supervisor安到php的容器里面

**Comment by SmileAany** [comment]
谢谢，我也是按照你使用过的，就是将supervisor和php安装到一个容器里面



在 2020-11-22 11:52:44，"万隆" <notifications@github.com> 写道：

这个你可以fork之后自己修改一下,也可以直接用我 fork后修改好的
https://github.com/yymmhh/dnmp

**Comment by shunhua** [comment]
> 这个你可以fork之后自己修改一下,也可以直接用我 fork后修改好的
> https://github.com/yymmhh/dnmp

也是用的这个

**Comment by shunhua** [comment]
新加的supervisor 你们怎么重载配置的啊

**Comment by shunhua** [comment]
> 这个你可以fork之后自己修改一下,也可以直接用我 fork后修改好的
> https://github.com/yymmhh/dnmp
进入容器后 查看状态 一直提示
unix:///run/supervisord.sock no such file

**Comment by shunhua** [comment]
> > 这个你可以fork之后自己修改一下,也可以直接用我 fork后修改好的
> > https://github.com/yymmhh/dnmp
> > 进入容器后 查看状态 一直提示
> > unix:///run/supervisord.sock no such file

解决了

**Comment by shunhua** [comment]
作者这版还没更新吗？
