### ISSUE TITLE
php dockerfile for centos about php ex

### ISSUE THREAD

**Issue by hungryandfoolishboy** [yeszao/dnmp#34]
how to modify the dockerfile to fix it to the centos,because centos use yum to manage package

**Comment by yeszao** [comment]
Hi @hungryandfoolishboy , 
Default, docker use **debian** image to build php-fpm container. we can always use `apt-get` to manage packages in container or Dockerfile, no matter what your host OS is.

On the other hand, even use Windows or Mac system, we can use `apt-get` in **container**.

**Comment by cxs1994** [comment]
你好，可我在nginx的镜像中执行apt-get命令，提示 /bin/sh: apt-get: not found

**Comment by yeszao** [comment]
@cxs1994 nginx使用的是alpine镜像，安装用
```
apk add --no-cache xxx
```
