### ISSUE TITLE
Mac升级docker后，mysql无法启动；docker版本2.5.0.1

### ISSUE THREAD

**Issue by RedSue** [yeszao/dnmp#341]
MacBook-Pro-2:dnmp root# docker-compose up mysql
Starting mysql ... done
Attaching to mysql
mysql            | 2020-11-27 20:08:19+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
mysql            | 2020-11-27 20:08:20+08:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mysql            | 2020-11-27 20:08:20+08:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.22-1debian10 started.
mysql exited with code 1

**Comment by gghtrt520** [comment]
Me too，how to deal with

**Comment by Little-He** [comment]
可以试着清空 data/mysql5 下的文件，从新build  up 试一下
我本地是mysql8一直restarting ，这么操作完成后，可以使用了
