### ISSUE TITLE
php扩展重新build总不生效

### ISSUE THREAD

**Issue by rockyzhuo** [yeszao/dnmp#348]
#
# PHP5.6
#
PHP56_VERSION=5.6.40
PHP56_PHP_CONF_FILE=./services/php56/php.ini
PHP56_FPM_CONF_FILE=./services/php56/php-fpm.conf
PHP56_LOG_DIR=./logs/php
PHP56_EXTENSION_DIR=./services/php56/ext
PHP56_EXTENSIONS=amqp,pdo_mysql,mysqli,mbstring,gd,curl,opcache,redis,memcached,xdebug,bcmath

如上面添加了pdo_mysql，重新build之后进入php容器查看 php -m，没有pdo_mysql的扩展

**Comment by yymmhh** [comment]
注意 docker-compose.yml 中使用的是否是PHP5.6的版本

**Comment by rockyzhuo** [comment]
php56:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP56_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP56_EXTENSIONS}
        TZ: "$TZ"
    container_name: php56
    expose:
      - 9501
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP56_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP56_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP56_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
      - ${PHP56_EXTENSION_DIR}:/tmp/ext
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

**Comment by jingmian** [comment]
`docker-compose.yml `中你的php56那段代码格式可能有误

**Comment by rockyzhuo** [comment]
格式没问题，能正常启动，就是配置的不生效

**Comment by jingmian** [comment]
`context: ./services/php`你这行写了吧，应该是`context: ./services/php56`

**Comment by shunhua** [comment]
其他扩展生效吗、？
