### ISSUE TITLE
容器内时区总是不正确，咋回事

### ISSUE THREAD

**Issue by shunhua** [yeszao/dnmp#349]

**Comment by shunhua** [comment]
容器内 打印 时间 显示总是不对，echo date("Y-m-d"); 总显示 2020-01-01

**Comment by yymmhh** [comment]
尝试容器内用定时任务同步时间

**Comment by shunhua** [comment]
解决了，因为我的电脑长时间没关过机，所以本地docker一直没更新时间，重启了下，时间就正常了，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 万隆 <notifications@github.com&gt;
发送时间: 2021年1月5日 21:54
收件人: yeszao/dnmp <dnmp@noreply.github.com&gt;
抄送: bryant <2399315737@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[yeszao/dnmp] 容器内时区总是不正确，咋回事 (#349)





 
尝试容器内用定时任务同步网络时间
