### ISSUE TITLE
Swoole 没有添加 configure 项目

### ISSUE THREAD

**Issue by wxfjamdc** [yeszao/dnmp#350]
服务端对外进行 https 请求时，会报缺少 openssl 的配置

参考了 https://github.com/swoole/docker-swoole/blob/master/dockerfiles/4.5.10/php7.4/alpine/Dockerfile

编译的时候，默认打开了
--enable-http2   \
        --enable-mysqlnd \
        --enable-openssl \
        --enable-sockets --enable-swoole-json

**Comment by jingmian** [comment]
把你运行的命令，和报错，都发出来

**Comment by wxfjamdc** [comment]
在 swoole 携程内执行 file_get_contents('https://www.baidu.com')
报错：
ErrorException: file_get_contents(): you must configure with `--enable-openssl` to support ssl connection when compiling Swoole in ...

**Comment by yangjingchuang** [comment]
> enable-http2

大佬，编译swoole 的时候怎么打开 configure 的配置项啊

**Comment by lin863187523** [comment]
hello ， 请问你们解决了没？ 我现在也遇到添加配置项的问题，请指教，谢谢！

**Comment by wxfjamdc** [comment]
我现在的方式是修改了
php/extensions/install.sh

在602 行附近
`
if [[ -z "${EXTENSIONS##*,swoole,*}" ]]; then
    echo "---------- Install swoole ----------"
    isPhpVersionGreaterOrEqual 7 0

    if [[ "$?" = "1" ]]; then

        mkdir /usr/src/php/ext/swoole
        tar -xf swoole-4.5.2.tgz --strip-components=1 -C /usr/src/php/ext/swoole
        docker-php-ext-configure swoole \
          --enable-http2   \
          --enable-mysqlnd \
          --enable-openssl \
          --enable-sockets
        docker-php-ext-install -j$(nproc) swoole
    else
        installExtensionFromTgz swoole-2.0.11
    fi
fi`

**Comment by mtgq** [comment]
`
# 安装 swoole
#COPY ./extensions/swoole-src-4.6.5.tar.gz  /usr/local/src/
#
#RUN \
#    docker-php-ext-install -j$(nproc) sockets bcmath pdo_mysql mysqli exif && \
#    docker-php-source extract && \
#    mkdir /usr/src/php/ext/swoole && \
#    cd /usr/local/src/ && \
#    tar xfz swoole-src-4.6.5.tar.gz --strip-components=1 -C /usr/src/php/ext/swoole && \
#    docker-php-ext-configure swoole \
#        --enable-http2   \
#        --enable-mysqlnd \
#        --enable-openssl \
#        --enable-sockets --enable-swoole-curl --enable-swoole-json && \
#    docker-php-ext-install -j$(nproc) swoole  && \
#    rm /usr/local/src/swoole-src-4.6.5.tar.gz
`

**Comment by mtgq** [comment]
``` 
# 安装 swoole
#COPY ./extensions/swoole-src-4.6.5.tar.gz  /usr/local/src/
#
#RUN \
#    docker-php-ext-install -j$(nproc) sockets bcmath pdo_mysql mysqli exif && \
#    docker-php-source extract && \
#    mkdir /usr/src/php/ext/swoole && \
#    cd /usr/local/src/ && \
#    tar xfz swoole-src-4.6.5.tar.gz --strip-components=1 -C /usr/src/php/ext/swoole && \
#    docker-php-ext-configure swoole \
#        --enable-http2   \
#        --enable-mysqlnd \
#        --enable-openssl \
#        --enable-sockets --enable-swoole-curl --enable-swoole-json && \
#    docker-php-ext-install -j$(nproc) swoole  && \
#    rm /usr/local/src/swoole-src-4.6.5.tar.gz
```

**Comment by ritaswc** [comment]
mark ，我去试试先
