### ISSUE TITLE
詢問容器怎麼做IP映射

### ISSUE THREAD

**Issue by uunmask2000** [yeszao/dnmp#352]
目前看到只有Nginx 只開 80 443,我要新增其他的要怎麼搞

**Comment by jingmian** [comment]
通过`nginx.conf`配置文件和`docker-composer.yml`中的`ports`参数一起配合

**Comment by xjimmy906** [comment]
docker-composer.yml
    ports:
      - "9503:9503"
      - "9502:9502"
