### ISSUE TITLE
Logstash 怎么使用？

### ISSUE THREAD

**Issue by shunhua** [yeszao/dnmp#353]
Logstash 怎么使用？

**Comment by sreio** [comment]
elk 有使用成功么？例如将logs目录下的日志在b里面查看？前几天我试了一下  容器都跑起来，发现不会用

**Comment by afu727** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by shunhua** [comment]
> 

你现在使用了吗？

**Comment by shunhua** [comment]
> elk 有使用成功么？例如将logs目录下的日志在b里面查看？前几天我试了一下 容器都跑起来，发现不会用

你现在使用了吗？filebeat  没有？

**Comment by sreio** [comment]
之前只尝试查询了几个容器的日志，项目产生的日志还没有尝试导入到es里，也并没有使用filebeat。

你是否尝试使用filebeat，并且成功导入项目日志或服务日志到es中？

**Comment by shunhua** [comment]
> 之前只尝试查询了几个容器的日志，项目产生的日志还没有尝试导入到es里，也并没有使用filebeat。
> 
> 你是否尝试使用filebeat，并且成功导入项目日志或服务日志到es中？

我没试呢 过一段要用

**Comment by shunhua** [comment]
> > 我没试呢 过一段要用
> 
> 可以共同交流一下👍🏻

嗯呢
