### ISSUE TITLE
redis挖矿病毒kdevtmpfsi

### ISSUE THREAD

**Issue by Latezly** [yeszao/dnmp#355]
![E@I)KE1LF5BF5}W%7{5%F0J](https://user-images.githubusercontent.com/17759624/105218147-b65b2200-5b4c-11eb-8598-30a884642d3f.png)
![J59$C`O7Q@ B_EB1)69DH3N](https://user-images.githubusercontent.com/17759624/105218395-00dc9e80-5b4d-11eb-930c-36c55dcf9271.png)
![P% 74WZ3}E0(EHYG$M H1M](https://user-images.githubusercontent.com/17759624/105218305-e4d8fd00-5b4c-11eb-90d1-f799f02405c9.png)
![C8V${T2~ OW1$)F XAYJ1JT](https://user-images.githubusercontent.com/17759624/105218957-c45d7280-5b4d-11eb-9734-4c490905bd5e.png)

https://learnku.com/articles/42323
随便搜了一下这种案例还是挺多的，虽然目前还不知道是怎么入侵的，不过看首先得把redis容器的默认的监听的端口或者ip改一改？

**Comment by September999999999** [comment]
不设置密码，还把端口暴露出去是这样的
