### ISSUE TITLE
mysql.cnf配置慢查询没生效

### ISSUE THREAD

**Issue by rockyzhuo** [yeszao/dnmp#357]
#配置my.cnf的配置文件：
long_query_time         = 1

通过命令查询 还是显示默认 10s
SHOW GLOBAL  VARIABLES LIKE 'long_query_time';

重新启动没生效，然后删除容器，重复up之后还是没有生效

**Comment by jingmian** [comment]
有重新进行 `build`试下吗

**Comment by yangjingchuang** [comment]
> 有重新进行 `build`试下吗

重新 build 是这样吗？？ docker-compose up --build 就行了对吧？

**Comment by simpleKalvin** [comment]
一样，我配置binlog 也没生效

**Comment by yeszao** [comment]
看看 mysql.cnf 文件这3行是不是都有：
```conf
slow_query_log
long_query_time         = 1
slow-query-log-file     = /var/log/mysql/mysql.slow.log
```
