### ISSUE TITLE
symfony 问题

### ISSUE THREAD

**Issue by nice-yu** [yeszao/dnmp#358]
将 symfony 放入到 /usr/bin 后, 执行 symfony 报错
env: can't execute 'bash': No such file or directory

Dockfile 添加，其余未修改
# Install symfony
RUN curl -o /usr/bin/symfony https://get.symfony.com/cli/installer \
    && chmod +x /usr/bin/symfony
ENV COMPOSER_HOME=/tmp/symfony

**Comment by jingmian** [comment]
后期我们会加上这个，你这样操作应该是会报错的
