### ISSUE TITLE
composer 依赖php环境，怎么才能使用composer

### ISSUE THREAD

**Issue by wukchao** [yeszao/dnmp#36]
composer 依赖php环境，怎么才能使用composer

**Comment by kleveralt** [comment]
宿主装php-cli去www目录局部安装composer就可以了

**Comment by enboo** [comment]
大侠，多打几个字嘛，我win10专业版，想在win10上装composer，如何关联到php容器里

**Comment by yeszao** [comment]
在 Linux 下使用方式：https://github.com/yeszao/dnmp/blob/master/README.md#6%E4%BD%BF%E7%94%A8composer
