### ISSUE TITLE
lets-encrypt 怎麼使用?

### ISSUE THREAD

**Issue by uunmask2000** [yeszao/dnmp#361]
想問一下
怎麼配置 lets-encrypt 
我安裝了
certbot
說配取不到NGIINX

**Comment by September999999999** [comment]
> 想問一下
> 怎麼配置 lets-encrypt
> 我安裝了
> certbot
> 說配取不到NGIINX

看看cerbot的具体用法，我用的是certbot certonly 这个参数

**Comment by uunmask2000** [comment]
> > 想问一下
> > 怎么配置lets-encrypt
> > 我安装了
> > certbot
> > 说配取不到NGIINX
> 
> 看看cerbot的具体用法，我用的是certbot certonly这个参数

OK
