### ISSUE TITLE
苹果m1芯片 的docker预览版3.1.0 上无法运行，nginx build报错

### ISSUE THREAD

**Issue by dwp73** [yeszao/dnmp#362]
clone好后，本机运行
`docker-compose up -d`

报错

`
Building with native build. Learn about native build in Compose here: https://docs.docker.com/go/compose-native-build/
Building nginx
[+] Building 2.6s (3/3) FINISHED
 => [internal] load build definition from Dockerfile                                                                         0.3s
 => => transferring dockerfile: 37B                                                                                          0.0s
 => [internal] load .dockerignore                                                                                            0.5s
 => => transferring context: 2B                                                                                              0.0s
 => ERROR [internal] load metadata for docker.io/library/1.19.1-alpine:latest                                                1.9s
------
 > [internal] load metadata for docker.io/library/1.19.1-alpine:latest:
------
failed to solve with frontend dockerfile.v0: failed to create LLB definition: unexpected status code [manifests latest]: 403 Forbidden
ERROR: Service 'nginx' failed to build
`

无法继续下一步

**Comment by Paladinhanxiao** [comment]
怎么解决的啊？我也遇到同样的问题

**Comment by ritaswc** [comment]
没有发现此问题，倒是mysql需要更换一个镜像
从mysql换成mysql/mysql-server

**Comment by jiayouzl** [comment]
> 没有发现此问题，倒是mysql需要更换一个镜像
> 
> 从mysql换成mysql/mysql-server

＋platform: linux/x86_64也可以的。

**Comment by ritaswc** [comment]
> 

我已经提交过pr，合并过去了，支持m1(arm64)了
