### ISSUE TITLE
对于比较冷们的扩展如何安装呢

### ISSUE THREAD

**Issue by jefferyjob** [yeszao/dnmp#365]
我们自己公司用的 ffmpeg 这个扩展，然后我去 pecl.php.net 这个扩展网站没找到，咋搞嘞

**Comment by jingmian** [comment]
这个后期我们也打算添加上去的

**Comment by jefferyjob** [comment]
> 这个后期我们也打算添加上去的

可以文档先写一下，对于自定义扩展如何安装。因为还有一些其他的冷门扩展，对于有这方面需求的开发者来说是好事

**Comment by jingmian** [comment]
这个比较难的,每个冷门扩展缺少的文件不同，无法写个文档通用自定义扩展安装

**Comment by jefferyjob** [comment]
就是举个例子嘛。比如基于ip连接redis、基于服务使用的ffmpeg。当然无法给出统一的标准，我也明白，有个例子的话，大家可以根据自己的需求然后进行不同方式的安装

**Comment by yangjingchuang** [comment]
> pecl.php.net

好像我看是用 zip 方式安装的

**Comment by yii-cloud** [comment]
与其说是冷门扩展更不如说php的扩展如何安装？或者说在docker中如何安装
1.下载源码包，放到对应的目录配置，参考install.sh即可
2.不同发行版本的类unix操作命令不太相同，可以执行php编译三部曲，任何一套环境都是适用的。即：phpize 、configure、make and make install
3.pecl安装
4.自己写c扩展基本是采用方式2搞定了
