### ISSUE TITLE
mysqld: File '/var/log/dnmp/mysql.slow.log' not found (Errcode: 13 - Permission denied)

### ISSUE THREAD

**Issue by piaoyunsoft** [yeszao/dnmp#37]
mysqld: File '/var/log/dnmp/mysql.slow.log' not found (Errcode: 13 - Permission denied)
手工进去 chmod 777 /var/log/dnmp/mysql.slow.log 才可以~ 怎么自动化呢？

**Comment by yeszao** [comment]
那就把mysql.slow.log放到MySQL data同一目录，这是mysql用户组所属的目录。
