### ISSUE TITLE
M1 macbook docker 预览版拉mysql  ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by Fawkes-hub** [yeszao/dnmp#370]
在M1芯片的docker预览版中，无法拉取MySQL镜像
提示错误
`Pulling mysql (mysql:8.0.13)...
8.0.13: Pulling from library/mysql
8.0.13: Pulling from library/mysql
ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries`

**Comment by Fawkes-hub** [comment]
找到了解决办法
修改mysql的镜像源
在docker-compose.yml文件中改为：
`  mysql:
    image: mysql/mysql-server:${MYSQL5_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "$TZ"`

**Comment by xingyu-Lu** [comment]
@Fawkes-hub 老铁，m1上用的顺畅嘛

**Comment by Fawkes-hub** [comment]
> @ Fawkes-hub老铁，m1上用的顺畅嘛

@xingyu-Lu MySQL暂时不支持，其他的还好。docker预览版还有些小问题，不过官方在积极修复应该很快就能好了。常规的环境都能装。我8G用起来内存经常爆满飚红，很焦虑。最好是直接上16G
