### ISSUE TITLE
nginx user uid的一点疑问

### ISSUE THREAD

**Issue by lhuang001** [yeszao/dnmp#371]
感谢您的工作，我对dnmp镜像有如下两点疑问：
1.dnmp使用的是nginx：alpine镜像，该镜像中nginx程序的默认用户是nginx。通过如图命令可知nginx用户的uid是101，和官方介绍一致。但是php-fpm镜像使用的是www-data用户，且uid为1000.这两个镜像user的uid不一致，不会导致权限问题吗？
![image](https://user-images.githubusercontent.com/21240907/111021145-4f980d80-8405-11eb-943b-1d65174eb9a4.png)

2.我不太清楚dnmp/services/nginx/fastcgi_params这个文件的作用，在nginx.conf里并没有看到包含该文件，还请您解释一下fastcgi是如何起作用的。

**Comment by worldxyj** [comment]
把nginx日志目录设置为nginx用户和组，把项目日志、uploads等目录设置为www-data用户和分组，它们需要写入权限的目录不是一个，不会有权限问题
