### ISSUE TITLE
workman or swoole

### ISSUE THREAD

**Issue by uunmask2000** [yeszao/dnmp#375]
詢問一下
怎麼啟 WebSocket 的服務映射進去
我用0.0.0.0.0:{port}
都沒辦法握手上
用node js 啟 WebSocket 卻可以
不清楚 容器要怎麼配置

**Comment by jingmian** [comment]
ports:
      - "9501:9501"

例子

**Comment by uunmask2000** [comment]
> ```
> ports:
>   - "9501:9501"
> ```
> 
> 例子

最後我在Nginx 那邊 代理 到虛擬IP上
port 不能直接 port : port

**Comment by Janmas-php** [comment]
> > ```
> > ports:
> >   - "9501:9501"
> > ```
> > 
> > 
> > 例子
> 
> 最後我在Nginx 那邊 代理 到虛擬IP上
> port 不能直接 port : port

请问你是怎么实现的？

**Comment by uunmask2000** [comment]
修改env，容器 up 那边，刷新容器.

**Comment by JanmasCromwell** [comment]
> 修改env，容器 up 那边，刷新容器.

Emmm.我尝试了下没有搞定这个问题。可以给我看下你的是怎么搞定的么？
