### ISSUE TITLE
swoole如何升级?

### ISSUE THREAD

**Issue by moon-zhangyue** [yeszao/dnmp#376]
现在版本是4.4.2  麻烦问一下,如何升级呢?pecl upgrade swoole  会报错

**Comment by yymmhh** [comment]
重新构建容器

参照 
` services/php/extensions/install.sh`  590行
 下载swoole-src 替换

**Comment by nio-ares** [comment]
你好，请问已经成功实现了吗?使用快速安装拓展swoole版本是 4.5.2，请问如何升级swoole 到4.6.7?

**Comment by yymmhh** [comment]
https://github.com/swoole/swoole-src/releases/tag/v4.6.7
 下载 Source code (tar.gz) 压缩包  下载完成重名为 swoole-4.6.7.tgz 
放到 `dnmp/services/php/extensions` 目录下

`dnmp/services/php/extensions/install.sh`  607行 修改为

`installExtensionFromTgz swoole-4.6.7` 

![image](https://user-images.githubusercontent.com/34824081/122840383-92368380-d32c-11eb-96b2-4d717d464373.png)

**Comment by nio-ares** [comment]
这样替换之后，还是4.5.2的版本

**Comment by nio-ares** [comment]
> https://github.com/swoole/swoole-src/releases/tag/v4.6.7
> 下载 Source code (tar.gz) 压缩包 下载完成重名为 swoole-4.6.7.tgz
> 放到 `dnmp/services/php/extensions` 目录下
> 
> `dnmp/services/php/extensions/install.sh` 607行 修改为
> 
> `installExtensionFromTgz swoole-4.6.7`
> 
> ![image](https://user-images.githubusercontent.com/34824081/122840383-92368380-d32c-11eb-96b2-4d717d464373.png)
这样替换之后，还是4.5.2的版本

**Comment by nio-ares** [comment]
> https://github.com/swoole/swoole-src/releases/tag/v4.6.7
> 下载 Source code (tar.gz) 压缩包 下载完成重名为 swoole-4.6.7.tgz
> 放到 `dnmp/services/php/extensions` 目录下
> 
> `dnmp/services/php/extensions/install.sh` 607行 修改为
> 
> `installExtensionFromTgz swoole-4.6.7`
> 
> ![image](https://user-images.githubusercontent.com/34824081/122840383-92368380-d32c-11eb-96b2-4d717d464373.png)
替换文件名之后，build的了一次php,重新构建，版本还是没变，是怎么回事呢

**Comment by nio-ares** [comment]
> https://github.com/swoole/swoole-src/releases/tag/v4.6.7
> 下载 Source code (tar.gz) 压缩包 下载完成重名为 swoole-4.6.7.tgz
> 放到 `dnmp/services/php/extensions` 目录下
> 
> `dnmp/services/php/extensions/install.sh` 607行 修改为
> 
> `installExtensionFromTgz swoole-4.6.7`
> 
> ![image](https://user-images.githubusercontent.com/34824081/122840383-92368380-d32c-11eb-96b2-4d717d464373.png)

可以了，谢谢大神，我给重新执行了一遍 快捷安装拓展，就给我自己下载的4.6.7版本的包，成功安装上了。
