### ISSUE TITLE
windows 10 Docker Desktop 环境下内网延迟 5-10s

### ISSUE THREAD

**Issue by lancemach** [yeszao/dnmp#377]
windows 10 Docker Desktop 环境下，接口响应5-10s多，网上说是DNS问题，电脑和软件都设置了DNS还是没有解决，但是在云主机中部署了好几台项目，暂还没有出现这种问题

**Comment by cnbattle** [comment]
目测wsl2磁盘io问题，docker desktop关闭wsl2看看

**Comment by lancemach** [comment]
收到，谢谢指点
