### ISSUE TITLE
如何增加个 php5.5 , 直接修改php5.4的 版本号为5.5  好像失败了

### ISSUE THREAD

**Issue by fzqk9** [yeszao/dnmp#378]
如何增加个 php5.5 , 直接修改php5.4的 版本号为5.5  好像失败了

**Comment by yymmhh** [comment]
建议对docker-compose.yml文件中 php54  进行修改

**Comment by jingmian** [comment]
不能直接修改5.4的，因为docker镜像上支持php 5.4版本很少，要找到对应的才行
