### ISSUE TITLE
' postgresql-libs' is not a valid world dependency

### ISSUE THREAD

**Issue by Caoxl-C** [yeszao/dnmp#381]
安装swoole扩展报错:
FAILED TO LIST THE WHOLE PACKAGE LIST FOR
 postgresql-libs 

COMMAND OUTPUT:
ERROR: ' postgresql-libs' is not a valid world dependency, format is name(@tag)([<>~=]version)

ERROR: apk failed

**Comment by jingmian** [comment]
需要手动安装 postgresql-libs 扩展后，才安装swoole
https://pkgs.alpinelinux.org/package/edge/main/x86/postgresql-libs
