### ISSUE TITLE
PHP 8.0.5 解决方案

### ISSUE THREAD

**Issue by sreio** [yeszao/dnmp#382]
1. 修改.env 中  PHP_VERSION=8.0.5
2. 如果已构建PHP容器，请先暂停 `docker-compose stop php` 删除容器 `docker-compose rm php`
3. 构建PHP容器并后台运行 `docker-compose up -d php`

Ps：修改 PHP_VERSION 为 https://www.php.net/ 版本即可

**Comment by whcoding** [comment]
少了一步 build php 镜像
