### ISSUE TITLE
在docker宿主机执行 php artisan migrate 报错

### ISSUE THREAD

**Issue by whcoding** [yeszao/dnmp#388]
- php版本: 7.4
- docker版本 20.10.6
- laravel版本 8.38.0

- 在php容器内部执行没有问题

报错如下:
![image](https://user-images.githubusercontent.com/25763789/118257191-ebff8e80-b4e0-11eb-85de-f38f1955b50f.png)

**Comment by tlerbao** [comment]
是的，确实存在这个问题，需要到容器里执行php think migrate 类似这种操作数据库的命令行

**Comment by tlerbao** [comment]
@yeszao 是修复了吗，还是姿势不对，close 是因为什么呢？
