### ISSUE TITLE
run docker-compose -f docker-compose56.yml up and throw a error

### ISSUE THREAD

**Issue by yuzhiyuan** [yeszao/dnmp#39]
when I run docker-compose -f docker-compose56.yml up in the dnmp dir with mac os10.13 or centos 7 ,it throws a error ,like this:

The following packages have unmet dependencies:
 libfreetype6-dev : Depends: zlib1g-dev but it is not going to be installed or
                             libz-dev
 libpng12-dev : Depends: zlib1g-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
ERROR: Service 'php' failed to build: The command '/bin/sh -c apt-get update     && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev     && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/     && docker-php-ext-install gd     && :    && apt-get install -y libicu-dev     && docker-php-ext-install intl     && :    && apt-get install -y libxml2-dev     && apt-get install -y libxslt-dev     && docker-php-ext-install soap     && docker-php-ext-install xsl     && docker-php-ext-install xmlrpc     && docker-php-ext-install wddx     && :    && apt-get install -y libbz2-dev     && docker-php-ext-install bz2     && :    && docker-php-ext-install zip     && docker-php-ext-install pcntl     && docker-php-ext-install pdo_mysql     && docker-php-ext-install mysqli     && docker-php-ext-install mbstring     && docker-php-ext-install exif     && docker-php-ext-install bcmath     && docker-php-ext-install calendar     && docker-php-ext-install sockets     && docker-php-ext-install gettext     && docker-php-ext-install shmop     && docker-php-ext-install sysvmsg     && docker-php-ext-install sysvsem     && docker-php-ext-install sysvshm     && docker-php-ext-install opcache' returned a non-zero code: 100

**Comment by yeluoqiuzhi** [comment]
对，连官方的源都已经没用了。。
