### ISSUE TITLE
php8 报错

### ISSUE THREAD

**Issue by littlemolh** [yeszao/dnmp#394]
#9 227.7 WARNING: Ignoring https://mirrors.aliyun.com/alpine/v3.13/main: No such file or directory
#9 227.7 WARNING: Ignoring https://mirrors.aliyun.com/alpine/v3.13/community: No such file or directory
#9 227.7 ERROR: No such package: .build-deps

**Comment by littlemolh** [comment]
> [ 3/17] RUN apk update && apk add nginx &&     apk add m4 autoconf make gcc g++ linux-headers &&     apk del m4 autoconf make gcc g++ linux-headers:
#7 0.202 fetch https://mirrors.aliyun.com/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
#7 5.208 fetch https://mirrors.aliyun.com/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
#7 5.208 ERROR: https://mirrors.aliyun.com/alpine/v3.12/main/: temporary error (try again later)
#7 5.208 WARNING: Ignoring https://mirrors.aliyun.com/alpine/v3.12/main/: No such file or directory
#7 10.21 ERROR: https://mirrors.aliyun.com/alpine/v3.12/community/: temporary error (try again later)
#7 10.21 WARNING: Ignoring https://mirrors.aliyun.com/alpine/v3.12/community/: No such file or directory
#7 10.21 2 errors; 45 distinct packages available

**Comment by yeszao** [comment]
是网络问题，修改 .env 文件里面的 CONTAINER_PACKAGE_URL 变量，删除值，让其为空，或者换一个，再重新启动。
