### ISSUE TITLE
请问php 版本怎么切换成7.2呢

### ISSUE THREAD

**Issue by nio-ares** [yeszao/dnmp#396]
请问php 版本怎么切换成7.2呢

**Comment by Ya-hui** [comment]
第一步：修改.env文件
#
# PHP7.2
#
PHP72_VERSION=7.2
PHP72_PHP_CONF_FILE=./services/php72/php.ini
PHP72_FPM_CONF_FILE=./services/php72/php-fpm.conf
PHP72_LOG_DIR=./logs/php
PHP72_EXTENSIONS=pdo_mysql,zip,pcntl,mysqli,mbstring,exif,gd,bcmath,sockets,curl,opcache,redis,memcached,swoole,mongodb,yaml,odbc,bz2,imagick

第二步：修改docker-compose.yml文件

  php72:
    build:
      context: ./services/php
      args:
        PHP_VERSION: php:${PHP72_VERSION}-fpm-alpine
        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
        PHP_EXTENSIONS: ${PHP72_EXTENSIONS}
        TZ: "$TZ"
    container_name: php72
    expose:
      - 9501
    extra_hosts:
      - "www.site1.com:172.17.0.1"
    volumes:
      - ${SOURCE_DIR}:/www/:rw
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
      - ${PHP72_LOG_DIR}:/var/log/php
      - ${DATA_DIR}/composer:/tmp/composer
    restart: always
    cap_add:
      - SYS_PTRACE
    networks:
      - default

第三步：docker-compose build php72

第四步：docker start php72

不知道为什么 php72 启动后会把默认的php 替换掉，这里重启 docker start php ，共存成功

fastcgi_pass   php72:9000;
