### ISSUE TITLE
PHP8安装redis swoole扩展问题

### ISSUE THREAD

**Issue by HFLeon** [yeszao/dnmp#399]
方法一：在docker-compose up之前.env配置了
PHP_VERSION=8.0.7
PHP_EXTENSIONS=redis,swoole
结果这俩扩展没装上

方法二：docker exec -it php /bin/sh
install-php-extensions redis 
install-php-extensions swoole
均失败：You are using an unsupported method to get install-php-extensions!

**Comment by jingmian** [comment]
方法一中你是否有重新build

**Comment by HFLeon** [comment]
是的，docker-compose build php之后还是没有

**Comment by lidemo000** [comment]
大佬, 请问您解决了方案二的问题了么? 是如何解决的, 方便告知下么

**Comment by Jonse-Larkin** [comment]
同样遇到这个问题，redis扩展无法安装
