### ISSUE TITLE
希望能出一个支持java环境的dockerfile

### ISSUE THREAD

**Issue by hudan2714** [yeszao/dnmp#4]
很感谢作者的提供。。。最近也在一直学习和研究dockerfile。作者的事例能用在正式项目的生产环境吗？我们有一些项目，是用java开发的。。也需要一个这个的环境。。。望作者能给好的建议。。

**Comment by yeszao** [comment]
我的博客是已经在用了的，https://www.awaimai.com
可以参考源码，改成你们需要的环境，然后根据生产环境配置。
主要在服务器的配置，docker不需要改太多的

**Comment by hudan2714** [comment]
那dockerfile中的php-fpm是不是得改成支持tomcat呢？还有就是nginx安装的扩展包，也是不是需要改变？

**Comment by yeszao** [comment]
@hudan2714 嗯，这是必须的，要改成Java的环境
