### ISSUE TITLE
PHP不能连接REDIS

### ISSUE THREAD

**Issue by echobar** [yeszao/dnmp#40]
貌似PHP没有安装REDIS扩展？在php.ini和phpinfo()里没有找到有关redis.so的扩展配置，php也无法连接redis，请教了

**Comment by lzqaz** [comment]
同问

**Comment by yeszao** [comment]
这个应该是PHP7 dockerfile更新后担心安装失败问题，才删了的（现在已经重新加到master分支），可以手动在dockerfile里面加上：
```
RUN pecl install redis-3.1.4 \
    && docker-php-ext-enable redis
```
也可以重新pull一份。
