### ISSUE TITLE
php7.3 zip 扩展的问题

### ISSUE THREAD

**Issue by kayw-geek** [yeszao/dnmp#400]
安装使用修改 `.env` 文件方式 之后重新执行 `build  -> up  ->php -m` 发现只有zlib 没有 zip ,当我执行 `docer exec -it php /bin/sh -> php -m` 却发现了有 `zip` 和 `zlib `,请问是什么问题导致的 容器内的php 和外的 不一致呢

**Comment by jingmian** [comment]
以容器内的为准,而且你可以在宿主机上通过 `which php`查看这个命令属于哪个

**Comment by 1229064537** [comment]
docker-compose restart php  重启php就可以了
