### ISSUE TITLE
docker-compose build mongo 

### ISSUE THREAD

**Issue by saiye** [yeszao/dnmp#401]
> docker-compose build mongodb 
提示
mongodb uses an image, skipping
如何解决

```text
  mongodb:
   image: mongo:${MONGODB_VERSION}
   container_name: mongodb
   environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
      TZ: "$TZ"
   volumes:
     - ${DATA_DIR}/mongo:/data/db:rw
     - ${DATA_DIR}/mongo_key:/mongo:rw
   ports:
     - "${MONGODB_HOST_PORT}:27017"
   networks:
     - default
   command:
     --auth 
```

```text
.env
MONGODB_VERSION=4.4
MONGODB_HOST_PORT=27017
MONGODB_INITDB_ROOT_USERNAME=root
MONGODB_INITDB_ROOT_PASSWORD=123456
```

```text
命令行执行
docker images|grep mongo
mongo                                                                4.4                                                     0e120e3fce9a   4 days ago      449MB

```

**Comment by saiye** [comment]
mongodb:
   image: mongo:${MONGODB_VERSION}
   container_name: mongodb
   environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGODB_INITDB_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGODB_INITDB_ROOT_PASSWORD}"
      TZ: "$TZ"
   volumes:
     - ${DATA_DIR}/mongo:/data/db:rw
     - ${DATA_DIR}/mongo_key:/mongo:rw
   ports:
     - "${MONGODB_HOST_PORT}:27017"
   networks:
     - default
   command:
     --auth

**Comment by letture** [comment]
docker-compose rm mongodb
