### ISSUE TITLE
请问如何修改mysql 的默认链接密码呢？

### ISSUE THREAD

**Issue by csj1024** [yeszao/dnmp#407]

**Comment by jingmian** [comment]
.env文件里面修改

**Comment by yeszao** [comment]
两种情况：
1. 如果是刚 clone 仓库，则如 @jingmian 所说，修改 .env 文件，再启动容器；
2. 如果是 mysql 已经启动过了，那需要通过 mysql 客户端连接 mysql 服务器，再通过命令来修改密码。
