### ISSUE TITLE
debian9内的PHP如何安装xdebug扩展？

### ISSUE THREAD

**Issue by admininfon** [yeszao/dnmp#41]
我没有使用过Debian系统，而且对docker安装xdebug扩展命令不了解，所以没办法在PHP的dockerfile内编写xdebug安装指令，需求帮助。

**Comment by yeszao** [comment]
在dockerfile里面加上这个命令（默认其实也有的）：
```
pecl install xdebug-2.4.1 \
    && docker-php-ext-enable xdebug
```
这是从pecl.php.net网站下载扩展包安装的，但是，pecl.php.net偶尔会访问不了（可能被墙），所以pecl命令安装失败的话，可以自己下载扩展包安装。

xdebug扩展下载地址：https://pecl.php.net/package/xdebug

dockerfile中的命令请看php/php54/Dockerfile最后7行对zendopcache的安装，仿照就可以了。
