### ISSUE TITLE
无法再windows下面使用

### ISSUE THREAD

**Issue by banditsmile** [yeszao/dnmp#413]
`一次配置，Windows、Linux、MacOs皆可用`

这个怕是没有验证过吧
首先，在windows下面你怎么操作下面的命令？
`
3.如果不是root用户，还需将当前用户加入docker用户组：
$ sudo gpasswd -a ${USER} docker
`

其次，在container里面想要改变挂载目录的所有者是无效的操作

**Comment by yeszao** [comment]
这个命令只在Linux系统中才需要，我们已经更新了 README，感谢
