### ISSUE TITLE
MAC BOOK PRO 上面安装phalcon扩展不成功，卡在安装途中.md

### ISSUE THREAD

**Issue by itknight** [yeszao/dnmp#416]
![image](https://user-images.githubusercontent.com/7972442/130310481-bc3960ee-39ce-4eed-9cf3-378b23774f3f.png)
根据README.md描述，在`.env`文件中的`90`行加入对psr和phalcon的扩展。
```
PHP_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache,zip,psr,phalcon
```
执行
```
docker-compose build php
```
会自动安装psr和phalcon其中，psr安装是没有问题的，phalcon看记录会自行安装 v4.1.2,但是会一直停留在这个界面上面。卡顿时间很久。不得不 `ctrl + c`暂停，这个原因不知道是什么。

我另外尝试了另外一种方案。
进入php的环境中,执行如下内容
```
docker exec -it php /bin/sh
install-php-extensions phalcon
```
![image](https://user-images.githubusercontent.com/7972442/130310737-232f32f4-6068-4b1b-9ee6-499298386411.png)

感觉执行效果是一样的。也会卡在这样几个界面上
有过1次，它安装成功了，也就只有1次，是通过第二种方式，不知道这种情况出现的原因是什么。
php版本为 7.4
========如下为我的电脑环境=====

![image](https://user-images.githubusercontent.com/7972442/130310642-9aff58ca-2b0b-482a-986d-d78c19a6ae77.png)

Docker环境
```
Docker version 20.10.5, build 55c4c88
```

**Comment by itknight** [comment]
hope for reply ,thanks

**Comment by itknight** [comment]
如果能告诉我一个另一个可以安装phalcon 4的办法也可以
Only if there is a way to install Phalcon 4 (o^^o)

**Comment by jingmian** [comment]
你在php的`Dockerfile`文件中尝试添加一下构建命令试下
```sh
ARG PSR_VERSION=1.1.0
ARG PHALCON_VERSION=4.1.2
ARG PHALCON_EXT_PATH=php7/64bits

RUN set -xe && \
        # Download PSR, see https://github.com/jbboehr/php-psr
        curl -LO https://github.com/jbboehr/php-psr/archive/v${PSR_VERSION}.tar.gz && \
        tar xzf ${PWD}/v${PSR_VERSION}.tar.gz && \
        # Download Phalcon
        curl -LO https://github.com/phalcon/cphalcon/archive/v${PHALCON_VERSION}.tar.gz && \
        tar xzf ${PWD}/v${PHALCON_VERSION}.tar.gz && \
        docker-php-ext-install -j $(getconf _NPROCESSORS_ONLN) \
            ${PWD}/php-psr-${PSR_VERSION} \
            ${PWD}/cphalcon-${PHALCON_VERSION}/build/${PHALCON_EXT_PATH} \
        && \
        # Remove all temp files
        rm -r \
            ${PWD}/v${PSR_VERSION}.tar.gz \
            ${PWD}/php-psr-${PSR_VERSION} \
            ${PWD}/v${PHALCON_VERSION}.tar.gz \
            ${PWD}/cphalcon-${PHALCON_VERSION} \
        && \
        php -m
```

**Comment by itknight** [comment]
> 你在php的`Dockerfile`文件中尝试添加一下构建命令试下
> 
> ```shell
> ARG PSR_VERSION=1.1.0
> ARG PHALCON_VERSION=4.1.2
> ARG PHALCON_EXT_PATH=php7/64bits
> 
> RUN set -xe && \
>         # Download PSR, see https://github.com/jbboehr/php-psr
>         curl -LO https://github.com/jbboehr/php-psr/archive/v${PSR_VERSION}.tar.gz && \
>         tar xzf ${PWD}/v${PSR_VERSION}.tar.gz && \
>         # Download Phalcon
>         curl -LO https://github.com/phalcon/cphalcon/archive/v${PHALCON_VERSION}.tar.gz && \
>         tar xzf ${PWD}/v${PHALCON_VERSION}.tar.gz && \
>         docker-php-ext-install -j $(getconf _NPROCESSORS_ONLN) \
>             ${PWD}/php-psr-${PSR_VERSION} \
>             ${PWD}/cphalcon-${PHALCON_VERSION}/build/${PHALCON_EXT_PATH} \
>         && \
>         # Remove all temp files
>         rm -r \
>             ${PWD}/v${PSR_VERSION}.tar.gz \
>             ${PWD}/php-psr-${PSR_VERSION} \
>             ${PWD}/v${PHALCON_VERSION}.tar.gz \
>             ${PWD}/cphalcon-${PHALCON_VERSION} \
>         && \
>         php -m
> ```
![image](https://user-images.githubusercontent.com/7972442/130316390-fa95dfa8-6107-4770-80cd-5f52874e87ed.png)
如上图所示，我把代码放到了`Dockerfile`的第`46`行，执行`docker-compose build php`的结果如下图：
![image](https://user-images.githubusercontent.com/7972442/130316344-0fa55c24-3de2-4f1c-93d1-55a029143194.png)
从代码上来看，似乎有些相似。

**Comment by jingmian** [comment]
你尝试`php 7.2.9`这个版本构建一下试试，看看是不是版本的问题

**Comment by itknight** [comment]
> 你尝试`php 7.2.9`这个版本构建一下试试，看看是不是版本的问题
![image](https://user-images.githubusercontent.com/7972442/130317093-6f31fece-fb59-4c5d-9b7e-7ae1e6bc5341.png)

我多尝试了几次，最后可以构建成功了，应该就是前面加了那句话的原因。十分感谢！/抱拳 衷心希望在未来的版本中，phalcon的安装可以更方便些，这个issue可以关闭了。

**Comment by jingmian** [comment]
前面加了那句话的原因，具体是哪里的，好像我也无太注意到
