### ISSUE TITLE
nginx 最新版报错

### ISSUE THREAD

**Issue by penglzy** [yeszao/dnmp#419]
/docker-entrypoint.sh: Configuration complete; ready for start up

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist

/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh

/docker-entrypoint.sh: Configuration complete; ready for start up

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration

/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/

/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh

10-listen-on-ipv6-by-default.sh: error: /etc/nginx/conf.d/default.conf is not a file or does not exist

**Comment by penglzy** [comment]
的确没有这个目录/etc/nginx/conf.d

**Comment by jingmian** [comment]
你貌似没有拉去最新代码进行构建,因为` /etc/nginx/conf.d/default.conf`,这个我们没有指定过

**Comment by leeeeeekai** [comment]
最新拉取的代码，构建的时候还是会报错： error: /etc/nginx/conf.d/default.conf is not a file or does not exist
截图：
![image](https://github.com/yeszao/dnmp/assets/49102519/a04c1191-3620-4224-8e4d-b9e3c64c6882)
