### ISSUE TITLE
当前（180724）master版本里php72有问题

### ISSUE THREAD

**Issue by ComeZC** [yeszao/dnmp#42]
1. Dockerfile中安装的xdebug版本是2.4.1，执行中报错显示该版本最高只支持php7.1
2. 使用的aliyun的源有问题，某个依赖的包的md5检测报错，导致中断; 换回163的就可以了

**Comment by king19800105** [comment]
我也遇到了安装xdebug错误的问题，php7.2版本不支持

**Comment by king19800105** [comment]
最新版的安装完成。踩了3个坑。
1. xdebug版本，需要替换成2.6.0
2. aliyun要换，百度找了个最新的aliyun的源，搞定。
3. memcached扩展不支持，需要替换成3.0.4

**Comment by yeszao** [comment]
感谢反馈，php7版本已经改成从源码安装了，pecl方式容易因为网络原因安装不成功。
