### ISSUE TITLE
nginx 运行报错了，一直重启 

### ISSUE THREAD

**Issue by wuqrmm** [yeszao/dnmp#421]
nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/localhost.conf:30

请指教

**Comment by jingmian** [comment]
你应该单独运行`nginx`容器,或者是启动`php`的时候没有指定`container_name: php`吧

**Comment by wuqrmm** [comment]
谢谢回复。没有单独运行，只是改了端口和服务名，因为和再跑的有冲突。而且只跑了php/nginx/mysql这三个服务。下面是报错信息：
2021/08/24 11:18:07 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/localhost.conf:30
另外，我实在外网的电脑运行的，不知道有没有关系！请指教

**Comment by jingmian** [comment]
在`docker-composer.yml`应该没有一个服务名字叫`php`的,你需要对应一个才可以

**Comment by Pearlulu** [comment]
你是不是装的php8.0，网站配置文件改成fastcgi_pass   php80:9000;
