### ISSUE TITLE
在supervistor容器中怎么执行PHP命令

### ISSUE THREAD

**Issue by yanghuanfirst** [yeszao/dnmp#423]
比如我想在supervistor容器配置一个 php -m,怎么搞呢？谢谢

**Comment by yymmhh** [comment]
https://github.com/yeszao/dnmp/issues/335

**Comment by yanghuanfirst** [comment]
> #335

多谢，但是我想让supervisor单独一个容器，我看很多人说，直接挂载/var/run/docker.sock和/usr/bin/docker到容器就可以直接在容器里面执行宿主机的docker命令了，但是我试过了，却不行。。。。

**Comment by ritaswc** [comment]
说一下我的思路，在 php:7.4.22-fpm-alpine 容器中 安装supervisord
如果你需要fpm 则开启对fpm的监听。我贴一下相关内容


Dockerfile
```shell
apk add supervisor
```

supervisord-fpm.ini
```
[program:php-fpm]
command = /usr/local/sbin/php-fpm
directory = /www
user = root
autorestart = true
autostart = true
redirect_stderr = true
stdout_logfile = /var/log/php/php-fpm.log
stdout_logfile_maxbytes = 10MB
stdout_logfile_backups = 10
```

反正在容器内，fpm用root启动省事，不会出现文件权限问题

**Comment by yanghuanfirst** [comment]
> 说一下我的思路，在 php:7.4.22-fpm-alpine 容器中 安装supervisord 如果你需要fpm 则开启对fpm的监听。我贴一下相关内容
> 
> Dockerfile
> 
> ```shell
> apk add supervisor
> ```
> 
> supervisord-fpm.ini
> 
> ```
> [program:php-fpm]
> command = /usr/local/sbin/php-fpm
> directory = /www
> user = root
> autorestart = true
> autostart = true
> redirect_stderr = true
> stdout_logfile = /var/log/php/php-fpm.log
> stdout_logfile_maxbytes = 10MB
> stdout_logfile_backups = 10
> ```
> 
> 反正在容器内，fpm用root启动省事，不会出现文件权限问题

哦，好的，多谢你的思路。但是我想让supervistor单独一个容器，我现在是直接挂载/var/run/docker.sock和/usr/bin/docker到容器中的。
