### ISSUE TITLE
使用 docker-php-ext-config | install 安装生成 so 文件后,并没有成功开启

### ISSUE THREAD

**Issue by ayuayue** [yeszao/dnmp#424]
是 oci8 和 pdo_oci ,使用  docker-php-ext-config | install 命令后生成 so 扩展文件, 并且生成了 ini 配置文件.但是 php -m
显示没有  php --ri oci8 也是一样.
另外用同一个版本的 php 编译好的,直接放到 extension 目录中,修改配置文件,同样不生效

环境 php5.6.40
使用了 docker-php-ext-enable 并重启了 php 的docker镜象,一样无法加载手动编译 | 加入的扩展

**Comment by ayuayue** [comment]
已经解决了,有些动态库并没有链接到,但是并没有提示出来,,一般的php扩展如果有问题,是在输出配置或扩展的时候有提示的,这个要用 ldd 来看 so 库文件.
但是又出现了新的问题,就是 nginx php oracle 在三个不同的容器中,使用 pdo_oci的方式去链接获取数据,中文都变成了 ?
进入容器后改 NSL_LANG 可以将cli的中文正常,但是 fpm 还是不行,改了fpm-conf文件也不行, 使用 dbeaver 这种工具查询却可以返回正确的数据, 是 pdo_oci 的问题吗,还是 alpine 的语言设置问题,弄了两天没有找到解决方案

**Comment by ritaswc** [comment]
新问题  新开一个issue，礼貌先行
