### ISSUE TITLE
phalcon 无法安装 问题

### ISSUE THREAD

**Issue by 11373450** [yeszao/dnmp#425]
https://github.com/yeszao/dnmp/issues/416 <br>
跟上面的问题一致。请问下如何解决？

**Comment by ljs1201** [comment]
你好，想问下你安装成功了吗，我是7.4.27也安装不成功，如果你装成功了，能否告知一下怎么操作，谢谢

**Comment by siyue1314** [comment]
在php容器 apk --update add --no-cache --virtual .build-deps autoconf g++ libtool make curl-dev gettext-dev linux-headers
 再执行  pecl install phalcon
