### ISSUE TITLE
nginx默认配置可以有点问题

### ISSUE THREAD

**Issue by phpluo** [yeszao/dnmp#427]
默认配置
```nginx
location ~ \.php$ {
        fastcgi_pass   php:9000;
        include        fastcgi-php.conf;
        include        fastcgi_params;
    }
```
我参考[LNMP](https://github.com/licess/lnmp/blob/master/conf/enable-php7.1.conf)的配置
```nginx
location ~ [^/]\.php(/|$) {
        fastcgi_pass   php:9000;
        include        fastcgi-php.conf;
        include        fastcgi_params;
        fastcgi_param  PHP_VALUE "auto_prepend_file=/www/php/xhgui-branch/external/header.php";
    }
```
就是正则匹配的问题
默认的规则 类似fastadmin这样的随机后台文件就有问题

![2021-10-07_22-15](https://user-images.githubusercontent.com/15026737/136404311-e8874c2c-a165-4912-b263-20216fbc22d4.png)
![2021-10-07_22-23](https://user-images.githubusercontent.com/15026737/136404359-2f92424b-162d-4205-93bb-07fa46fcf19e.png)
![2021-10-07_22-26](https://user-images.githubusercontent.com/15026737/136404965-8c953620-423e-4d52-8cdc-cb84883775aa.png)

**Comment by jingmian** [comment]
那是因为你thinkphp5为静态没有设置好
```sh
   location / {

        if (!-e $request_filename) {
            rewrite ^(.*)$ /index.php?s=/$1 last;
            break;
        }
    }
     location ~ \.php(.*)$  {
        fastcgi_pass   php72:9000;
        fastcgi_index  index.php;
        include        fastcgi_params;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;
        fastcgi_param PATH_INFO       $path_info;
        try_files $fastcgi_script_name =404;
    }
```

**Comment by phpluo** [comment]
这个问题和本项目关系不大，只是我习惯配置其他网站的时候 复制一份默认配置修改而已 

![图](https://user-images.githubusercontent.com/15026737/136404311-e8874c2c-a165-4912-b263-20216fbc22d4.png)

![2021-10-10_23-07](https://user-images.githubusercontent.com/15026737/136701664-77837616-7708-4001-882f-b724cc299cac.png)

**Comment by jingmian** [comment]
已优化
