### ISSUE TITLE
.evn 配置swoole扩展没有开启openssl

### ISSUE THREAD

**Issue by SemiThin** [yeszao/dnmp#430]
现在临时进入容器安装

但是有时候重新build php容器的时候 常常忘记 进入容器install

有没有固定的方案啊？比如在php/extensions/install.sh 入手？

之前有个issue是在install.sh 解决，但是我尝试了也没有解决？
https://github.com/yeszao/dnmp/issues/350

请各位帮帮我，这个问题困扰我好久了

@jingmian @yeszao

**Comment by jingmian** [comment]
已添加
