### ISSUE TITLE
加上或者替换mariadb

### ISSUE THREAD

**Issue by ota1-letzgame** [yeszao/dnmp#432]
mysql缺了arm版，mariadb是个更好的选择

**Comment by justmd5** [comment]
docker-compose.yaml 文件配置参考：
`
mysql:
    image: mysql/mysql-server:${MYSQL_VERSION}
    container_name: mysql
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/my.cnf:ro
      - ${DATA_DIR}/mysql:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      TZ: "$TZ"
`
.env 里边版本定义：
MYSQL_VERSION = 8.0.27
