### ISSUE TITLE
引入企业微信会话存档大佬写的扩展包报错

### ISSUE THREAD

**Issue by benbenxiong1** [yeszao/dnmp#434]
编译安装完，启动php提示：PHP Warning:  PHP Startup: Unable to load dynamic library 'wxwork_finance_sdk.so' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/wxwork_finance_sdk.so (Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /package/php7-wxwork-finance-sdk-master/C_sdk/libWeWorkFinanceSdk_C.so)), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/wxwork_finance_sdk.so.so (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/wxwork_finance_sdk.so.so: No such file or directory)) in Unknown on line 0

这是什么原因？
附上： [会话存档的php扩展包地址](https://github.com/pangdahua/php7-wxwork-finance-sdk)
[企业微信sdk地址](https://work.weixin.qq.com/api/doc/90000/90135/91774)
能提供下解决思路么？

**Comment by ritaswc** [comment]
提示你缺少 动态库，自己改一下编译脚本 把php extension wxwork_finance_sdk.so自己装一下

**Comment by benbenxiong1** [comment]
> 提示你少自己动态库，改自己一下编译脚本把php扩展wxwork_finance_sdk.so装一下

wxwork_finance_sdk.so已经编译好了 缺少的是这个`加载共享库 ld-linux-x86-64.so.2 时出错：没有这样的文件或目录`

**Comment by ritaswc** [comment]
ld-linux是  glibc的，看看这个

https://github.com/sgerrand/alpine-pkg-glibc
