### ISSUE TITLE
php56 build failed

### ISSUE THREAD

**Issue by gelcaas** [yeszao/dnmp#438]
dnmp % docker-compose up -d
Building php56
[+] Building 0.0s (1/2)                                                                                                                                                                                     
 => [internal] load build definition from Dockerfile                                                                                                                                                   0.0s
 => => transferring dockerfile: 2B                                                                                                                                                                     0.0s
failed to solve with frontend dockerfile.v0: failed to read dockerfile: open /var/lib/docker/tmp/buildkit-mount951349866/Dockerfile: no such file or directory
ERROR: Service 'php56' failed to build : Build failed

**Comment by gelcaas** [comment]
who can help, What's the matter ?

**Comment by gelcaas** [comment]
Mac m1 和芯片有关吗？

**Comment by gelcaas** [comment]
service/php56里面怎么没有Dockerfile呢？

**Comment by jingmian** [comment]
`docker-compose.yml`你填写的php56格式有误，就会构建失败,php56是没有Dockerfile，因为是直接拉取已经构建好的镜像

**Comment by gelcaas** [comment]
> `docker-compose.yml`你填写的php56格式有误，就会构建失败,php56是没有Dockerfile，因为是直接拉取已经构建好的镜像

我是直接用的docker-compose.yml.sample里面的示例，是没有更新吗？

**Comment by jingmian** [comment]
`env.sample`文件有无修改`.env`

**Comment by yeszao** [comment]
PHP56 用的是 `services/php` 目录下的 Dockerfile 文件，docker-compose.yml 里面有：
```yml
  php56:
    build:
      context: ./services/php
```

**Comment by gelcaas** [comment]
> PHP56 用的是 `services/php` 目录下的 Dockerfile 文件，docker-compose.yml 里面有：
> 
> ```yaml
>   php56:
>     build:
>       context: ./services/php
> ```

ok. 可以了，谢谢
