### ISSUE TITLE
7.2没有找到fpm 容器  

### ISSUE THREAD

**Issue by jonise92** [yeszao/dnmp#44]
7 nginx配置文件
这里，我们还需要稍微修改nginx配置文件：

location ~ \.php$ {
    fastcgi_pass   fpm:9000;
    fastcgi_index  index.php;
    include        fastcgi_params;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
}
这里，我们仅需把fastcgi_pass改成：fpm:9000。

也就是，PHP-FPM的侦听主机改成：Nginx links PHP-FPM容器的别名，在docker-compose.yml文件里面我们设置为fpm。

在这一步没有找到fpm:9000 也没有找到Nginx links PHP-FPM容器的别名

**Comment by yeszao** [comment]
博客上的是稍微旧一些的描述了，github上的代码已经改成最新的 network 方式了，具体请参看docker-compose.yml文件源码
