### ISSUE TITLE
可以新增 php8.1吗？

### ISSUE THREAD

**Issue by zbage** [yeszao/dnmp#441]

**Comment by ritaswc** [comment]
你把.env里面的配置改成8.1就是了呀

或者docker-compose.yml 增加一个php81的容器

PHP_VERSION: php:8.1.1-fpm-alpine3.15

**Comment by zbage** [comment]
php81:
      build:
        context: ./services/php81
        args:
          PHP_VERSION: php:${PHP81_VERSION}-fpm-alpine3.15
          CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
          PHP_EXTENSIONS: ${PHP81_EXTENSIONS}
          TZ: "$TZ"
      container_name: php81
      expose:
        - 9501
      extra_hosts:
        - "zbage.lan:172.0.0.10"
      volumes:
        - ${SOURCE_DIR}:/www/:rw
        - ${PHP81_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
        - ${PHP81_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
        - ${PHP81_LOG_DIR}:/var/log/php
        - ${DATA_DIR}/composer:/tmp/composer
      restart: always
      cap_add:
        - SYS_PTRACE
      networks:
      net-default:
        ipv4_address: 172.0.0.9
     
ERROR: The Compose file './docker-compose.yml' is invalid because:
Unsupported config option for services.php: 'php81'
