### ISSUE TITLE
php5.4.5部分扩展无法安装，该如何解决？

### ISSUE THREAD

**Issue by xuexuguang** [yeszao/dnmp#443]
php安装的版本为php5.4.5

但是在env里添加了扩展 mongo、yaf、xdebug之后，无法正常安装；应该是5.4.5不支持env里配置； 

像这种情况，每次我都是进入容器后，手动编译扩展，进行安装。带来的问题就是，一重启容器后扩展又丢失了，很苦恼。 

我把容器打包成镜像后，然后再在yaml文件中指定从镜像进行构建，但是每次打包完之后，镜像很大。新增扩展的话，还需要重新打包镜像。

想请问下，我这种情况有什么好的处理方式吗？ 不胜感激

**Comment by yeszao** [comment]
修改 `services/php54/Dockerfile` 文件，加上自己的扩展，就不会丢失的。
