### ISSUE TITLE
env配置里新增了rdkafka，安装完以后没有扩展？

### ISSUE THREAD

**Issue by xuexuguang** [yeszao/dnmp#444]
# PHP7.2.5
PHP72_VERSION=7.2.5
PHP72_PHP_CONF_FILE=./services/php72/php.ini
PHP72_FPM_CONF_FILE=./services/php72/php-fpm.conf
PHP72_LOG_DIR=./logs/php
PHP72_EXTENSIONS=pdo_mysql,mbstring,gd,curl,redis,memcached,xdebug,amqp,igbinary,mysqli,pcntl,mongodb,bcmath,ctype,Tokenizer,xml,zip,rdkafka

env配置添加了rdkafka，build完之后，执行php -m 看不到扩展

**Comment by ritaswc** [comment]
缺少这个编译的内容，大兄弟，你来贡献代码吧
