### ISSUE TITLE
PHPMyAdmin配置好像不生效

### ISSUE THREAD

**Issue by DanceLynx** [yeszao/dnmp#450]
比如
memory_limit = 512M
post_max_size = 512M
upload_max_filesize = 512M
导入sql文件的时候 最大还是显示的是2M

**Comment by jingmian** [comment]
这个不建议用网页端导入,建议使用navicat外连链接后，倒入数据。没有生效的原因可能是`phpmyadmin`容器里面的php配置文件限制了
