### ISSUE TITLE
如何安装别的版本PHP,比如8.1

### ISSUE THREAD

**Issue by moon-zhangyue** [yeszao/dnmp#456]
你好,麻烦问下,如何安装别的版本PHP,比如8.1 谢谢

**Comment by jingmian** [comment]
```sh
 php81:
   build:
     context: ./services/php80
     args:
       PHP_VERSION: php:${PHP80_VERSION}-fpm-alpine3.13
       CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
       PHP_EXTENSIONS: ${PHP80_EXTENSIONS}
       TZ: "$TZ"
   container_name: php81
   expose:
     - 9501
   volumes:
     - ${SOURCE_DIR}:/www/:rw
     - ${PHP80_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
     - ${PHP80_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
     - ${PHP80_LOG_DIR}:/var/log/php
     - ${DATA_DIR}/composer:/tmp/composer
   restart: always
   cap_add:
     - SYS_PTRACE
   networks:
     - default
```
然后构建镜像之前需要在`env`里面的`PHP80_VERSION`设置一下`8.1`版本就可以了

**Comment by jingmian** [comment]
[参考这里](https://github.com/yeszao/dnmp/issues/456)

**Comment by moon-zhangyue** [comment]
> ```shell
>  php81:
>    build:
>      context: ./services/php80
>      args:
>        PHP_VERSION: php:${PHP80_VERSION}-fpm-alpine3.13
>        CONTAINER_PACKAGE_URL: ${CONTAINER_PACKAGE_URL}
>        PHP_EXTENSIONS: ${PHP80_EXTENSIONS}
>        TZ: "$TZ"
>    container_name: php81
>    expose:
>      - 9501
>    volumes:
>      - ${SOURCE_DIR}:/www/:rw
>      - ${PHP80_PHP_CONF_FILE}:/usr/local/etc/php/php.ini:ro
>      - ${PHP80_FPM_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
>      - ${PHP80_LOG_DIR}:/var/log/php
>      - ${DATA_DIR}/composer:/tmp/composer
>    restart: always
>    cap_add:
>      - SYS_PTRACE
>    networks:
>      - default
> ```
> 
> 然后构建镜像之前需要在`env`里面的`PHP80_VERSION`设置一下`8.1`版本就可以了

你这能成功？？？  8.1的文件都没有的

**Comment by yeszao** [comment]
用了跟 php8.0 一样的配置。
