### ISSUE TITLE
增添多功能

### ISSUE THREAD

**Issue by junyuexin** [yeszao/dnmp#46]
你好，能不能像PHP多版本那样，mysql也增加个5.7的版本，使用的网站程序不支持mysql8，我把8.0改成5.7一直没成功过，对容器服务不是太熟悉修改了几处也不行。还有就是PHP的版本可不可以写在一个yml文件中，修改成不同的端口映射，那样可以同时使用多个版本的PHP。期待您的回复，谢谢！

**Comment by yeszao** [comment]
这是另外一个功能了，建议在自己项目中修改实现。
