### ISSUE TITLE
Redis服务器版本：Redis 扩展未安装 ×

### ISSUE THREAD

**Issue by zcyc** [yeszao/dnmp#460]
修改了 .env，重新 build 之后还是这样。

**Comment by zcyc** [comment]
我进到容器里边检查了 php -m 也没看到 redis。

**Comment by zcyc** [comment]
只能到容器里边 install-php-extensions

**Comment by Gitturb** [comment]
需要docker-compose up 重启一下

**Comment by zcyc** [comment]
> 需要docker-compose up 重启一下

重启了也不行。非得进里边去装。完全按您文档操作的。
