### ISSUE TITLE
pdo_sqlsrv安装不上

### ISSUE THREAD

**Issue by rsaLive** [yeszao/dnmp#462]
请教一个环境问题
我是windows10  docker环境，昨天好好的，我今天build 一下之后，pdo_sqlsrv 失败了，报错如下：（我php -m 查看pdo_sqlsrv 是有的）

![YG 2PI~DVZ_P GW`8% E6P](https://user-images.githubusercontent.com/14867935/158562002-1f98cef3-bcb2-4bff-9315-985210789828.png)

**Comment by rsaLive** [comment]
这个问题 已解决

**Comment by yeszao** [comment]
网络的问题，多试几次，或者用代理。
