### ISSUE TITLE
webhook 自动拉取代码

### ISSUE THREAD

**Issue by YanCunJu** [yeszao/dnmp#468]
目的：webhook 执行脚本自动拉取代码
尝试：
自己写的简单的 webook 钩子，代码类似于`exec(cd  my_project_path && git pull origin dev)` ，执行没有报错，但是也没执行成功。切换到 php 容器，给 www-data 用户生成了 ssh，并且把 公钥添加到了代码仓库，但是没有效果。想在容器中切到 www-data 用户，手动执行命令，却被告知`This account is not available`，不知道如何调试了，请给一些思路，谢谢。

**Comment by wangxujian666** [comment]
需要把www-data设置为可登陆(我暂时用的这个,感觉不是正道)
