### ISSUE TITLE
swoole 扩展如何开启 openssl？

### ISSUE THREAD

**Issue by Linnzh** [yeszao/dnmp#469]
发送邮件时，提示：

`Connection could not be established with host smtp.qq.com :stream_socket_client(): you must configure with `--enable-openssl` to support ssl connection when compiling Swoole`

**Comment by opszhou** [comment]
解决了？

**Comment by Linnzh** [comment]
> 解决了？

我在 install.sh 里修改了安装 swoole 的命令：

```sh
if [[ -z "${EXTENSIONS##*,swoole,*}" ]]; then
    echo "---------- Install swoole ----------"
    # pecl install swoole # 原安装 swoole 命令，更改为下面的命令
    pecl install --configureoptions 'enable-sockets="no" enable-openssl="yes" enable-http2="yes" enable-mysqlnd="yes" enable-swoole-json="no" enable-swoole-curl="yes" enable-cares="yes"' swoole
    docker-php-ext-enable swoole
fi
```

携带配置安装的这条命令是在 swoole 官网找的：<https://wiki.swoole.com/#/environment?id=pecl>
