### ISSUE TITLE
php扩展

### ISSUE THREAD

**Issue by 35924784** [yeszao/dnmp#47]
php的扩展安装能否加一个说明

**Comment by yeszao** [comment]
你指的是什么样的说明?

**Comment by 35924784** [comment]
就是如何安装相应的扩展，比如memcached,mongodb类似的扩展如何安装？
如下图您这里提到的第10项，这些命令能否说明下：

<img width="496" alt="default" src="https://user-images.githubusercontent.com/5801601/43933997-77e7ef78-9c7f-11e8-8cfc-b3e5e53feed8.png">

**Comment by yeszao** [comment]
这些需要通过源码安装，dockerfile里面有例子的，参考来做就行了的。
