### ISSUE TITLE
因为新版本的libiconv移除了preloadable_libiconv.so这个扩展包,

### ISSUE THREAD

**Issue by uunmask2000** [yeszao/dnmp#479]
因为新版本的libiconv移除了preloadable_libiconv.so这个扩展包,
进入php容器,执行下面语句,然后重启容器即可
apk add gnu-libiconv=1.15-r2  --no-cache --repository http://mirrors.aliyun.com/alpine/v3.12/community

_Originally posted by @huadiji in https://github.com/yeszao/dnmp/issues/414#issuecomment-901067505_

**Comment by uunmask2000** [comment]
這個可以加回去嘛？

**Comment by jingmian** [comment]
你是在php哪个版本测试的，我测试了7.2.19-alpine，没有这个问题呢

**Comment by uunmask2000** [comment]
我在php7.4.25 版本
莊康軍 -0932-969-495
                           telegram : https://t.me/tankcat
                           LINE ID : tankcat
                           WeChat ID : tankcat0301
個人履歷 : https://www.cakeresume.com/9c65a5



镜面王子 ***@***.***> 於 2022年5月5日 週四 下午3:25寫道：

**Comment by jingmian** [comment]
已修复，可以测试下了
