### ISSUE TITLE
mysql5.7配置问题

### ISSUE THREAD

**Issue by junyuexin** [yeszao/dnmp#49]
如何配置mysql5.7，我一次都没成功过(不是高手没办法），能不能像PHP可以选择版本一样，给做个mysql5.7的yml文件，谢谢！

**Comment by yeszao** [comment]
docker-compose.yml文件里面，把：
```
...
  mysql:
    image: mysql:8.0
...
```
改为：

```
...
  mysql:
    image: mysql:5.7
...
```
在重新构建：
```
docker-compose up --build --no-deps mysql
```

**Comment by Cstome** [comment]
我也是这样做，但是他提示：

`dnmp_mysql_1_c5c6ca28af15 exited with code 2`

**Comment by Cstome** [comment]
> 我也是这样做，但是他提示：
> 
> `dnmp_mysql_1_c5c6ca28af15 exited with code 2`

自己解决了。

由于MySQL8 不支持降级，因此降级到MySQL5.7后出现不兼容的情况。
由于只报错 `dnmp_mysql_1_c5c6ca28af15 exited with code 2` ，没有其他错误信息，后来刷新 ./mysql 文件夹才发现里面的 `mysql.error.log` 错误日志。

解决方法：

对于没有数据表的情况，直接删除 ./mysql 文件夹。
有数据的情况，建议导出数据后，删除 ./mysql 文件夹，等MySQL5.7初始化后再重新导入。
