### ISSUE TITLE
mac php80 redis扩展安装失败

### ISSUE THREAD

**Issue by pipifamily** [yeszao/dnmp#492]
方法一：.env php80 PHP_EXTENSIONS add redis(PHP80_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache,redis)然后docker-compose build php80  没有报错，进入容器发现没有安装成功，后再容器 install-php-extensions redis,提示 github.com等网页请求超时无法安装；但我在服务器这两种方式安装都没有问题，是什么原因呢

**Comment by dygin** [comment]
you should run proxy to accelerate your network or you could download the offline package from pecl to normal install instead in pod

**Comment by jingmian** [comment]
已添加
