### ISSUE TITLE
Invalid service name "php-fpm" - only [a-zA-Z0-9] are allowed

### ISSUE THREAD

**Issue by puregardenia** [yeszao/dnmp#5]
https://github.com/yeszao/dnmp/blob/19476595801961184a1bed39d6d72bd41783461e/docker-compose.yml#L12-L14

Linux Mint 18.2 基于 ubuntu 16 会报 `Invalid service name "php-fpm" - only [a-zA-Z0-9] are allowed` 的错误。
修改为 `phpfpm` 就行了

**Comment by yeszao** [comment]
嗯，需要和系统命名规则
