### ISSUE TITLE
mysql用户名密码

### ISSUE THREAD

**Issue by otherChild** [yeszao/dnmp#50]
mysql用户名密码是多少？没有按照phpadmin

**Comment by yeszao** [comment]
用户名：root
密码：123456

这在docker-compose.yml文件中指定的

**Comment by Cstome** [comment]
可以在 .env 文件里修改密码吗，我改了发现没作用。

**Comment by yeszao** [comment]
.env里面的只是构建的时候有用，系统启动之后就要登录MySQL改了。
