### ISSUE TITLE
无法访问加速镜像

### ISSUE THREAD

**Issue by huangzhuohua** [yeszao/dnmp#500]
git clone https://github.com.cnpmjs.org/yeszao/dnmp.git
无法访问

Cloning into 'dnmp'...
fatal: unable to access 'https://github.com.cnpmjs.org/yeszao/dnmp.git/': Could not resolve host: github.com.cnpmjs.org

**Comment by jingmian** [comment]
gitee，有我们的镜像https://gitee.com/yeszao/dnmp
