### ISSUE TITLE
rabbitmq_delayed_message_exchange 插件启用失败

### ISSUE THREAD

**Issue by CloudS-Hu** [yeszao/dnmp#508]
[root@localhost dnmp]# docker-compose up -d
[+] Building 8.3s (5/5) FINISHED                                                                                                                
 => [internal] load build definition from Dockerfile                                                                                       0.0s
 => => transferring dockerfile: 32B                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                          0.0s
 => => transferring context: 2B                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/rabbitmq:management                                                                     4.4s
 => CACHED [1/2] FROM docker.io/library/rabbitmq:management@sha256:4e07766c0f2347d52550e75698b0ef998489f015ca1b59f691d435992381c4da        0.0s
 => => resolve docker.io/library/rabbitmq:management@sha256:4e07766c0f2347d52550e75698b0ef998489f015ca1b59f691d435992381c4da               0.0s
 => ERROR [2/2] RUN if [ -z "${PLUGINS##*,rabbitmq_amqp1_0,*}" ]; then         printf "y\n"| rabbitmq-plugins enable rabbitmq_amqp1_0;     3.9s
------                                                                                                                                          
 > [2/2] RUN if [ -z "${PLUGINS##*,rabbitmq_amqp1_0,*}" ]; then         printf "y\n"| rabbitmq-plugins enable rabbitmq_amqp1_0;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_auth_backend_ldap,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_auth_backend_ldap;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_auth_backend_http,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_auth_backend_http;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_auth_mechanism_ssl,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_auth_mechanism_ssl;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_consistent_hash_exchange,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_consistent_hash_exchange;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_federation,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_federation;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_federation_management,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_federation_management;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_management_agent,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_management_agent;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_mqtt,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_mqtt;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_prometheus,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_prometheus;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_shovel,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_shovel;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_shovel_management,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_shovel_management;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_stomp,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_stomp;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_trust_store,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_trust_store;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_stomp,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_stomp;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_mqtt,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_mqtt;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_stomp_examples,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_stomp_examples;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_mqtt_examples,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_mqtt_examples;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_delayed_message_exchange,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_delayed_message_exchange;     fi:
#0 0.973 Enabling plugins on node rabbit@buildkitsandbox:
#0 0.973 rabbitmq_amqp1_0
#0 2.009 The following plugins have been configured:
#0 2.009   rabbitmq_amqp1_0
#0 2.009   rabbitmq_management
#0 2.009   rabbitmq_management_agent
#0 2.009   rabbitmq_prometheus
#0 2.009   rabbitmq_web_dispatch
#0 2.009 Applying plugin configuration to rabbit@buildkitsandbox...
#0 2.123 The following plugins have been enabled:
#0 2.123   rabbitmq_amqp1_0
#0 2.123 
#0 2.123 set 5 plugins.
#0 2.123 Offline change; changes will take effect at broker restart.
#0 2.793 Enabling plugins on node rabbit@buildkitsandbox:
#0 2.793 rabbitmq_delayed_message_exchange
#0 3.829 Error:
#0 3.829 {:plugins_not_found, [:rabbitmq_delayed_message_exchange]}
------
failed to solve: executor failed running [/bin/sh -c if [ -z "${PLUGINS##*,rabbitmq_amqp1_0,*}" ]; then         printf "y\n"| rabbitmq-plugins enable rabbitmq_amqp1_0;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_auth_backend_ldap,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_auth_backend_ldap;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_auth_backend_http,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_auth_backend_http;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_auth_mechanism_ssl,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_auth_mechanism_ssl;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_consistent_hash_exchange,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_consistent_hash_exchange;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_federation,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_federation;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_federation_management,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_federation_management;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_management_agent,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_management_agent;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_mqtt,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_mqtt;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_prometheus,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_prometheus;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_shovel,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_shovel;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_shovel_management,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_shovel_management;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_stomp,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_stomp;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_trust_store,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_trust_store;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_stomp,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_stomp;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_mqtt,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_mqtt;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_stomp_examples,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_stomp_examples;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_web_mqtt_examples,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_web_mqtt_examples;     fi     &&     if [ -z "${PLUGINS##*,rabbitmq_delayed_message_exchange,*}" ]; then         printf "y\n" | rabbitmq-plugins enable rabbitmq_delayed_message_exchange;     fi]: exit code: 70

**Comment by CloudS-Hu** [comment]
.env

#
# PHP source directory
#
SOURCE_DIR=/var/www

#
# Runtime data directory
#
DATA_DIR=./data

#
# Container Timezone
#
TZ=Asia/Shanghai

#
# Container package fetch url
#
# Can be empty, followings or others:
# mirrors.163.com
# mirrors.aliyun.com
# mirrors.ustc.edu.cn
# dl-cdn.alpinelinux.org
#
CONTAINER_PACKAGE_URL=mirrors.ustc.edu.cn

#
#ALPINE
#
ALPINE_VERSION=3.12

#
# Nginx
#
NGINX_VERSION=1.19.1-alpine
NGINX_HTTP_HOST_PORT=80
NGINX_HTTPS_HOST_PORT=443
NGINX_CONFD_DIR=./services/nginx/conf.d
NGINX_CONF_FILE=./services/nginx/nginx.conf
NGINX_FASTCGI_PHP_CONF=./services/nginx/fastcgi-php.conf
NGINX_FASTCGI_PARAMS=./services/nginx/fastcgi_params
NGINX_LOCATION_PHP=./services/nginx/location_php
NGINX_CORS=./services/nginx/cors
NGINX_SSL_CERTIFICATE_DIR=./services/nginx/ssl
NGINX_LOG_DIR=./logs/nginx
# Available apps: certbot
NGINX_INSTALL_APPS=

#
# Openresty
#
OPENRESTY_VERSION=alpine
OPENRESTY_HTTP_HOST_PORT=80
OPENRESTY_HTTPS_HOST_PORT=443
OPENRESTY_CONFD_DIR=./services/openresty/conf.d
OPENRESTY_CONF_FILE=./services/openresty/openresty.conf
OPENRESTY_FASTCGI_PHP_CONF=./services/openresty/fastcgi-php.conf
OPENRESTY_CONF_FASTCGIPARAMS_FILE=./services/openresty/fastcgi_params
OPENRESTY_SSL_CERTIFICATE_DIR=./services/openresty/ssl
OPENRESTY_LOG_DIR=./logs/nginx

#
# SUPERVISOR
#
SUPERVISOR_CONFIG=./services/supervisor/conf.d/
SUPERVISOR_LOG=./logs/supervisor
SUPERVISOR_CONF_FILE=./services/supervisor/supervisord.conf
SUPERVISOR_HOST_PORT_C=9001

#
# PHP8
#
# Available PHP_EXTENSIONS:
#
# pdo_mysql,zip,pcntl,mysqli,mbstring,exif,bcmath,calendar,
# sockets,gettext,shmop,sysvmsg,sysvsem,sysvshm,pdo_rebird,
# pdo_dblib,pdo_oci,pdo_odbc,pdo_pgsql,pgsql,oci8,odbc,dba,
# gd,intl,bz2,soap,xsl,xmlrpc,wddx,curl,readline,snmp,pspell,
# recode,tidy,gmp,imap,ldap,imagick,sqlsrv,mcrypt,opcache,
# redis,memcached,xdebug,swoole,pdo_sqlsrv,sodium,yaf,mysql,
# amqp,mongodb,event,rar,ast,yac,yar,yaconf,msgpack,igbinary,
# seaslog,varnish,xhprof,xlswriter,memcache,rdkafka,zookeeper,
# psr,phalcon,sdebug,ssh2,yaml,protobuf,hprose
#
# You can let it empty to avoid installing any extensions,
# or install multi plugins as:
# PHP_EXTENSIONS=pdo_mysql,mysqli,gd,curl,opcache
#
PHP80_VERSION=8.0.9
PHP80_PHP_CONF_FILE=./services/php80/php.ini
PHP80_FPM_CONF_FILE=./services/php80/php-fpm.conf
PHP80_LOG_DIR=./logs/php80
PHP80_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache


#
# PHP7
#
# Available PHP_EXTENSIONS:
#
# pdo_mysql,zip,pcntl,mysqli,mbstring,exif,bcmath,calendar,
# sockets,gettext,shmop,sysvmsg,sysvsem,sysvshm,pdo_rebird,
# pdo_dblib,pdo_oci,pdo_odbc,pdo_pgsql,pgsql,oci8,odbc,dba,
# gd,intl,bz2,soap,xsl,xmlrpc,wddx,curl,readline,snmp,pspell,
# recode,tidy,gmp,imap,ldap,imagick,sqlsrv,mcrypt,opcache,
# redis,memcached,xdebug,swoole,pdo_sqlsrv,sodium,yaf,mysql,
# amqp,mongodb,event,rar,ast,yac,yar,yaconf,msgpack,igbinary,
# seaslog,varnish,xhprof,xlswriter,memcache,rdkafka,zookeeper,
# psr,phalcon,sdebug,ssh2,yaml,protobuf,hprose
#
# You can let it empty to avoid installing any extensions,
# or install multi plugins as:
# PHP_EXTENSIONS=pdo_mysql,mysqli,gd,curl,opcache
#
PHP_VERSION=7.4.27
PHP_PHP_CONF_FILE=./services/php/php.ini
PHP_FPM_CONF_FILE=./services/php/php-fpm.conf
PHP_LOG_DIR=./logs/php
PHP_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache


#
# PHP5.6
#
PHP56_VERSION=5.6.40
PHP56_PHP_CONF_FILE=./services/php56/php.ini
PHP56_FPM_CONF_FILE=./services/php56/php-fpm.conf
PHP56_LOG_DIR=./logs/php
PHP56_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache

#
# PHP5.4
#
PHP54_VERSION=5.4.45
PHP54_PHP_CONF_FILE=./services/php54/php.ini
PHP54_FPM_CONF_FILE=./services/php54/php-fpm.conf
PHP54_LOG_DIR=./logs/php
PHP54_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache

#
# RABBITMQ
# Available RABBITMQ_PLUGINS:
# rabbitmq_amqp1_0,rabbitmq_auth_backend_ldap,rabbitmq_auth_backend_http,rabbitmq_auth_mechanism_ssl,
# rabbitmq_consistent_hash_exchange,rabbitmq_federation,rabbitmq_federation_management,rabbitmq_management,
# rabbitmq_management_agent,rabbitmq_mqtt,rabbitmq_prometheus,rabbitmq_shovel,rabbitmq_shovel_management,
# rabbitmq_stomp,rabbitmq_tracing,rabbitmq_trust_store,rabbitmq_web_stomp,rabbitmq_web_mqtt,
# rabbitmq_web_stomp_examples,rabbitmq_web_mqtt_examples,rabbitmq_delayed_message_exchange
#
RABBITMQ_VERSION=management
RABBITMQ_CONF_FILE=./services/rabbitmq/rabbitmq.yml
RABBITMQ_HOST_PORT_C=5672
RABBITMQ_HOST_PORT_S=15672
RABBITMQ_DEFAULT_USER=myuser
RABBITMQ_DEFAULT_PASS=mypass
RABBITMQ_PLUGINS=rabbitmq_amqp1_0

#
# MONGODB
#
MONGODB_VERSION=4.1
MONGODB_HOST_PORT=27017
MONGODB_INITDB_ROOT_USERNAME=root
MONGODB_INITDB_ROOT_PASSWORD=123456

#
# ELASTICSEARCH
#
# Available ELASTICSEARCH_PLUGINS:
#
# amazon-ec2,analysis-icu,analysis-kuromoji,analysis-nori,
# analysis-phonetic,analysis-smartcn,analysis-stempel,
# analysis-ukrainian,discovery-azure-classic,discovery-ec2,
# discovery-file,discovery-gce,google-cloud-storage,
# ingest-attachment,ingest-geoip,ingest-user-agent,mapper-murmur3,
# mapper-size,microsoft-azure-storage,qa,repository-azure,
# repository-gcs,repository-hdfs,repository-s3,store-smb,
# analysis-ik,analysis-pinyin
#
# You can let it empty to avoid installing any plugins,
# or install plugins as:
# ELASTICSEARCH_PLUGINS=analysis-ik,analysis-pinyin
#
ELASTICSEARCH_VERSION=7.1.1
ELASTICSEARCH_CONF_FILE=./services/elasticsearch/elasticsearch.yml
ELASTICSEARCH_HOST_PORT_C=9200
ELASTICSEARCH_HOST_PORT_S=9300
ELASTICSEARCH_PLUGINS=analysis-ik

#
# KIBANA
#
KIBANA_VERSION=7.1.1
KIBANA_HOST=5601
KIBANA_I18N_LOCALE=zh-CN

#
# LOGSTASH
#
LOGSTASH_VERSION=7.1.1
LOGSTASH_HOST=5601
LOGSTASH_HOST_PORT_C=9600
LOGSTASH_HOST_PORT_S=5044

#
# MySQL8
#
MYSQL_VERSION=8.0.28
MYSQL_HOST_PORT=3306
MYSQL_ROOT_PASSWORD=123456
MYSQL_ROOT_HOST=%
MYSQL_CONF_FILE=./services/mysql/mysql.cnf
MYSQL_LOG_DIR=./logs/mysql
#
# MySQL5
#
MYSQL5_VERSION=5.7.28
MYSQL5_HOST_PORT=3305
MYSQL5_ROOT_PASSWORD=123456
MYSQL5_ROOT_HOST=%
MYSQL5_CONF_FILE=./services/mysql5/mysql.cnf
MYSQL5_LOG_DIR=./logs/mysql5

#
# Redis
#
REDIS_VERSION=5.0.3-alpine
REDIS_HOST_PORT=6379
REDIS_CONF_FILE=./services/redis/redis.conf

#
# Memcached
#
MEMCACHED_VERSION=alpine
MEMCACHED_HOST_PORT=11211
MEMCACHED_CACHE_SIZE=128

#
# phpMyAdmin
#
PHPMYADMIN_HOST_PORT=8080
PHPMYADMIN_USER_CONF_FILE=./services/phpmyadmin/config.user.inc.php
PHPMYADMIN_PHP_CONF_FILE=./services/phpmyadmin/php-phpmyadmin.ini

#
# redisMyAdmin
#
REDISMYADMIN_HOST_PORT=8081

#
# AdminMongo
#
ADMINMONGO_HOST_PORT=1234

#
# Node
#
NODE_VERSION=10.16.1-alpine

**Comment by CloudS-Hu** [comment]
docker-compose.yml 配置

```
  rabbitmq:
    build:
      context: ./services/rabbitmq
      args:
        RABBITMQ_VERSION: ${RABBITMQ_VERSION}
        RABBITMQ_PLUGINS: ${RABBITMQ_PLUGINS}
    container_name: rabbitmq
    restart: always
    ports:
      - "${RABBITMQ_HOST_PORT_C}:5672"
      - "${RABBITMQ_HOST_PORT_S}:15672"
    environment:
       TZ: "$TZ"
       RABBITMQ_DEFAULT_USER: "${RABBITMQ_DEFAULT_USER}"
       RABBITMQ_DEFAULT_PASS: "${RABBITMQ_DEFAULT_PASS}"
    networks:
          - default
```

**Comment by CloudS-Hu** [comment]
系统环境：
```
[root@localhost dnmp]# cat /proc/version 
Linux version 3.10.0-1160.71.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Tue Jun 28 15:37:28 UTC 2022
[root@localhost dnmp]# uname -a
Linux localhost.localdomain 3.10.0-1160.71.1.el7.x86_64 #1 SMP Tue Jun 28 15:37:28 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by balrogsxt** [comment]
我看了容器里面没有rabbitmq_delayed_message_exchange，自己下一个拖进去启用

**Comment by CloudS-Hu** [comment]
> 我看了容器里面没有rabbitmq_delayed_message_exchange，自己下一个拖进去启用

谢谢，已解决

解决方法：
1 、在 services/rabbitmq/下创建plugins目录，然后将 rabbitmq_delayed_message_exchange-3.11.1 插件下载到目录中
2、Dockfile中新增`COPY ./plugins/rabbitmq_delayed_message_exchange-3.11.1 /plugins/rabbitmq_delayed_message_exchange-3.11.1`
重新启动容器

**Comment by CloudS-Hu** [comment]
> 我看了容器里面没有rabbitmq_delayed_message_exchange，自己下一个拖进去启用

已解决，解决方法
1、在 ./services/rabbitmq/ 下创建 plugins目录，下载插件 rabbitmq_delayed_message_exchange-3.11.1.ez 放到目录中
2、Dockerfile 中添加拷贝脚本 `COPY ./plugins /plugins`

重新构建并启动容器
