### ISSUE TITLE
swoole看着装上了,实际上没有

### ISSUE THREAD

**Issue by jonny77** [yeszao/dnmp#509]
phpinfo打出来

/usr/local/etc/php/conf.d/docker-php-ext-gd.ini, /usr/local/etc/php/conf.d/docker-php-ext-mysqli.ini, /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini, /usr/local/etc/php/conf.d/docker-php-ext-pdo_mysql.ini, /usr/local/etc/php/conf.d/docker-php-ext-redis.ini, /usr/local/etc/php/conf.d/docker-php-ext-sodium.ini, /usr/local/etc/php/conf.d/docker-php-ext-swoole.ini

进入容器 php --ri swoole 又是:
Extension 'swoole' not present.

![image](https://user-images.githubusercontent.com/1962170/183636466-aabe62d7-cd13-4f20-a4c7-4640b52eed35.png)

**Comment by jingmian** [comment]
`install-php-extensions swoole`你用这个命令试下

**Comment by jonny77** [comment]
> `install-php-extensions swoole`你用这个命令试下

进入容器里面装吗?

**Comment by jonny77** [comment]
> `install-php-extensions swoole`你用这个命令试下

### INSTALLING REMOTE MODULE swoole ###
pecl/swoole requires PHP (version >= 8.0.0), installed version is 7.4.27
No valid packages found
install failed
哎.... 7.4不行啊

**Comment by uunmask2000** [comment]
> > `install-php-extensions swoole`你用这个命令试下
> 
> ### INSTALLING REMOTE MODULE swoole
> pecl/swoole requires PHP (version >= 8.0.0), installed version is 7.4.27 No valid packages found install failed 哎.... 7.4不行啊

https://github.com/yeszao/dnmp/tree/master/services/php/extensions
你要将版本php 或者 你要把你的 swoole 包 丢进来就可以了

**Comment by jeeinn** [comment]
确实有这个问题，使用 `docker compose build php`，输出的日志里会有错误：
```
#14 [10/12] RUN chmod +x install-composer.sh     && sh install-composer.sh     && rm -rf /tmp/extensions
#14 0.362 PHP Warning:  PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20190902/swoole (Error loading shared library /usr/local/lib/php/extensions/no-debug-non-zts-20190902/swoole: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20190902/swoole.so (Error loading shared library libstdc++.so.6: No such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20190902/swoole.so))) in Unknown on line 0
```
但是按照 install.sh 的脚本，进入容器依次安装却没有问题，汗。
使用楼上的命令单独安装也可以：https://github.com/yeszao/dnmp/issues/509#issuecomment-1211445622 （但是这种完全重启容器后会消失）

**Comment by shmilylbelva** [comment]
文章的第二部分 [https://www.jianshu.com/p/a49dae2c6aff](https://www.jianshu.com/p/a49dae2c6aff)
