### ISSUE TITLE
Mac上运行一直报路径错误

### ISSUE THREAD

**Issue by lylevip** [yeszao/dnmp#51]
Mac版本为：10.13.6
错误信息如下：
ERROR: for dnmp_nginx_1  Cannot start service nginx: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/www/docker/dnmp/conf/nginx.conf\\\" to rootfs \\\"/mnt/sda1/varStarting dnmp_redis_1         ... done
Starting dnmp_phpredisadmin_1 ... done
74a74cd/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying toStarting dnmp_mysql_1         ... error
 the expected type

ERROR: for dnmp_mysql_1  Cannot start service mysql: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/www/docker/dnmp/conf/mysql.cnf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/9483012af8ad00ef2a1b3a6720f9c88e478d51c845dd7dba70497ac3a0f5af52\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/9483012af8ad00ef2a1b3a6720f9c88e478d51c845dd7dba70497ac3a0Recreating dnmp_php_1         ... error
ng to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for dnmp_php_1  Cannot start service php: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/www/docker/dnmp/conf/php-fpm.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/94973dee0374c72294e63702ec89ea5c668fc5d4eceaa7757fb364bdd5cccb87\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/94973dee0374c72294e63702ec89ea5c668fc5d4eceaa7757fb364bdd5cccb87/usr/local/etc/php-fpm.d/www.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx  Cannot start service nginx: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/www/docker/dnmp/conf/nginx.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/939581fbda36b4b5276677dc2f6338331aae2c76c78af6c5cf893852a74a74cd\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/939581fbda36b4b5276677dc2f6338331aae2c76c78af6c5cf893852a74a74cd/etc/nginx/nginx.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for mysql  Cannot start service mysql: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/www/docker/dnmp/conf/mysql.cnf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/9483012af8ad00ef2a1b3a6720f9c88e478d51c845dd7dba70497ac3a0f5af52\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/9483012af8ad00ef2a1b3a6720f9c88e478d51c845dd7dba70497ac3a0f5af52/etc/mysql/conf.d/mysql.cnf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for php  Cannot start service php: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/www/docker/dnmp/conf/php-fpm.conf\\\" to rootfs \\\"/mnt/sda1/var/lib/docker/aufs/mnt/94973dee0374c72294e63702ec89ea5c668fc5d4eceaa7757fb364bdd5cccb87\\\" at \\\"/mnt/sda1/var/lib/docker/aufs/mnt/94973dee0374c72294e63702ec89ea5c668fc5d4eceaa7757fb364bdd5cccb87/usr/local/etc/php-fpm.d/www.conf\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by yeszao** [comment]
可能是权限问题，如果确保了权限没问题，可以把已经建过的容器删除，重启docker，然后再试试。
