### ISSUE TITLE
关于workerman无法连接的问题

### ISSUE THREAD

**Issue by tlerbao** [yeszao/dnmp#513]
我根据 [workerman的简单开发示例](https://www.workerman.net/doc/workerman/getting-started/simple-example.html)，示例二启动了成功后，无法连接上，是因为php运行在容器里的问题吗？

<img width="504" alt="image" src="https://user-images.githubusercontent.com/20442232/187460447-c79d6a2d-ada3-4fc7-970a-b698a54158be.png">

<img width="939" alt="image" src="https://user-images.githubusercontent.com/20442232/187460330-baffd172-5af8-460f-a54e-2d78b2bca0e6.png">

**Comment by jingmian** [comment]
端口确认开放了吗
