### ISSUE TITLE
安装扩展时报错

### ISSUE THREAD

**Issue by 879820013** [yeszao/dnmp#515]
Updating channel "pecl.php.net"
Channel "pecl.php.net" is up to date
fetch https://mirrors.ustc.edu.cn/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.ustc.edu.cn/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
v3.14.8-12-g72a50554ec [https://mirrors.ustc.edu.cn/alpine/v3.14/main]
v3.14.8-8-g3f503f87ee [https://mirrors.ustc.edu.cn/alpine/v3.14/community]
OK: 14959 distinct packages available
### MARKING PRE-INSTALLED PACKAGES AS IN-USE ###
# Packages: postgresql-libs libstdc++
OK: 586 MiB in 119 packages
### INSTALLING REMOTE MODULE swoole ###
  (installing version 4.8.7)
downloading swoole-4.8.7.tgz ...
Starting to download swoole-4.8.7.tgz (1,851,160 bytes)
................done: 65,536 bytes
ERROR: unable to unpack /tmp/pear/download/swoole-4.8.7.tgz

php版本 7.3.30

安装命令 install-php-extensions swoole-4.8.7

尝试过https://www.jianshu.com/p/4989df8431f1 这里面的办法 好像没用

**Comment by shmilylbelva** [comment]
dockerfile 增加 `RUN apk upgrade --no-cache && \
    apk add --no-cache  openssl libgcc libstdc++` 
#swoole需要libstdc++
