### ISSUE TITLE
为什么win10上安装dnmp，项目接口速度很慢

### ISSUE THREAD

**Issue by percy7788** [yeszao/dnmp#517]
为什么win10上安装dnmp，项目接口速度很慢，很奇怪

**Comment by percy7788** [comment]
还是本地项目

**Comment by LaoZhangRen** [comment]
是不是把代码放到了win  你把代码放到wsl（例如：/home/code/），别放到win映射到wsl的目录(例如：/d/code/)

**Comment by yeszao** [comment]
不同文件系统可能会导致这个问题。
