### ISSUE TITLE
希望再集成一个RocketMQ

### ISSUE THREAD

**Issue by yimisunrise** [yeszao/dnmp#518]
希望再集成一个RocketMQ

**Comment by ikaijian** [comment]
等到中，请问有集成了吗

**Comment by yimisunrise** [comment]
> 等到中，请问有集成了吗

我自己fork了一个，然后添加了rocketMQ， https://github.com/yimisunrise/dnmp

**Comment by yeszao** [comment]
暂不考虑 rocketMQ，可自行修改添加。
