### ISSUE TITLE
现在php装不了啊。

### ISSUE THREAD

**Issue by happyqian** [yeszao/dnmp#519]
![image](https://user-images.githubusercontent.com/3366947/193446385-46d3d5ea-3f96-4413-ba7a-1771b081625f.png)

**Comment by happyqian** [comment]
这种情况我查了下，网上好像没有这种答案，我估计是docker官方出了问题(我不确定,哈哈)，既然官方的有问题，那就试试国内镜像，找docker-compose.yml文件里的php那段定义(其它版本也一样): PHP_VERSION: php:${PHP80_VERSION}-fpm-alpine3.13 换成 PHP_VERSION: daocloud.io/library/php:${PHP80_VERSION}-fpm-alpine3.13 解决

**Comment by jingle-shi** [comment]
修改为国内镜像

**Comment by jingle-shi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
