### ISSUE TITLE
php(8.x,7.x?)安装swoole报错，以及安装swoole openssl，curl报错解决

### ISSUE THREAD

**Issue by taobali32** [yeszao/dnmp#521]
定位问题 应该是  install-php-extensions  出问题了

修复方法

找到php7.x版本安装swoole方法，（7 0  改成 8 0 ，php版本8.x的话修改8.x extensions/install.sh）
![image](https://user-images.githubusercontent.com/30717763/197452552-d286642e-3944-437b-892d-f21436b11cfe.png)

把swoole源码下载下来放在 extensions文件中(8.0的话， 注意源码zip是多压缩了一份外壳，需要下载下来解压进入文件夹在压缩，然后修改压缩包名字)

安装方法处理
![image](https://user-images.githubusercontent.com/30717763/197452826-6db767fa-2de6-4115-b8c3-d45b045dd540.png)

dockerfile更改
不要限制版本
![image](https://user-images.githubusercontent.com/30717763/197453044-ea776add-7f3f-46e5-b1f3-66a109d0e394.png)

然后开始安装。

不行换下源，最近阿里源不是很稳定

**Comment by jingmian** [comment]
已修复
