### ISSUE TITLE
php8/Dockerfile mac m1 下gnu-libiconv不能加版本号 RUN apk add gnu-libiconv 

### ISSUE THREAD

**Issue by phpluo** [yeszao/dnmp#522]
# 在mac m1 下gnu-libiconv不能加版本号 阿里云的源和中科大的都没有1.15-r3这个版本
可以改为
`
RUN apk add gnu-libiconv libstdc++ --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/edge/community/ --allow-untrusted
`

或者和默认php/Dockerfile下的一样

`
RUN apk add --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/v3.13/community/ gnu-libiconv=1.15-r3
`

我没有去运行过代码   只是编译的时候发现问题 改了是能编译通过的  #502 

`
 >  ERROR [dnmp-php8  9/12] RUN apk add gnu-libiconv=1.15-r3 libstdc++ --no-cache --repository 
 > http://mirrors.aliyun.com/alpine/edge/community/ --allow-untrusted                            54.7s
 >  [dnmp-php8  9/12] RUN apk add gnu-libiconv=1.15-r3 libstdc++ --no-cache --repository http://mirrors.aliyun.com/alpine/edge/community/ --allow-untrusted:
#0 0.319 fetch http://mirrors.aliyun.com/alpine/edge/community/aarch64/APKINDEX.tar.gz
#0 25.16 fetch https://mirrors.aliyun.com/alpine/v3.14/main/aarch64/APKINDEX.tar.gz
#0 35.35 fetch https://mirrors.aliyun.com/alpine/v3.14/community/aarch64/APKINDEX.tar.gz
#0 54.72 ERROR: unable to select packages:
#0 54.74   gnu-libiconv-1.17-r0:
#0 54.74     breaks: world[gnu-libiconv=1.15-r3]
------
failed to solve: executor failed running [/bin/sh -c apk add gnu-libiconv=1.15-r3 libstdc++ --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/edge/community/ --allow-untrusted]: exit code: 1`

<img width="1838" alt="image" src="https://user-images.githubusercontent.com/15026737/203258836-214010f3-603e-4aa3-abd0-577b6b6d32dd.png">

<img width="967" alt="image" src="https://user-images.githubusercontent.com/15026737/203260658-1fc8b5f1-0944-4424-a937-98e936dbdcce.png">

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/15026737/203259653-3d188b3b-176a-41e4-a73b-9d476cbb77e6.png">

**Comment by afu727** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by jingmian** [comment]
8.0以上版本已删除版本号，主要是镜像源它一直把旧的包都删除，不会一直长期在，所以比较矛盾
