### ISSUE TITLE
dnmp安装php扩展redis igbinary memcached xdebug swoole protobuf全部失败

### ISSUE THREAD

**Issue by vpanda666** [yeszao/dnmp#523]
PHP80_EXTENSIONS=pdo_mysql,pcntl,mysqli,mbstring,calendar,sockets,pdo_pgsql,gd,curl,snmp,tidy,gmp,imap,ldap,imagick,mcrypt,opcache,redis,xdebug,swoole,mongodb,igbinary,protobuf

dnmp安装php扩展redis igbinary memcached xdebug swoole protobuf全部失败
但是其他扩展安装成功，尝试了n²次，每次过程都是删除dnmp目录重新clone
尝试了不同的网络，包括vpn（香港，德国，日本）和本地网络都是无法安装，alpine版本也从3.12一直尝试到3.17，历时两天时间尝试

**Comment by vpanda666** [comment]
除了上述问题，还出现了新的问题，如下
=> ERROR [ 9/12] RUN apk add gnu-libiconv=1.15-r3 libstdc++ --no-cache --repository http://mirrors.ustc.edu.cn/a  2.0s
------
 > [ 9/12] RUN apk add gnu-libiconv=1.15-r3 libstdc++ --no-cache --repository http://mirrors.ustc.edu.cn/alpine/edge/community/ --allow-untrusted:
#13 0.531 fetch http://mirrors.ustc.edu.cn/alpine/edge/community/x86_64/APKINDEX.tar.gz
#13 1.099 fetch https://mirrors.ustc.edu.cn/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
#13 1.630 fetch https://mirrors.ustc.edu.cn/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
#13 1.946 ERROR: unable to select packages:
#13 1.985   gnu-libiconv-1.16-r0:
#13 1.985     breaks: world[gnu-libiconv=1.15-r3]
#13 1.985     satisfies: world[so:libiconv.so.2]
------
executor failed running [/bin/sh -c apk add gnu-libiconv=1.15-r3 libstdc++ --no-cache --repository http://${CONTAINER_PACKAGE_URL}/alpine/edge/community/ --allow-untrusted]: exit code: 1
ERROR: Service 'php80' failed to build : Build failed

**Comment by jingmian** [comment]
那是因为镜像源CND问题，你在`.env`文件中修改`CONTAINER_PACKAGE_URL`值就行了，有几个源地址可以选择的

**Comment by afu727** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
