### ISSUE TITLE
我想要安装php的yaf扩展，需要如何 操作呢？

### ISSUE THREAD

**Issue by dreaminto** [yeszao/dnmp#53]

**Comment by yeszao** [comment]
参考 `php72/Dockerfile` 文件中**redis**、**xdebug**扩展的安装

**Comment by sincez** [comment]
php5.6需要自己下载源文件，可以使用下列命令
COPY ./yaf-2.3.5.tgz /tmp/yaf.tgz
RUN ls /tmp
RUN mkdir -p /tmp/yaf \
    && tar -xf /tmp/yaf.tgz -C /tmp/yaf --strip-components=1 \
    && rm /tmp/yaf.tgz \
    && docker-php-ext-configure /tmp/yaf --enable-yaf \
    && docker-php-ext-install /tmp/yaf \
    && rm -r /tmp/yaf
php7以上的可以使用pecl安装
RUN pecl install yaf-3.0.7 \
    && docker-php-ext-enable yaf

**Comment by yeszao** [comment]
@sincez 正解。

pecl安装本来是一个很快捷的方式，不过因为国内网络原因，经常无法连接，所以现在pecl扩展都改从源码安装了，以确保100%可行。
