### ISSUE TITLE
2.1.0 的 env 配置扩展 build 不生效，只能使用 install-php-extensions 

### ISSUE THREAD

**Issue by lg970044** [yeszao/dnmp#530]
使用   Jan 13, 2023  的 commit 正常。

**Comment by lg970044** [comment]
把镜像删除后， .env 文件有写上了 xlswriter,yaml  这两个扩展， build 中没报什么错，但启动后，发现没装好。

再用  install-php-extensions  ，有时也装不成功，多试几次就装好了。没截图，失败原因 上次试， 一次是网络差 压缩包 没下完 ，中断报错了，  一次是 下载的文件 校验错误， 解压失败。

**Comment by jingmian** [comment]
因为`build`的时候`yaml`和`xlswriter`都是`pecl`方式安装，有时可能因为网络问题，安装不成功，所以后面构建再利用` install-php-extensions `就会再次尝试`pecl`安装，如果碰巧网络就安装上
