### ISSUE TITLE
Mysql启动失败

### ISSUE THREAD

**Issue by wen403** [yeszao/dnmp#531]
![image](https://user-images.githubusercontent.com/67454874/225233960-d0463bdd-403e-4d4d-b4ee-25fc95dd3de9.png)

**Comment by wen403** [comment]
### 目前临时解决办法
![image](https://user-images.githubusercontent.com/67454874/225243929-6151aa6e-f99e-43a6-a954-092b7a47ee81.png)

**Comment by dygin** [comment]
you could put this privileged: true into the node mysql: docker-compose.yml
