### ISSUE TITLE
mysql5  和 mysql8 启动失败

### ISSUE THREAD

**Issue by wqjohnston** [yeszao/dnmp#536]
mysql5         | [Entrypoint] Starting MySQL 5.7.28-1.1.13
mysql5 exited with code 1
mysql5         | [Entrypoint] Starting MySQL 5.7.28-1.1.13
mysql5 exited with code 1
mysql5         | [Entrypoint] Starting MySQL 5.7.28-1.1.13
mysql5 exited with code 1
mysql5         | [Entrypoint] Starting MySQL 5.7.28-1.1.13
mysql5 exited with code 1
mysql5         | [Entrypoint] Starting MySQL 5.7.28-1.1.13
mysql5 exited with code 1
mysql5         | [Entrypoint] Starting MySQL 5.7.28-1.1.13
mysql5 exited with code 1

**Comment by yeszao** [comment]
如果容器有修改，先把 `data/mysql5/*` 里面的文件删除掉，在重启。
