### ISSUE TITLE
修改 my.cnf  不生效 

### ISSUE THREAD

**Issue by Garbo1229** [yeszao/dnmp#539]
修改 my.cnf mysql8 或 mysql5 都未生效
配置文件完全没有被mysql使用

**Comment by shmilylbelva** [comment]
可以看看我的这篇文章 [https://www.jianshu.com/p/d15252f0cb58](https://www.jianshu.com/p/d15252f0cb58) 从3.2开始

**Comment by yeszao** [comment]
修改文件后需要重新启动 mysql 容器。
