### ISSUE TITLE
php.ini里面的output_buffering应该改成on

### ISSUE THREAD

**Issue by wisonlau** [yeszao/dnmp#540]
我在setcookie中遇到Cannot modify header information-headers already sent by错误,使用ob_start不生效,最后找到output_buffering发现有设置为4096,发现网上大多数人都说可以随便给一个值,最后我发现改成on才解决问题.

参考:http://www.yinxi.net/zt/show_17055.html

**Comment by jingmian** [comment]
`output_buffering = On`启用输出缓冲区，缓冲区大小由服务器自动决定。你可以尝试再把4096增大一点
