### ISSUE TITLE
php80安装swoole扩展不成功

### ISSUE THREAD

**Issue by WangQuanTang** [yeszao/dnmp#544]
在`.env`文件中的`PHP80_EXTENSIONS`添加`swoole`相关扩展：`pcntl`和`swoole`：
```
PHP80_EXTENSIONS=pdo_mysql,mysqli,mbstring,gd,curl,opcache,redis,mongodb,pcntl,swoole
```

使用指令重构PHP容器：
```
docker-compose build php80
```
卡在了下面安装扩展的`swoole扩展`这个步骤：

```
 => [ 5/12] RUN chmod +x install.sh     && sh install.sh     && rm -rf /tmp/extensions                          1146.6s
 => => # ions/swoole -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/
 => => # include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/tmp/extensions/swoole -
 => => # I/tmp/extensions/swoole/include -I/tmp/extensions/swoole/ext-src -I/tmp/extensions/swoole/thirdparty -I/tmp/ex
 => => # tensions/swoole/thirdparty/hiredis -DHAVE_CONFIG_H -g -O2 -Wall -Wno-unused-function -Wno-deprecated -Wno-depr
 => => # ecated-declarations -std=c++11 -DENABLE_PHP_SWOOLE -c /tmp/extensions/swoole/ext-src/swoole_coroutine.cc  -fPI
 => => # C -DPIC -o ext-src/.libs/swoole_coroutine.o

```
![image](https://github.com/yeszao/dnmp/assets/52555689/0680d459-b60c-4141-981c-efa7aca2c83b)

修改`CONTAINER_PACKAGE_URL`源为阿里云、163和mirrors.ustc.edu.cn也是卡在这个地方。在`\dnmp\services\php80\extensions`中替换swoole扩展：`swoole-5.0.2.tgz`，也是无法动弹。

在查看了`install.sh`和`install-php-extensions`也没找到有任何问题的地方。

使用指令`install-php-extensions`安装显示成功，但是查看php扩展的时候依然是没有`swoole`扩展。

请问这个如何解决。

**Comment by shmilylbelva** [comment]
科学上网能够解决

**Comment by shmilylbelva** [comment]
另外 如果报 `Warning: PHP Startup: Unable to load dynamic library 'swoole' (tried: /usr/local/lib/php/extensions/no-debug-non-zts-20210902/swoole (Error loading shared library /usr/local/lib/ph
p/extensions/no-debug-non-zts-20210902/swoole: No such file or directory), /usr/local/lib/php/extensions/no-debug-non-zts-20210902/swoole.so (Error loading shared library libstdc++.so.6: No
 such file or directory (needed by /usr/local/lib/php/extensions/no-debug-non-zts-20210902/swoole.so))) in Unknown on line 0`
 修改dockerfile ,增加 `RUN apk upgrade --no-cache && \
    apk add --no-cache  openssl libgcc libstdc++` 和 `RUN install-php-extensions swoole pcntl`

**Comment by WangQuanTang** [comment]
> 科学上网能够解决

非常感谢
