### ISSUE TITLE
 docker-compose up

### ISSUE THREAD

**Issue by Xuzan9396** [yeszao/dnmp#56]
alpine: Pulling from library/nginx
ERROR: no matching manifest for unknown in the manifest list entries
[root@localhost dnmp]# docker-compose -f docker-compose56.yml up -d
Pulling nginx (nginx:alpine)...
alpine: Pulling from library/nginx
alpine: Pulling from library/nginx
ERROR: no matching manifest for unknown in the manifest list entries

**Comment by yeszao** [comment]
这估计是网络原因，参考我的博客中的这一节《使用国内镜像仓库》：https://www.awaimai.com/2120.html#3

**Comment by Xuzan9396** [comment]
我换成最新的nginx镜像就好了
