### ISSUE TITLE
imagick扩展安装失败

### ISSUE THREAD

**Issue by xuanyue0522** [yeszao/dnmp#563]
install-php-extensions imagick
install-php-extensions v.2.1.35
#StandWithUkraine
Updating channel "pecl.php.net"
Update of Channel "pecl.php.net" succeeded
fetch http://mirrors.aliyun.com/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.aliyun.com/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
v3.8.5-67-gf94de196ca [http://mirrors.aliyun.com/alpine/v3.8/main]
v3.8.5-66-gccbd6a8ae7 [http://mirrors.aliyun.com/alpine/v3.8/community]
OK: 9572 distinct packages available
### INSTALLING REQUIRED PACKAGES ###
# Packages to be kept after installation: libxrender pixman cairo libffi libintl libuuid libblkid libmount pcre glib dbus-libs avahi-libs gmp nettle p11-kit libtasn1 libunistring gnutls cups-libs jbig2dec tiff ghostscript libxft graphite2 harfbuzz pango libcroco shared-mime-info gdk-pixbuf librsvg imagemagick libgomp
# Packages to be used only for installation: m4 perl autoconf dpkg dpkg-dev file binutils isl libatomic mpfr3 mpc1 gcc musl-dev libc-dev g++ make
(1/48) Installing m4 (1.4.18-r1)
(2/48) Installing perl (5.26.3-r0)
(3/48) Installing autoconf (2.69-r2)
(4/48) Installing dbus-libs (1.10.28-r0)
(5/48) Installing libintl (0.19.8.1-r2)
(6/48) Installing avahi-libs (0.7-r2)
(7/48) Installing binutils (2.30-r6)
(8/48) Installing libxrender (0.9.10-r2)
(9/48) Installing pixman (0.34.0-r5)
(10/48) Installing cairo (1.14.12-r2)
(11/48) Installing gmp (6.1.2-r1)
(12/48) Installing nettle (3.4.1-r0)
(13/48) Installing libffi (3.2.1-r4)
(14/48) Installing p11-kit (0.23.10-r0)
(15/48) Installing libtasn1 (4.14-r0)
(16/48) Installing libunistring (0.9.7-r0)
(17/48) Installing gnutls (3.6.14-r0)
(18/48) Installing cups-libs (2.2.12-r0)
(19/48) Installing dpkg (1.18.24-r0)
(20/48) Installing dpkg-dev (1.18.24-r0)
(21/48) Installing file (5.32-r2)
(22/48) Installing isl (0.18-r0)
(23/48) Installing libgomp (6.4.0-r9)
(24/48) Installing libatomic (6.4.0-r9)
(25/48) Installing mpfr3 (3.1.5-r1)
(26/48) Installing mpc1 (1.0.3-r1)
(27/48) Installing gcc (6.4.0-r9)
(28/48) Installing musl-dev (1.1.19-r11)
(29/48) Installing libc-dev (0.7.1-r0)
(30/48) Installing g++ (6.4.0-r9)
(31/48) Installing libuuid (2.32-r0)
(32/48) Installing libblkid (2.32-r0)
(33/48) Installing libmount (2.32-r0)
(34/48) Installing pcre (8.42-r0)
(35/48) Installing glib (2.56.1-r1)
(36/48) Installing shared-mime-info (1.9-r0)
(37/48) Installing tiff (4.0.10-r3)
(38/48) Installing gdk-pixbuf (2.36.11-r2)
(39/48) Installing jbig2dec (0.14-r0)
(40/48) Installing ghostscript (9.26-r4)
(41/48) Installing graphite2 (1.3.11-r1)
(42/48) Installing harfbuzz (1.7.6-r1)
(43/48) Installing libxft (2.3.2-r2)
(44/48) Installing pango (1.40.14-r1)
(45/48) Installing libcroco (0.6.12-r2)
(46/48) Installing librsvg (2.40.21-r0)
(47/48) Installing imagemagick (7.0.8.68-r0)
(48/48) Installing make (4.2.1-r2)
Executing busybox-1.28.4-r3.trigger
Executing fontconfig-2.12.6-r1.trigger
Executing glib-2.56.1-r1.trigger
Executing shared-mime-info-1.9-r0.trigger
Executing gdk-pixbuf-2.36.11-r2.trigger
OK: 310 MiB in 108 packages
### INSTALLING REMOTE MODULE imagick ###
**No releases available for package "pecl.php.net/imagick"
install failed**

**Comment by jingmian** [comment]
你安装的php是什么版本

**Comment by xuanyue0522** [comment]
php8.1和php5.6

**Comment by Garbo1229** [comment]
https://github.com/yeszao/dnmp/pull/568 你试下这个
