### ISSUE TITLE
新手求怎么切换版本谢谢

### ISSUE THREAD

**Issue by JackeyLov5** [yeszao/dnmp#564]
按照教程去除了 docker-compose.yml 中 php54 代码块注释 
启动
`➜ docker-compose up -d
[+] Building 6.9s (6/12)                                           docker:desktop-linux
 => [php54 internal] load build definition from Dockerfile                         0.0s
 => => transferring dockerfile: 930B                                               0.0s
 => [php54 internal] load .dockerignore                                            0.0s
 => => transferring context: 2B                                                    0.0s
 => [php54 internal] load metadata for docker.io/library/php:5.4.45-fpm            3.0s
 => CACHED [php54 1/8] FROM docker.io/library/php:5.4.45-fpm@sha256:b8e42519a65cf  0.2s
 => => resolve docker.io/library/php:5.4.45-fpm@sha256:b8e42519a65cf21787c1662c71  0.2s
 => [php54 internal] load build context                                            0.0s
 => => transferring context: 456B                                                  0.0s
 => ERROR [php54 2/8] RUN sed -i "s/httpredir.debian.org/mirrors.ustc.edu.cn/g" /  3.6s
------
 > [php54 2/8] RUN sed -i "s/httpredir.debian.org/mirrors.ustc.edu.cn/g" /etc/apt/sources.list     && sed -i "s/security.debian.org/mirrors.ustc.edu.cn\/debian-security/g" /etc/apt/sources.list     && apt-get update:
1.564 Ign http://mirrors.ustc.edu.cn jessie InRelease
1.653 Ign http://mirrors.ustc.edu.cn jessie-updates InRelease
1.753 Ign http://mirrors.ustc.edu.cn jessie/updates InRelease
1.844 Ign http://mirrors.ustc.edu.cn jessie Release.gpg
1.949 Ign http://mirrors.ustc.edu.cn jessie-updates Release.gpg
2.045 Ign http://mirrors.ustc.edu.cn jessie/updates Release.gpg
2.132 Ign http://mirrors.ustc.edu.cn jessie Release
2.229 Ign http://mirrors.ustc.edu.cn jessie-updates Release
2.330 Ign http://mirrors.ustc.edu.cn jessie/updates Release
3.422 Err http://mirrors.ustc.edu.cn jessie/main amd64 Packages
3.422   404  Not Found
3.527 Err http://mirrors.ustc.edu.cn jessie-updates/main amd64 Packages
3.527   404  Not Found
3.614 Err http://mirrors.ustc.edu.cn jessie/updates/main amd64 Packages
3.614   404  Not Found
3.617 W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/jessie/main/binary-amd64/Packages  404  Not Found
3.617
3.617 W: Failed to fetch http://mirrors.ustc.edu.cn/debian/dists/jessie-updates/main/binary-amd64/Packages  404  Not Found
3.617
3.617 W: Failed to fetch http://mirrors.ustc.edu.cn/debian-security/dists/jessie/updates/main/binary-amd64/Packages  404  Not Found
3.617
3.617 E: Some index files failed to download. They have been ignored, or old ones used instead.
------
failed to solve: process "/bin/sh -c sed -i \"s/httpredir.debian.org/${CONTAINER_PACKAGE_URL}/g\" /etc/apt/sources.list     && sed -i \"s/security.debian.org/${CONTAINER_PACKAGE_URL}\\/debian-security/g\" /etc/apt/sources.list     && apt-get update" did not complete successfully: exit code: 100`
请问大哥们这是怎么回事呢 看报错应该是源的问题 或者怎么解决。。谢谢

**Comment by yeszao** [comment]
应该是网络问题，在`.env`里面修改源看看。
