### ISSUE TITLE
建议加上php8.2，并修复php8安装扩展失效的问题

### ISSUE THREAD

**Issue by xiahuan710** [yeszao/dnmp#571]
非常感谢作者提供这么优秀的作品，希望作者能加上php8.2，php在env文件里开启了扩展，build镜像依然没有扩展，只有默认的一些扩展

**Comment by jingmian** [comment]
只需要在`env`中，把php版本修改`8.2`，开启扩展构建可以不要一次性全部加上，先加上一部分构建，观察是否有报错提示

**Comment by xiahuan710** [comment]
> 只需要在`env`中，把php版本修改`8.2`，开启扩展构建可以不要一次性全部加上，先加上一部分构建，观察是否有报错提示

其他的扩展可以，唯独imagick在php8.0里装不上

**Comment by jeeinn** [comment]
我的 .env 配置 PHP80_VERSION=8.2.13 后，发现没有 gd 
7.4的默认配置是有 gd 的

临时解决就` install-php-extensions gd`

**Comment by jingmian** [comment]
@xiahuan710 imagick今天已经修复好，请测试看看
