### ISSUE TITLE
php56, redis扩展死活安装不上

### ISSUE THREAD

**Issue by LeftH0ok** [yeszao/dnmp#572]
安装方式修改.env,  docker-compose build php56

搜了其他issue未解决

---------- Install redis ----------
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
[91mexpr: syntax error
[0m[91m./configure: line 2547: test: =: unary operator expected
[0mchecking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
checking for gawk... no
checking for nawk... no
checking for awk... [91mconfigure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
[0mawk
checking if awk is broken... no
checking whether to enable redis support... yes, shared
checking whether to enable sessions... yes
checking whether to enable json serializer support... yes
checking whether to enable igbinary serializer support... no
checking whether to enable msgpack serializer support... no
checking whether to enable lzf compression... no
checking use system liblzf... no
checking whether to enable Zstd compression... no
checking use system libsztd... yes
checking whether to enable lz4 compression... no
checking use system liblz4... no
checking for hash includes... /usr/local/include/php
checking for json includes... /usr/local/include/php
checking for redis json support... enabled
checking for redis igbinary support... disabled
checking for pkg-config... /usr/bin/pkg-config
checking for git... no
checking for ld used by cc... /usr/x86_64-alpine-linux-musl/bin/ld
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
[91m./configure: line 6935: /usr/bin/file: No such file or directory
[0mchecking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 98304
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/x86_64-alpine-linux-musl/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
/bin/bash /tmp/extensions/redis/libtool --mode=compile cc  -I. -I/tmp/extensions/redis -DPHP_ATOM_INC -I/tmp/extensions/redis/include -I/tmp/extensions/redis/main -I/tmp/extensions/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext  -DHAVE_CONFIG_H  -g -O2   -c /tmp/extensions/redis/redis.c -o redis.lo 
/bin/bash /tmp/extensions/redis/libtool --mode=compile cc  -I. -I/tmp/extensions/redis -DPHP_ATOM_INC -I/tmp/extensions/redis/include -I/tmp/extensions/redis/main -I/tmp/extensions/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext  -DHAVE_CONFIG_H  -g -O2   -c /tmp/extensions/redis/redis_commands.c -o redis_commands.lo 
mkdir .libs
 cc -I. -I/tmp/extensions/redis -DPHP_ATOM_INC -I/tmp/extensions/redis/include -I/tmp/extensions/redis/main -I/tmp/extensions/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext -DHAVE_CONFIG_H -g -O2 -c /tmp/extensions/redis/redis_commands.c  -fPIC -DPIC -o .libs/redis_commands.o
 cc -I. -I/tmp/extensions/redis -DPHP_ATOM_INC -I/tmp/extensions/redis/include -I/tmp/extensions/redis/main -I/tmp/extensions/redis -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/include/php/ext -DHAVE_CONFIG_H -g -O2 -c /tmp/extensions/redis/redis.c  -fPIC -DPIC -o .libs/redis.o
[91mIn file included from /tmp/extensions/redis/redis_commands.h:4:0,
                 from /tmp/extensions/redis/redis_commands.c:23:
/tmp/extensions/redis/common.h:12:28: fatal error: zend_smart_str.h: No such file or directory
 #include <zend_smart_str.h>
                            ^
compilation terminated.
In file included from /tmp/extensions/redis/php_redis.h:20:0,
                 from /tmp/extensions/redis/redis.c:25:
/tmp/extensions/redis/common.h:12:28: fatal error: zend_smart_str.h: No such file or directory
 #include <zend_smart_str.h>
                            ^
compilation terminated.
[0m[91mmake: *** [Makefile:181: redis.lo] Error 1
make: *** Waiting for unfinished jobs....
[0m[91mmake: *** [Makefile:183: redis_commands.lo] Error 1
[0m[91merror: 'redis' does not exist

usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc

Possible values for module-name:
[0m[91mbcmath.so gd.so mysqli.so opcache.so pdo_mysql.so
[0m[91m
Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
[0m---------- Install mongodb ----------
fetch http://mirrors.ustc.edu.cn/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://mirrors.ustc.edu.cn/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
[91mERROR: unsatisfiable constraints:
[0m  libressl-dev-2.7.5-r0:
    conflicts:
               openssl-dev-1.0.2u-r0[pc:libcrypto=2.7.5]
               openssl-dev-1.0.2u-r0[pc:libssl=2.7.5]
               openssl-dev-1.0.2u-r0[pc:openssl=2.7.5]
    satisfies: curl-dev-7.61.1-r3[libressl-dev]
               libssh2-dev-1.9.0-r1[pc:libcrypto]
               libssh2-dev-1.9.0-r1[pc:libssl]
  openssl-dev-1.0.2u-r0:
    conflicts:
               libressl-dev-2.7.5-r0[pc:libcrypto=1.0.2u]
               libressl-dev-2.7.5-r0[pc:libssl=1.0.2u]
               libressl-dev-2.7.5-r0[pc:openssl=1.0.2u]
    satisfies: world[openssl-dev]
               libssh2-dev-1.9.0-r1[pc:libcrypto]
               libssh2-dev-1.9.0-r1[pc:libssl]
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
[91mexpr: syntax error
[0m[91m./configure: line 2903: test: =: unary operator expected
[0mchecking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /usr/local
checking for PHP includes... -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /usr/local/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
checking for gawk... [91mconfigure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
[0mno
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable MongoDB support... yes, shared
checking PHP version... 5.6.40
checking whether to enable developer build flags... no
[91m./configure: line 4503: test: : integer expression expected
[0mchecking whether to enable code coverage... no
checking whether to compile against system libraries instead of bundled... no
checking whether to use system libbson... no
checking whether to use system libmongoc... no
checking whether to enable client-side encryption... auto
checking for gcc... (cached) cc
checking whether we are using the GNU C compiler... (cached) yes
checking whether cc accepts -g... (cached) yes
checking for cc option to accept ISO C89... (cached) none needed
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking accept ARG2 => struct sockaddr ARG3 => socklen_t ... ok
checking for an ANSI C-conforming const... yes
checking for inline... inline
checking for typeof syntax and keyword spelling... typeof
checking for __sync_add_and_fetch_4... yes
checking for __sync_add_and_fetch_8... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for strings.h... (cached) yes
checking whether byte ordering is bigendian... no
checking for strnlen... yes
checking for reallocf... no
checking for syscall... yes
checking for SYS_gettid... yes
checking for snprintf... yes
checking for strlcpy... yes
checking for struct timespec... yes
checking for library containing clock_gettime... none required
checking for library containing floor... none required
checking for gmtime_r... yes
checking for rand_r... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... yes
checking whether PTHREAD_ONCE_INIT needs braces... no
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for PHP_MONGODB_SNAPPY... no
checking for snappy_uncompress in -lsnappy... no
checking snappy-c.h usability... no
checking snappy-c.h presence... no
checking for snappy-c.h... no
checking for PHP_MONGODB_ZLIB... yes
checking for res_nsearch... no
checking for res_search... yes
checking whether to enable SASL for Kerberos authentication... auto
checking for PHP_MONGODB_SASL... no
checking for sasl_client_init in -lsasl2... no
checking sasl/sasl.h usability... no
checking sasl/sasl.h presence... no
checking for sasl/sasl.h... no
checking which SASL library to use... no
checking whether to enable crypto and TLS... auto
checking deprecated option for OpenSSL library path... auto
configure: checking whether OpenSSL is available
checking for PHP_MONGODB_SSL... yes
checking whether ASN1_STRING_get0_data is declared... yes
checking which TLS library to use... openssl
checking whether to use system crypto profile... no
checking deprecated option for whether to use system crypto profile... no
checking whether to enable ICU for SASLPrep with SCRAM-SHA-256 authentication... auto
checking for PHP_MONGODB_ICU... no
checking for shm_open... yes
checking for sched_getcpu... yes
checking for socklen_t... yes
checking for struct sockaddr_storage.ss_family... yes
checking if compiler needs -Werror to reject unknown flags... no
checking for the pthreads library -lpthreads... no
checking whether pthreads work without any flags... yes
checking for joinable pthread attribute... PTHREAD_CREATE_JOINABLE
checking if more special flags are required for pthreads... no
checking for PTHREAD_PRIO_INHERIT... (cached) yes
checking if weak symbols are supported... yes
checking which crypto library to use for libmongocrypt... openssl
checking for ld used by cc... /usr/x86_64-alpine-linux-musl/bin/ld
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking for /usr/x86_64-alpine-linux-musl/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
[91m./configure: line 18286: /usr/bin/file: No such file or directory
[0mchecking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 98304
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/x86_64-alpine-linux-musl/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
checking for ld used by g++... /usr/x86_64-alpine-linux-musl/bin/ld
checking if the linker (/usr/x86_64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld) supports shared libraries... yes
checking for g++ option to produce PIC... -fPIC
checking if g++ PIC flag -fPIC works... yes
checking if g++ static flag -static works... yes
checking if g++ supports -c -o file.o... yes
checking whether the g++ linker (/usr/x86_64-alpine-linux-musl/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
(cached) (cached) checking how to hardcode library paths into programs... immediate
configure: creating ./config.status

mongodb was configured with the following options:

Build configuration:
  CFLAGS                                           : -g -O2
  Extra CFLAGS                                     :  
  Developers flags (slow)                          : 
  Code Coverage flags (extra slow)                 : 
  System libmongoc                                 : no
  System libbson                                   : no
  System libmongocrypt                             : no
  LDFLAGS                                          :

**Comment by jingmian** [comment]
sorry,在`yml`漏了修改`php56`的构建名称，已修复，拉取最新版尝试一下
