### ISSUE TITLE
docker compose up 报错 Permission denied

### ISSUE THREAD

**Issue by gelcaas** [yeszao/dnmp#574]
=> ERROR [ 2/12] RUN if [ mirrors.aliyun.com ] ; then sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repos  0.3s
------
 > [ 2/12] RUN if [ mirrors.aliyun.com ] ; then sed -i "s/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g" /etc/apk/repositories ; fi:
#0 0.303 sed: can't create temp file '/etc/apk/repositoriesXXXXXX': Permission denied

**Comment by yeszao** [comment]
已修复：https://github.com/yeszao/dnmp/commit/bf71f5175177c71e7124223c373550cef884a482
