### ISSUE TITLE
imagick的扩展在php80上怎样装都装不上

### ISSUE THREAD

**Issue by xiahuan710** [yeszao/dnmp#577]
php81 82  74，经过修改都可以正常安装了，希望作者能自己试试php80的imagick的扩展，是在.env里配置build镜像那种方法，exec进入容器后有概率可以安装成功。

**Comment by jefferyjob** [comment]
我也是这个问题

**Comment by xiahuan710** [comment]
> 我也是这个问题

可以装，作者自带的安装方法写的有错，改个方法就可以
`if [[ -z "${EXTENSIONS##*,imagick,*}" ]]; then
    echo "---------- Install imagick ----------"
#   apk add --no-cache file-dev
#   apk add --no-cache imagemagick-dev
#    printf "\n" | pecl install imagick
#    apk add --no-cache autoconf g++ make
    apk add --update --no-cache autoconf g++ file-dev imagemagick imagemagick-dev libtool make pcre-dev
    printf "\n" | pecl install imagick
    docker-php-ext-enable imagick
fi`

**Comment by xiahuan710** [comment]
`
if [[ -z "${EXTENSIONS##*,imagick,*}" ]]; then
    echo "---------- Install imagick ----------"
#   apk add --no-cache file-dev
#   apk add --no-cache imagemagick-dev
#    printf "\n" | pecl install imagick
#    apk add --no-cache autoconf g++ make
    apk add --update --no-cache autoconf g++ file-dev imagemagick imagemagick-dev libtool make pcre-dev
    printf "\n" | pecl install imagick
    docker-php-ext-enable imagick
fi
`

**Comment by xiahuan710** [comment]
`if [[ -z "${EXTENSIONS##*,imagick,*}" ]]; then
    echo "---------- Install imagick ----------"
#   apk add --no-cache file-dev
#   apk add --no-cache imagemagick-dev
#    printf "\n" | pecl install imagick
#    apk add --no-cache autoconf g++ make
    apk add --update --no-cache autoconf g++ file-dev imagemagick imagemagick-dev libtool make pcre-dev
    printf "\n" | pecl install imagick
    docker-php-ext-enable imagick
fi`

**Comment by jingmian** [comment]
已修复，拉取最新版试试
