### ISSUE TITLE
nginx.conf的问题

### ISSUE THREAD

**Issue by xiahuan710** [yeszao/dnmp#578]
在service/nginx 目录下nginx.conf不起作用，起作用的是容器内的nginx.conf，conf.d/ 目录下的配置文件是可以在容器外使用的

**Comment by SemiThin** [comment]
都已经映射了，不可能不起作用，- ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
修改后请重载配置文件

docker-compose exec nginx nginx -s reload

**Comment by xiahuan710** [comment]
> 都已经映射了，不可能不起作用，- ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro 修改后请重载配置文件
> 
> docker-compose exec nginx nginx -s reload

nginx.conf是只读文件（ro），除非build，reload是不能改变配置文件的，需要改成可读写（rw）

**Comment by yeszao** [comment]
> > 都已经映射了，不可能不起作用，- ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro 修改后请重载配置文件
> > docker-compose exec nginx nginx -s reload
> 
> nginx.conf是只读文件（ro），除非build，reload是不能改变配置文件的，需要改成可读写（rw）

`rw`意思是不能在容器中修改配置，在主机中修改再`reload`是可以正常加载的。
