### ISSUE TITLE
怎么安装Memcached扩展

### ISSUE THREAD

**Issue by jiayuan2018** [yeszao/dnmp#58]
装不上Memcached扩展啊 ， 依赖的libmemcached用apt-get install libmemcached  提示找不到

**Comment by yeszao** [comment]
```
RUN apt-get install -y libmemcached-dev zlib1g-dev \
    && pecl install memcached-2.2.0 \
    && docker-php-ext-enable memcached
```
版本按需要选定

**Comment by shenyong12345** [comment]
php 扩展 怎么安装xhprof  我是脚本写在这里吗 但是报错  /root/dnmp/extensions/install.sh
docker-compose build不行
