### ISSUE TITLE
安装报错了，修改了yml文件里的端口重新拉取还是一样报错

### ISSUE THREAD

**Issue by kevon2019** [yeszao/dnmp#581]
Error response from daemon: driver failed programming external connectivity on endpoint nginx (728d62aa65c5001c1619d610cc2bd6af5d30f8b63b31f6bf97067c7252bf3f4c): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

**Comment by jingmian** [comment]
日志很明显，Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use，提示你有一个80端口被占用，Nginx无法启动
