### ISSUE TITLE
php8.3有计划么？

### ISSUE THREAD

**Issue by cjango** [yeszao/dnmp#582]
php8.3有计划么？

**Comment by jingmian** [comment]
只要在`.env`里面修改为php8.3版本，也是可以用的，

**Comment by jingmian** [comment]
只要在`.env`里面修改为php8.3版本，也是可以用的，

**Comment by xiahuan710** [comment]
是可以用，但是pecl装不上imagick，只能用编译装了

**Comment by jingmian** [comment]
关于`imagick`上两个星期我已经修复了，在`sh`脚本是通过编译安装，在php8版本以上，暂时无法通过pecl安装的
