### ISSUE TITLE
docker-compose up -d

### ISSUE THREAD

**Issue by zonghua-hu** [yeszao/dnmp#590]
Building nginx
Step 1/10 : ARG NGINX_VERSION
ERROR: Service 'nginx' failed to build: Please provide a source image with `from` prior to commit

**Comment by jingmian** [comment]
有可能你docker 版本比较低，我这里重新拉取最新版，可以正常构建

**Comment by zonghua-hu** [comment]
谢谢大佬，更新我的docker后，可以正常构建成功~再次感谢
