### ISSUE TITLE
Redis服务器版本：Connection refused

### ISSUE THREAD

**Issue by iYting** [yeszao/dnmp#596]
一个很诡异的问题。redis无法连接，所有容器用的都是同一个网络，在容器内能互相ping通 ，但是index.php 代码里无法连接

**Comment by jeeinn** [comment]
php 连接配置 要用容器名称连接

**Comment by humengcn** [comment]
@iYting 出现了同样的问题，容器之间可以 ping 通，但是在 php 容器内连不上 redis，提示：Connection refused

![微信截图_20240822182502](https://github.com/user-attachments/assets/df452a4a-f29a-495f-8993-65cd54ff0086)

**Comment by nangongchunshui** [comment]
> @iYting 出现了同样的问题，容器之间可以 ping 通，但是在 php 容器内连不上 redis，提示：Connection refused
> 
> ![微信截图_20240822182502](https://private-user-images.githubusercontent.com/9284625/360392189-df452a4a-f29a-495f-8993-65cd54ff0086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDE1MTcsIm5iZiI6MTczMTM0MTIxNywicGF0aCI6Ii85Mjg0NjI1LzM2MDM5MjE4OS1kZjQ1MmE0YS1mMjlhLTQ5NWYtODk5My02NWNkNTRmZjAwODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMTYwNjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUzMDYyZjJjZmEyYmMyYmQ1ZWI3NTdjZTRlMGVkMGRlNGI2YmJmMmIwNzEyMmI5MDEyNjg5ZGY4NGVhZDdjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ALccrQRaWgL-CGnHFreGLk4iQHqTDlmzGGwpLo433Fs)

请问下，解决了吗？我设置了密码，也是无法通过容器名称连接

**Comment by nigiwen** [comment]
> > @iYting 出现了同样的问题，容器之间可以 ping 通，但是在 php 容器内连不上 redis，提示：Connection refused
> > ![微信截图_20240822182502](https://private-user-images.githubusercontent.com/9284625/360392189-df452a4a-f29a-495f-8993-65cd54ff0086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDE1MTcsIm5iZiI6MTczMTM0MTIxNywicGF0aCI6Ii85Mjg0NjI1LzM2MDM5MjE4OS1kZjQ1MmE0YS1mMjlhLTQ5NWYtODk5My02NWNkNTRmZjAwODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMTYwNjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUzMDYyZjJjZmEyYmMyYmQ1ZWI3NTdjZTRlMGVkMGRlNGI2YmJmMmIwNzEyMmI5MDEyNjg5ZGY4NGVhZDdjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ALccrQRaWgL-CGnHFreGLk4iQHqTDlmzGGwpLo433Fs)
> 
> 请问下，解决了吗？我设置了密码，也是无法通过容器名称连接

我也遇到了这个问题，我改了端口和加了密码，请问你解决了吗

**Comment by nigiwen** [comment]
> > > @iYting 出现了同样的问题，容器之间可以 ping 通，但是在 php 容器内连不上 redis，提示：Connection refused
> > > ![微信截图_20240822182502](https://private-user-images.githubusercontent.com/9284625/360392189-df452a4a-f29a-495f-8993-65cd54ff0086.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDE1MTcsIm5iZiI6MTczMTM0MTIxNywicGF0aCI6Ii85Mjg0NjI1LzM2MDM5MjE4OS1kZjQ1MmE0YS1mMjlhLTQ5NWYtODk5My02NWNkNTRmZjAwODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMTFUMTYwNjU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGUzMDYyZjJjZmEyYmMyYmQ1ZWI3NTdjZTRlMGVkMGRlNGI2YmJmMmIwNzEyMmI5MDEyNjg5ZGY4NGVhZDdjZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ALccrQRaWgL-CGnHFreGLk4iQHqTDlmzGGwpLo433Fs)
> > 
> > 
> > 请问下，解决了吗？我设置了密码，也是无法通过容器名称连接
> 
> 我也遇到了这个问题，我改了端口和加了密码，请问你解决了吗

我明白怎么个事了，工具链接是通过宿主机链接的也就映射出来的端口，而php链接是容器之间的链接，所以容器之间访问用的还是redis容器里的6379端口
