### ISSUE TITLE
php5.4 已经在最新版本 docker 无法拉取

### ISSUE THREAD

**Issue by mtgq** [yeszao/dnmp#599]
[DEPRECATION NOTICE] Docker Image Format v1 and Docker Image manifest version 2, schema 1 support is disabled by default and will be removed in an upcoming release. Suggest the author of docker.io/library/php:5.4.45-fpm to upgrade the image to the OCI Format or Docker Image manifest v2, schema 2. More information at https://docs.docker.com/go/deprecated-image-specs/

提示错误如下

**Comment by jingmian** [comment]
你的docker版本应该是高于26的，要在docker 24版本以下才能拉取了，php5.4镜像源作者很多久没有更新的。
解决方法，在老版本的docker下pull该镜像或者你可以在一台云服务器上安装旧版docker，然后pull，接着打一个标签,push到自已私有镜像库，就可以拉取

**Comment by mtgq** [comment]
> 你的docker版本应该是高于26的，要在docker 24版本以下才能拉取了，php5.4镜像源作者很多久没有更新的。 解决方法，在老版本的docker下pull该镜像或者你可以在一台云服务器上安装旧版docker，然后pull，接着打一个标签,push到自已私有镜像库，就可以拉取

对的，我用的最新版本的docker，我是给作者说下
