### ISSUE TITLE
MacOS M系列compose报错

### ISSUE THREAD

**Issue by huangzhuohua** [yeszao/dnmp#601]
`
% docker-compose up
WARN[0000] /Users/xyz/Documents/Docker/dnmp/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion 
[+] Running 2/2
 ✘ mysql5 Error no match for platform in manifest: not fo...               2.8s 
 ✘ mysql Error  context canceled                                           2.8s 
**Error response from daemon: no match for platform in manifest: not found**

`

**Comment by jingmian** [comment]
M1暂时没有合适的mysql5.7版本,建议你用mysql8
