### ISSUE TITLE
请问可以编译添加Mysql扩展吗

### ISSUE THREAD

**Issue by jingmian** [yeszao/dnmp#61]
在php54和php56没有mysql扩展，我该如何编译进去

**Comment by yeszao** [comment]
**_Dockerfile_**的`RUN`中加一行：
```
docker-php-ext-install mysql
```
虽然老版本还可以用mysql扩展，不过建议改用用`mysqli`或者`pdo_mysql`为妥
毕竟，`mysql`扩展从PHP5.5.0开始被废弃，PHP7.0.0被移除了。

**Comment by jingmian** [comment]
@yeszao 这个我明白，有时候维护陈旧的代码需要。
另外我还想咨询下  我在docker-compose.yml配置文件修改
 mysql:
    image: mysql:5.7
    MYSQL_ROOT_PASSWORD: "root"
但我重启docker后，发现密码为何依然是123456？

**Comment by yeszao** [comment]
@jingmian 镜像构建后就密码就定下来了，docker-compose.yml 是构建的时候有用，下次up直接从image读了，要修改密码可以重新构建，或者登录MySQL修改密码。
