### ISSUE TITLE
请问鉴权失败是什么原因啊

### ISSUE THREAD

**Issue by menghongwen** [yeszao/dnmp#610]
#3 [php82 internal] load metadata for docker.io/library/php:8.2-fpm
#3 ...

#4 [nginx auth] library/nginx:pull token for registry-1.docker.io
#4 DONE 0.0s

#5 [php82 auth] library/php:pull token for registry-1.docker.io
#5 DONE 0.0s

#6 [nginx internal] load metadata for docker.io/library/nginx:1.26-alpine
#6 ...

#3 [php82 internal] load metadata for docker.io/library/php:8.2-fpm
#3 ERROR: failed to authorize: failed to fetch oauth token: Post "https://auth.docker.io/token": dial tcp [2a03:2880:f12a:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

#6 [nginx internal] load metadata for docker.io/library/nginx:1.26-alpine
#6 ERROR: failed to authorize: failed to fetch oauth token: Post "https://auth.docker.io/token": dial tcp [2a03:2880:f12a:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
------
 > [php82 internal] load metadata for docker.io/library/php:8.2-fpm:
------
------
 > [nginx internal] load metadata for docker.io/library/nginx:1.26-alpine:
------
failed to solve: nginx:1.26-alpine: failed to resolve source metadata for docker.io/library/nginx:1.26-alpine: failed to authorize: failed to fetch oauth token: Post "https://auth.docker.io/token": dial tcp [2a03:2880:f12a:83:face:b00c:0:25de]:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by afu727** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by menghongwen** [comment]
win10环境, docker也登陆了, 也挂了vpn, 浏览器访问https://auth.docker.io/token也没有问题

**Comment by menghongwen** [comment]
换源之后解决问题, 打扰了
