### ISSUE TITLE
咋搞啊

### ISSUE THREAD

**Issue by tuzisir** [yeszao/dnmp#65]
[root@tuzisir dnmp]# docker-compose up
Building php72
Step 1/14 : ARG PHP_VERSION
ERROR: Service 'php72' failed to build: Please provide a source image with `from` prior to commit

**Comment by yeszao** [comment]
修改的Dockerfile文件吧？要确保改得符合语法哦～

**Comment by YatShen** [comment]
我直接clone下来运行也会报这个错误。
docker版本：1.13.1
docker-compose版本：1.22.0
请问是什么原因呢？

**Comment by yeszao** [comment]
看来是PHP_VERSION变量没正常导到dockerfile里面

**Comment by yeszao** [comment]
现在是什么情况呢？在Windows系统下用吗？

**Comment by fengke549015** [comment]
我也会出现这个情况
`Step 1/12 : ARG PHP_VERSION
ERROR: Service 'php72' failed to build: Please provide a source image with `from` prior to commit
`
没改过任何东西，拉下来就这样

**Comment by fengke549015** [comment]
> Step 1/12 : ARG PHP_VERSION
ERROR: Service 'php72' failed to build: Please provide a source image with `from` prior to commit

**Comment by yeszao** [comment]
更新下docker版本，因为我们通过ARG传递版本号，所以需要`docker 17.05+`
国内网络可到这里下载：[https://oomake.com/download/docker-windows](https://oomake.com/download/docker-windows)
