### ISSUE TITLE
Parse error: syntax error, unexpected ''keys.tags.pu' (T_ENCAPSED_AND_WHITESPACE) in /var/www/html/composer-setup.php on line 658

### ISSUE THREAD

**Issue by yszar** [yeszao/dnmp#66]
Parse error: syntax error, unexpected ''keys.tags.pu' (T_ENCAPSED_AND_WHITESPACE) in /var/www/html/composer-setup.php on line 658
ERROR: Service 'php56' failed to build: The command '/bin/sh -c php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"     && php composer-setup.php     && php -r "unlink('composer-setup.php');"     && mv composer.phar /usr/local/bin/composer     && composer config -g repo.packagist composer https://packagist.laravel-china.org' returned a non-zero code: 255

请问这个错误怎么解决

**Comment by yszar** [comment]
目前暂时将Dockerfile里关于composer的一段注释掉了

**Comment by yeszao** [comment]
composer安装换了地址，可以重新拉一份，或者把Dockerfile中的：
```
RUN php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
```
改为：
```
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
```
