### ISSUE TITLE
我遇到一个情况，停在partition-engine-check很长时间，最后返回timeout的？

### ISSUE THREAD

**Issue by guiqide** [yeszao/dnmp#7]
安装的步骤完成后，进入下面的步骤停在这个步骤很长时间：
`mysql_1    | 2017-10-24T06:40:54.275419Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mysql_1    | 2017-10-24T06:40:54.303899Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
mysql_1    | 2017-10-24T06:40:54.313734Z 0 [Note] InnoDB: Log scan progressed past the checkpoint lsn 12169644
mysql_1    | 2017-10-24T06:40:54.313766Z 0 [Note] InnoDB: Doing recovery: scanned up to log sequence number 12169653
mysql_1    | 2017-10-24T06:40:54.313771Z 0 [Note] InnoDB: Database was not shutdown normally!
mysql_1    | 2017-10-24T06:40:54.313774Z 0 [Note] InnoDB: Starting crash recovery.
mysql_1    | 2017-10-24T06:40:54.479369Z 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
mysql_1    | 2017-10-24T06:40:54.479411Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mysql_1    | 2017-10-24T06:40:54.480688Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mysql_1    | 2017-10-24T06:40:54.527029Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mysql_1    | 2017-10-24T06:40:54.530717Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
mysql_1    | 2017-10-24T06:40:54.530751Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
mysql_1    | 2017-10-24T06:40:54.531030Z 0 [Note] InnoDB: Waiting for purge to start
mysql_1    | 2017-10-24T06:40:54.582195Z 0 [Note] InnoDB: 5.7.20 started; log sequence number 12169653
mysql_1    | 2017-10-24T06:40:54.582816Z 0 [Note] Plugin 'FEDERATED' is disabled.
mysql_1    | 2017-10-24T06:40:54.584021Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mysql_1    | 2017-10-24T06:40:54.621035Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
mysql_1    | 2017-10-24T06:40:54.632924Z 0 [Warning] CA certificate ca.pem is self signed.
mysql_1    | 2017-10-24T06:40:54.634393Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
mysql_1    | 2017-10-24T06:40:54.634449Z 0 [Note] IPv6 is available.
mysql_1    | 2017-10-24T06:40:54.634456Z 0 [Note]   - '::' resolves to '::';
mysql_1    | 2017-10-24T06:40:54.634470Z 0 [Note] Server socket created on IP: '::'.
mysql_1    | 2017-10-24T06:40:54.641016Z 0 [Note] InnoDB: Buffer pool(s) load completed at 171024  6:40:54
mysql_1    | 2017-10-24T06:40:54.663197Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2017-10-24T06:40:54.663240Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2017-10-24T06:40:54.663851Z 0 [Warning] 'db' entry 'performance_schema mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2017-10-24T06:40:54.663870Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2017-10-24T06:40:54.664440Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2017-10-24T06:40:54.699472Z 0 [Warning] 'tables_priv' entry 'user mysql.session@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2017-10-24T06:40:54.699500Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
mysql_1    | 2017-10-24T06:40:54.886573Z 0 [Note] Event Scheduler: Loaded 0 events
mysql_1    | 2017-10-24T06:40:54.887047Z 0 [Note] mysqld: ready for connections.
mysql_1    | Version: '5.7.20-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
mysql_1    | 2017-10-24T06:40:54.887074Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
mysql_1    | 2017-10-24T06:40:54.887078Z 0 [Note] Beginning of list of non-natively partitioned tables
mysql_1    | 2017-10-24T06:40:55.228798Z 0 [Note] End of list of non-natively partitioned tables
`

过很久会显示下面的内容：
`2017-10-24T05:26:51.351060Z 0 [Note] InnoDB: page_cleaner: 1000ms intended loop took 119786ms. The settings might not be optimal. (flushed=0 and evicted=0, during the time.)
`

**Comment by yeszao** [comment]
my.cnf配置：innodb_lru_scan_depth=256
