### ISSUE TITLE
我应该怎么访问宿主机呢

### ISSUE THREAD

**Issue by windyugit** [yeszao/dnmp#70]
我应该怎么访问宿主机呢，求教

**Comment by windyugit** [comment]
我准备把mysql 放宿主机

**Comment by yeszao** [comment]
宿主机可以和容器直接增加一个虚拟网卡，它们通过这个虚拟网卡相互访问，这种情况容器访问宿主机需要指定宿主机在这个虚拟网卡下的IP

**Comment by pointline** [comment]
容器启动后，直接在宿主机127.0.0.1+端口号就可以访问

**Comment by yeszao** [comment]
还有一种方式，`host.docker.internal`也是指向Host的
