### ISSUE TITLE
windowns 安装报错。

### ISSUE THREAD

**Issue by Irving-yang** [yeszao/dnmp#71]
![tim 20181025144449](https://user-images.githubusercontent.com/11228413/47480928-969cfc80-d864-11e8-8472-cf6da49bccfe.png)
/bin/sh: 1: /tmp/extensions/install.sh: not found

实际上是有的。

**Comment by yeszao** [comment]
是否已解决呢？在Dockerfile里面把这一行注释掉是否可以

**Comment by yeszao** [comment]
或者是不是分区没有权限

**Comment by Irving-yang** [comment]
> 或者是不是分区没有权限

不是，权限都是在C盘，提示复制脚本没复制过去，其他人没遇到过吗  ，我是windows10 docker 开发者最新版

**Comment by cyberfeipunk** [comment]
![image](https://user-images.githubusercontent.com/14144580/48004304-cc3ac300-e14b-11e8-8a7d-92cdedb27c15.png)
将文本换行方式修改为UNIX版的LF

**Comment by yeszao** [comment]
@Irving-yang 是否已解决？
