### ISSUE TITLE
Dockerfile中的repositories修改

### ISSUE THREAD

**Issue by tourze** [yeszao/dnmp#72]
目前个人测试，国内使用 https://packagist.laravel-china.org 源最快，如果主要是国人使用的多的话，建议更换到这个。

**Comment by tourze** [comment]
或者考虑不在docker中带入composer。。。我这里做开发的话，是在宿主机安装这些工具，线上环境也不会带composer

**Comment by yeszao** [comment]
在容器里面安装主要是考虑宿主机再安装PHP的麻烦，在测试测试，可以换个源
