### ISSUE TITLE
Service 'php56' failed to build: Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by cmming** [yeszao/dnmp#75]
docker-compose up ，后提示错误如下

Service 'php56' failed to build: Please provide a source image with `from` prior to commit

系统版本
Linux iz2ze8il673tviee81hrkez 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Docker 版本
Docker version 1.13.1, build 8633870/1.13.1
docker-compose 版本
docker-compose version 1.22.0, build f46880f

**Comment by crazykun** [comment]
我也遇到了,怎么解决的?

**Comment by yeszao** [comment]
升级docker-compose，然后重新克隆一份源码
