### ISSUE TITLE
容器时区都是UTC

### ISSUE THREAD

**Issue by WencoChen** [yeszao/dnmp#76]
&#160; &#160; &#160;&#160; 容器的默认时区都是UTC，但是我看到这个项目里面好像就mysql.cnf里面加了8个小时，那其他的呢？我在docker-compose文件里面添加了`TZ=Asia/Shanghai`，但是php打印出来的时间还是少了8个小时，有什么好的解决方法吗？

**Comment by yeszao** [comment]
进到容器里面，echo $TZ输出是什么呢？
容器里面用date命令出来的时区呢

**Comment by yeszao** [comment]
不行的话可以直接改php.ini，然后重启容器

**Comment by WencoChen** [comment]
```
/var/www $ echo $TZ
>Asia/Shanghai
/var/www $ date
>Tue Oct 30 12:28:06 UTC 2018
```
比现实少8小时，谷歌搜索别人说只需要这样设置就行了，看起来环境变量是生效了，但是时间却并没有改变，摸不着头脑，看来只好改配置了

**Comment by yeszao** [comment]
需要重新build下容器

**Comment by WencoChen** [comment]
原来如此，谢谢
