### ISSUE TITLE
安装php时很卡慢

### ISSUE THREAD

**Issue by xwpd** [yeszao/dnmp#77]
看命令是源更新的慢，基本不动，阿里源。

**Comment by xwpd** [comment]
一般都是卡这些 
Get:2 http://security.debian.org/debian-security buster/updates InRelease [38.3 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian buster InRelease [150 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian buster-updates InRelease [47.6 kB]
Get:6 http://cdn-fastly.deb.debian.org/debian buster/main amd64 Packages [7719 kB]
Get:7 http://mirrors.aliyun.com/debian stretch-updates InRelease [91.0 kB]
阿里云也有些会卡挺久的。
本人100m光纤电信，带自动梯子都卡。。。。

**Comment by yeszao** [comment]
似乎不是buster，Jessie或者stretch

**Comment by xwpd** [comment]
安装的时候，会自动更新这些，我自己把把对应国内源加上就很快了
