### ISSUE TITLE
Y大是不是忘了更新本地代码

### ISSUE THREAD

**Issue by kleveralt** [yeszao/dnmp#81]
https://github.com/yeszao/dnmp/blob/master/Dockerfile#L24
此处应该有一个设置mt变量（你改成了mc）的代码

https://github.com/yeszao/dnmp/blob/cea37ce8d2bc0e6b58f6d004664f814406afb30c/Dockerfile#L34
这一行怎么消失了?

php5.4的docker-php-ext-install也是不支持多线程编译的所以要加一下版本判断

**Comment by kleveralt** [comment]
看到install.sh变动了

**Comment by yeszao** [comment]
嗯，我改了下名字，mc = Multicore compilation，方便理解点

**Comment by yeszao** [comment]
思路是参考你的

**Comment by kleveralt** [comment]
我是在纳闷现在怎么冲突了，不知道怎么合并你的更新了，不太会用git @@

https://github.com/kleveralt/dnmp/pull/1

**Comment by yeszao** [comment]
等等，我还在改，打算用.env文件
你改了哪部分了呢？

**Comment by kleveralt** [comment]
我没在改 目前已经非常好使了

nginx的配置文件有一处
https://github.com/yeszao/dnmp/blob/master/conf/conf.d/localhost_https.conf#L14
这个ssl on指令可以拿掉

我在研究看看要怎么合并你的更新过来

**Comment by yeszao** [comment]
我又重新改了下，用.env来配置一些参数。
你提交的ifconfig判断方法非常好，不过我还是担心网络问题导致安装失败，所以也用.env来让使用者手动配置。有的朋友提议用curl/wget从php网站获取扩展包再安装，我试了几次，还是得翻墙才行，所以还是保留用下载好的扩展包。
咱这网络环境，也是无语啊

**Comment by kleveralt** [comment]
哈哈国内从php.net下载会下到吐血的
