### ISSUE TITLE
docker toolbox部署dnmp遇到的好多问题，哪位耐心大神帮忙看看

### ISSUE THREAD

**Issue by enboo** [yeszao/dnmp#82]
1.![image](https://user-images.githubusercontent.com/39607705/48259359-ad417700-e452-11e8-93c4-79037dd1bcf4.png)

2.
![image](https://user-images.githubusercontent.com/39607705/48259549-3eb0e900-e453-11e8-9c12-8e1495e35c36.png)

3.
![image](https://user-images.githubusercontent.com/39607705/48259610-79b31c80-e453-11e8-8a26-f6ee147657a4.png)

4.
![image](https://user-images.githubusercontent.com/39607705/48259745-e4645800-e453-11e8-8917-96c28e6703f3.png)

5.
![image](https://user-images.githubusercontent.com/39607705/48259777-12499c80-e454-11e8-8104-3420706919e3.png)

6.
![image](https://user-images.githubusercontent.com/39607705/48259955-b29fc100-e454-11e8-9c5e-f509ba205ecd.png)

这个是啥玩意

**Comment by yeszao** [comment]
这些只是警告而已，不影响，可略过

**Comment by enboo** [comment]
是的，能不用docker toolbox还是升级win10家庭版到专业版，我这里用专业版来up能行，正在学习，感谢
