### ISSUE TITLE
宿主机安装composer，如何与php容器进行关联

### ISSUE THREAD

**Issue by enboo** [yeszao/dnmp#85]
win10，composer安装需要绑定关联php.exe，如何关联

**Comment by alexxd35** [comment]
宿主机使用composer是需要在宿主机安装php？

**Comment by yeszao** [comment]
目前知道的方法：
1. 在容器里面安装composer
2. 使用docker 的 composer 镜像
3. 宿主机安装PHP再安装composer

可任选一种

**Comment by enboo** [comment]
我使用的是第二种方法，单独的composer镜像，在使用过程中composer容器不是后台一直运行，是单独的一次次使用，不需要-d，我这里使用起来的指令是：

**Comment by yeszao** [comment]
最新更新在主机中使用composer方法：https://github.com/yeszao/dnmp/blob/master/README.md#6%E4%BD%BF%E7%94%A8composer

**Comment by daulCN** [comment]
> 最新更新在主机中使用composer方法：https://github.com/yeszao/dnmp/blob/master/README.md#6%E4%BD%BF%E7%94%A8composer

请问在windows下有类似的方法吗？

**Comment by daulCN** [comment]
自己写了一个windows的bat文件

```
@ECHO off
:composer
docker run -it --rm -v %cd%:/app composer %*
goto:eof
```

将文件命名为composer.bat，然后加到环境变量中，就能正常使用composer了

**Comment by yeszao** [comment]
@daulCN 赞！

**Comment by fengyunye** [comment]
> 自己写了一个windows的bat文件
> 
> ```
> @ECHO off
> :composer
> docker run -it --rm -v %cd%:/app composer %*
> goto:eof
> ```
> 将文件命名为composer.bat，然后加到环境变量中，就能在windows下正常使用composer了
你好，我想问下，这种方式应该并没有把配置文件放到宿主机中吧，那如何使用国内镜像仓库呢？

**Comment by fengyunye** [comment]
@daulCN 
> 自己写了一个windows的bat文件
> 
> ```
> @ECHO off
> :composer
> docker run -it --rm -v %cd%:/app composer %*
> goto:eof
> ```
> 将文件命名为composer.bat，然后加到环境变量中，就能在windows下正常使用composer了




你好，请问这种方式如何配置镜像仓库，好像并没有把配置文件放到宿主级中吧？

**Comment by daulCN** [comment]
> @daulCN
> 
> > 自己写了一个windows的bat文件
> > ```
> > @ECHO off
> > :composer
> > docker run -it --rm -v %cd%:/app composer %*
> > goto:eof
> > ```
> > 将文件命名为composer.bat，然后加到环境变量中，就能在windows下正常使用composer了
> 
> 你好，请问这种方式如何配置镜像仓库，好像并没有把配置文件放到宿主级中吧？

已更新

**Comment by fengyunye** [comment]
@daulCN  多谢解答

**Comment by im55cc** [comment]
@daulCN 
![docker](https://user-images.githubusercontent.com/10059014/56180968-20709a00-603e-11e9-83d7-0c11afa9662e.png)
为什么我在E盘可以成功，但是切到 E:\test\ 目录下就报错了？

**Comment by dyxxxyd** [comment]
@popdaul 用这种方式，composer 容器内的php是8.0版本的，如果php容器版本是7.* 那么创建的项目就会有问题。引入的库PHP>=8.0.0
