### ISSUE TITLE
Ubuntu 16.04.5 LTS执行built失败

### ISSUE THREAD

**Issue by qq516249940** [yeszao/dnmp#87]
Step 2/12 : FROM php:${PHP_VERSION}-fpm
 ---> 9d11d506e313
Step 3/12 : ARG PHP_XDEBUG
 ---> Using cache
 ---> 441010ef6653
Step 4/12 : ARG PHP_SWOOLE
 ---> Using cache
 ---> 254144ad3de4
Step 5/12 : ARG PHP_REDIS
 ---> Using cache
 ---> 6f4b2cd5f566
Step 6/12 : ARG REPLACE_SOURCE_LIST
 ---> Using cache
 ---> e7cd243873be
Step 7/12 : COPY ./sources.list /etc/apt/sources.list.tmp
 ---> Using cache
 ---> c66877cd83b6
Step 8/12 : RUN if [ "${REPLACE_SOURCE_LIST}" = "true" ]; then     mv /etc/apt/sources.list.tmp /etc/apt/sources.list; else     rm -rf /etc/apt/sources.list.tmp; fi
 ---> Using cache
 ---> 5905292f066e
Step 9/12 : RUN apt update
 ---> Using cache
 ---> df42722adec4
Step 10/12 : COPY ./extensions /tmp/extensions
 ---> Using cache
 ---> 011798b14af7
Step 11/12 : RUN chmod +x /tmp/extensions/install.sh     && /tmp/extensions/install.sh     && rm -rf /tmp/extensions
 ---> Running in 7b683a2ceaaa
/bin/sh: 1: /tmp/extensions/install.sh: Text file busy
ERROR: Service 'php72' failed to build: The command '/bin/sh -c chmod +x /tmp/extensions/install.sh     && /tmp/extensions/install.sh     && rm -rf /tmp/extensions' returned a non-zero code: 2

**Comment by qq516249940** [comment]
liusuwanqing@ken:~/dnmp$ sudo docker-compose up     
Building php72
Step 1/12 : ARG PHP_VERSION
Step 2/12 : FROM php:${PHP_VERSION}-fpm
 ---> 9d11d506e313
Step 3/12 : ARG PHP_XDEBUG
 ---> Using cache
 ---> 441010ef6653
Step 4/12 : ARG PHP_SWOOLE
 ---> Using cache
 ---> 254144ad3de4
Step 5/12 : ARG PHP_REDIS
 ---> Using cache
 ---> 6f4b2cd5f566
Step 6/12 : ARG REPLACE_SOURCE_LIST
 ---> Using cache
 ---> e7cd243873be
Step 7/12 : COPY ./sources.list /etc/apt/sources.list.tmp
 ---> Using cache
 ---> c66877cd83b6
Step 8/12 : RUN if [ "${REPLACE_SOURCE_LIST}" = "true" ]; then     mv /etc/apt/sources.list.tmp /etc/apt/sources.list; else     rm -rf /etc/apt/sources.list.tmp; fi
 ---> Using cache
 ---> 5905292f066e
Step 9/12 : RUN apt update
 ---> Using cache
 ---> df42722adec4
Step 10/12 : COPY ./extensions /tmp/extensions
 ---> Using cache
 ---> 011798b14af7
Step 11/12 : RUN chmod +x /tmp/extensions/install.sh     && /tmp/extensions/install.sh     && rm -rf /tmp/extensions
 ---> Running in 85f94c5e36e1
/bin/sh: 1: /tmp/extensions/install.sh: Text file busy
ERROR: Service 'php72' failed to build: The command '/bin/sh -c chmod +x /tmp/extensions/install.sh     && /tmp/extensions/install.sh     && rm -rf /tmp/extensions' returned a non-zero code: 2

没有更改过任何文件。
liusuwanqing@ken:~/dnmp$ tree
.
├── conf
│   ├── conf.d
│   │   ├── certs
│   │   │   └── localhost
│   │   │       ├── gencert.sh
│   │   │       ├── localhost.crt
│   │   │       ├── localhost.csr
│   │   │       ├── localhost.key
│   │   │       └── localhost.origin.key
│   │   ├── localhost.conf
│   │   └── localhost_https.conf
│   ├── mysql.cnf
│   ├── nginx.conf
│   ├── php-fpm.conf
│   └── php.ini
├── dnmp.png
├── docker-compose.yml
├── Dockerfile
├── env.sample
├── extensions
│   ├── install.sh
│   ├── redis-4.1.1.tgz
│   ├── swoole-2.0.11.tgz
│   ├── swoole-4.2.1.tgz
│   ├── xdebug-2.4.1.tgz
│   ├── xdebug-2.5.5.tgz
│   ├── xdebug-2.6.1.tgz
│   └── zendopcache-7.0.5.tgz
├── LICENSE
├── log
├── mysql
├── README-en.md
├── README.md
├── snapshot.png
├── sources.list
└── www
    └── localhost
        └── index.php

9 directories, 29 files

**Comment by yeszao** [comment]
在dockerfile中把这里
```
chmod +x /tmp/extensions/install.sh && /tmp/extensions/install.sh && rm -rf /tmp/extensions
```
拆分成单独的每个RUN行，看提示什么错误

**Comment by qq516249940** [comment]
> 在dockerfile中把这里
> 
> ```
> chmod +x /tmp/extensions/install.sh && /tmp/extensions/install.sh && rm -rf /tmp/extensions
> ```
> 拆分成单独的每个RUN行，看提示什么错误

拆分竟然可以了！

**Comment by qq516249940** [comment]
可能shell的编码没有转换吧，我用centos7是通过，ubuntu失败。

**Comment by qq516249940** [comment]
可能shell的编码

**Comment by yeszao** [comment]
已经加了.gitattribute 文件，应该是都没问题了
