### ISSUE TITLE
windows10 上报错 /bin/sh: 1: /tmp/extensions/install.sh: not found

### ISSUE THREAD

**Issue by liumingsongning** [yeszao/dnmp#88]
windows10 上报错 /bin/sh: 1: /tmp/extensions/install.sh: not found

**Comment by yeszao** [comment]
看这：https://github.com/yeszao/dnmp/issues/86

**Comment by yeszao** [comment]
git的自动修改回车换行号引起的，加了gitattibutes ，强制.sh用unix换行，重新从master 拉一份
