### ISSUE TITLE
查看代码是安装指定版本的swoole

### ISSUE THREAD

**Issue by wangliangl** [yeszao/dnmp#89]
实际运行完之后并没有安装成功swoole扩展

**Comment by yeszao** [comment]
PHP5.4不支持swoole，其他两个版本是有的

如果在.env改了版本，要下载对应版本到extensions目录

**Comment by wangliangl** [comment]
我的php版本是7.2
这个是在容器内看的
root@7a246f8d25dd:/var/www/html# php -v
PHP 7.2.7 (cli) (built: Jul  6 2018 16:11:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.7, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
root@7a246f8d25dd:/var/www/html# php -m |grep swoole
root@7a246f8d25dd:/var/www/html#

**Comment by yeszao** [comment]
在.env里面改了版本号吗

**Comment by wangliangl** [comment]
clone下来后就没有任何的改动,然后直接就build的。发现p7确实是没有swoole扩展的，但是我手动的去env里面更新成最新版的swoole版本后就安装上了。
