### ISSUE TITLE
mysql log couldn't be generated 

### ISSUE THREAD

**Issue by peyoot** [yeszao/dnmp#9]
I run it in ubuntu 16.04 and get error:
mysql_1    | mysqld: File '/var/log/mysql/mysql-slow.log' not found (Errcode: 13 - Permission denied)
mysql_1    | 2017-11-29T07:57:28.288062Z 0 [ERROR] Could not use /var/log/mysql/mysql-slow.log for logging (error 13 - Permission denied).

I wonder why this mysql-slow.log couldn't be generated automatically? should we manually touch one?

**Comment by yeszao** [comment]
It prompts that user mysql cannot create and write this file.
These is because `/var/log/mysql` is belong to root in container.
To avoid this, we can:

1.  change the owner of `/var/log/mysql` in container:
```
chown -R mysql:mysql /var/log/mysql:
```
Then restart container.

2 use `/var/lib/mysql` instead of `/var/log/mysql`
```
 volumes:
    ...
    - ./log/mysql/:/var/lib/mysql/:rw
```
