### ISSUE TITLE
mysqld 占用内存过大

### ISSUE THREAD

**Issue by jianghan200** [yeszao/dnmp#93]
mysqld 占用了 38.2% 的内存，我用的是1G1核的机器，lnmp 的 mysql 只会占据3%的内存
当然 dnmp 是8.0的 mysql， lnmp 是5.7的，不知这个都是这样吗？还是异常？

**Comment by yeszao** [comment]
修改 mysql.cnf 文件，把一些用到内存的配置调小一些
