### ISSUE TITLE
你好，我像询问下添加网站的方式

### ISSUE THREAD

**Issue by zl1x** [yeszao/dnmp#94]
我以前用的是普通的lnmp,可以一键添加vhost,就是不用自己写那个网站的nginx的.conf,请问您的dnmp可以这样吗，还是得自己写好.conf然后把网站文件加进去才行？

**Comment by skylei** [comment]
![image](https://user-images.githubusercontent.com/1855591/49429135-b966ed00-f7e2-11e8-804f-632e5e9a809b.png)
直接进行拷贝.localhost.conf编辑一下即可;
![image](https://user-images.githubusercontent.com/1855591/49429217-f337f380-f7e2-11e8-8521-6a3a1cc8e479.png)

**Comment by zl1x** [comment]
请问是只要编辑root那块吗，下面的内容需要对应编辑吗

**Comment by skylei** [comment]
@zl1x 对的

**Comment by zl1x** [comment]
谢谢老哥解答

**Comment by Orocker** [comment]
@zl1x 这个root路径是容器内部的还是宿主机上面的路径？
